### ISSUE TITLE
پیغام خطا هنگام بیلد

### ISSUE THREAD

**Issue by EhsanErshadi** [Mds92/MD.BootstrapPersianDateTimePicker#1]
سلام
هنگام بیلد خطای زیر رو میده:
Error	1	The name 'RouteConfig' does not exist in the current context	D:\Sync\Work\GitHubRepo\MD.BootstrapPersianDateTimePicker\MD.BootstrapPersianDateTimePicker\Global.asax.cs	14	13	MD.BootstrapPersianDateTimePicker

**Comment by Mds92** [comment]
سلام
معلومه خطا میده !!!
این پروژه سی شارپ نیست، فقط برید داخل پوشه ویو و فایل های اچ تی ام ال رو اجرا کنید
