### ISSUE TITLE
datepicker footer امروز weekday ob1

### ISSUE THREAD

**Issue by ehsanamini** [Mds92/MD.BootstrapPersianDateTimePicker#10]
weekday of today in the footer is off by 1 day

I fixed it by changing line 331 from:

todayDateTimeString = 'امروز، ' + getPersianWeekDay(**persianTodayDateTemp[2]**) + ' ' + toPersianNumber(currentDayNumber) + ' ' + getPersianMonth(currentMonthNumber) + ' ' + toPersianNumber(currentYearNumber),

to

todayDateTimeString = 'امروز، ' + getPersianWeekDay(**(persianTodayDateTemp[2]+6)%7**) + ' ' + toPersianNumber(currentDayNumber) + ' ' + getPersianMonth(currentMonthNumber) + ' ' + toPersianNumber(currentYearNumber),

(persianTodayDateTemp[2]**+6**)**%7** was chosen rather than simply (persianTodayDateTemp[2]**-1**) to avoid getting a possibly negative function argument on Sunday.

It seems to work for today, haven't yet tested it for other days though.
Alternatively, relying on the JS native i18n API, replacing the entire RHS with **'امروز، ' + (new Date).toLocaleDateString("fa-IR", {weekday: "long",  year: "numeric",  month: "long",  day: "numeric"}).slice(0, -5),** will also do the trick and be less of a hack.

**Comment by Mds92** [comment]
Thanks for your report and sample code.
I'll fix it in next version, as soon as possible

**Comment by Mds92** [comment]
Get the new version
