### ISSUE TITLE
تریگر تغییر بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by Ali-Azmoud** [Mds92/MD.BootstrapPersianDateTimePicker#100]
درود.
در حال حاضر وقتی تاریخی رو انتخاب میکنیم رویداد
change
اجرا نمیشه

وقتی دارید مقدار تکست رو عوض میکنید لطفا 
.trigger('change')
هم در انتهای تکست باکس بزارید تا رویداد اجرا بشه

ممنون

**Comment by Mds92** [comment]
ممنون از توجه شما
لطفا آخرین ورژن را دریافت نمائید
