### ISSUE TITLE
مشکل عمل نکردن disabledDates

### ISSUE THREAD

**Issue by EmadMi** [Mds92/MD.BootstrapPersianDateTimePicker#102]
سلام

تغییرات ورژن جدید واقعا عالیه ممنونم از زحماتتون

فقط من هرکاری میکنم disabledDates کار نمیکنه

نمونه کدی که استفاده کردم اینه

$('#Date').MdPersianDateTimePicker({
            targetTextSelector: '#Date',
            targetDateSelector: '#hdfDate',
            enableTimePicker: false,
            textFormat: 'yyyy/MM/dd',
            dateFormat: 'yyyy/MM/dd',
            disabledDates: [new Date(2018, 10, 31)],
            disableBeforeToday: true,
            yearOffset: 2,
        });

ممنون میشم راهنمایی کنین منو

مرسی

**Comment by Mds92** [comment]
سلام
من تست کردم مشکلی نیست
دقت شود که تاریخ 
new Date(2018, 10, 31)
یعنی 10 آذر 1397
ماه های میلادی از 0 شروع میشن تا 11
