### ISSUE TITLE
تفاوت تاریخ های تبدیلی میلادی

### ISSUE THREAD

**Issue by EmadMi** [Mds92/MD.BootstrapPersianDateTimePicker#104]
سلام
توی تبدیل تاریخ گفتین که مثلا 2018/10/31 میشه 10 آذر

ولی من وقتی 10 آذر رو تبدیل تاریخ میزنم توی تقویم میشه 2018/12/01

که طبق گفته ی شما باید یکماه ازش کم کنم

که میشه 2018/11/01 و این با مقدار شما متفاوته

سوالم اینه که شما مقدار ثابتی رو کم میکنین همیشه؟؟؟

من بخاطر مورد استفادم خیلی مهمه واسم که بخش بسته شدن تاریخ دقیق کار کنه

ممنونم

**Comment by Mds92** [comment]
"2018/10/31" همون ماه 10 هست
ممنون میشم بگید من کجا گفتم تو این مدل تاریخ ماه یکی کم میشه
لطفا مطالعه نمائید
https://www.w3schools.com/jsref/jsref_obj_date.asp
سوالات مربوط به جاوااسکریپت را جای دیگر مطرح کنید

**Comment by EmadMi** [comment]
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/issues/102#issuecomment-435558266

شما اینجا گفتین توی این تقویم ماه های میلادی از 0 تا 11 هستن

من توی بانک اطلاعاتیم به دلایلی باید تاریخ شمسی رو ذخیره کنم

توی هر تبدیل تاریخی هم محاسبه کنین اون تاریخ تستی رو بهتون 2018/12/01 میده

![datepicker](https://user-images.githubusercontent.com/44611997/48019752-6a795980-e149-11e8-9776-51f8edc8733d.PNG)

و طبق گفته ی شما من باید یک ماه از این مقدار کم کنم چون ماه های میلادی از صفر شروع میشن ولی توی واقعیت تاریخ از 1 شروع میشه

ولی انگار شما بجای 30 روز دارین 31 روز کم میکنین از تاریخ اصلی

و این 31 روز ثابته انگار ...

عذر میخوام اگر که سوالم مضحکه مهندس جان

ولی برای من دونستن این موضوع خیلی مهمه

ممنون میشم اگر من رو راهنمایی کنین تا از

 تجاربتون بی نصیب نمونم

**Comment by Mds92** [comment]
همان طور که تو کامنتی که شما لینک دادید گفتم تو مقدار دهی تاریخ به شکل زیر
new Date()
ماه از 0 شروع میشه نه فرمتی که شما نوشتید به شکل 2018/10/31
تاریخ 2018/10/31 همان ماه 10 میلادی است که ربطی به آبجکت دیت در جاوااسکریپت ندارد
برای تبدیل فرمت 2018/10/31 به آبجکت دیت باید به شکل زیر عمل کنید
new Date(Date.parse('2018/10/31'))
اگر میخواهید بهتر بلد بشید باید مطالعه کنید، با کد نوشتن تنها نمیشه همه را مطلع شید
https://www.w3schools.com/jsref/jsref_obj_date.asp
