### ISSUE TITLE
مشکل با Build شدن در NPM

### ISSUE THREAD

**Issue by aliqasemzadeh** [Mds92/MD.BootstrapPersianDateTimePicker#105]
سلام
وقت بخیر
من می خواهم از 
datepicker 
شما به صورت زیر در 
laravel mix
استفاده کنم.
window.MdPersianDateTimePicker = require('md.bootstrappersiandatetimepicker');

اما به نظر می رسد که 
module loader 
ندارد

به نظرم این طوری خیلی سخته با این ماژول کار کرد.

**Comment by Mds92** [comment]
با سلام
این یه پلاکین جی کوئری هست و بعید میدونم بتونید به این راحتی به شکل 
laravel mix
ازش استفاده کنید

**Comment by aliqasemzadeh** [comment]
سلام
یعنی ماژول لودر نداره؟

**Comment by Mds92** [comment]
خیر نداره

**Comment by aliqasemzadeh** [comment]
سلام
ایکاش اضافه کنید چون خیلی خوبه و کار را آسان می کند.

مگه webpack 
نیست؟

**Comment by vahidalvandi** [comment]
بله من هم به همین دلیل به مشکل خوردم

**Comment by aliqasemzadeh** [comment]
@vahidalvandi  @Mds92 
سلام
یک نفر باید ماژول لودر را اضافه کند

**Comment by vahidalvandi** [comment]
in laravel mix you can copy in destination path

```
mix.copy('node_modules/md.bootstrappersiandatetimepicker/dist/jquery.md.bootstrap.datetimepicker.js', 'public/app/js/libs/jquery.md.bootstrap.datetimepicker.js');
mix.copy('node_modules/md.bootstrappersiandatetimepicker/dist/jquery.md.bootstrap.datetimepicker.style.css', 'public/app/css/libs/jquery.md.bootstrap.datetimepicker.style.css');

```
