### ISSUE TITLE
disabledates

### ISSUE THREAD

**Issue by ya3aman** [Mds92/MD.BootstrapPersianDateTimePicker#106]
با سلام 
من در تقویم ، خاصیت از تاریخ تا تاریخ رو فعال کردم
حالا میخوام وقتی کاربر روی تقویم اول تاریخی رو انتخاب میکنه ، بر اساس این تاریخ انتخابی ، یک سری تاریخ در تقویم دوم رو بلاک یا دیزیبل کنم . راه کاری براش پیدا نکردم ، میشه راهنمایی کنید ؟
ممنون میشم

**Comment by Mds92** [comment]
Hello,
For the problem I added `setOption` method. (v3.2.8)
You can call it in `change` event.
e.g:
`$('#date1').MdPersianDateTimePicker('setOption', 'disabledDates', [])`
