### ISSUE TITLE
در راست چین شده مشکل دارد

### ISSUE THREAD

**Issue by vahidalvandi** [Mds92/MD.BootstrapPersianDateTimePicker#109]
در راست چین بودن 
bootstrap 4 
مشکل دارد هنگامی که این راست چین را داشته باشیم
https://github.com/vahidalvandi/bootstrap4-rtl

**Comment by Mds92** [comment]
این کتابخانه با استاندارد خود 
Bootstrap 4+
نوشته شده
برای استفاده از کتابخانه های راست چین کردن و ... خودتان باید زحمت بکشید و 
CSS
های مورد نیاز خودتان را درست کنید

**Comment by Mds92** [comment]
لازم به ذکر است که در بوت استرپ 4 نیاز به کتابخانه ای جدا برای راست چین کردن ندارید
از روش استاندارد زیر استفاده نمائید
`<html dir="rtl">`

**Comment by vahidalvandi** [comment]
این به تنهایی کفایت نمی کند
