### ISSUE TITLE
قرار دادن تاریخ انتخابی در value 

### ISSUE THREAD

**Issue by iranidesign** [Mds92/MD.BootstrapPersianDateTimePicker#11]
با سلام اول تشکر بابت زحمتتون
یک مشکل هست و اون این هست که چطور میتونم تاریخ انتخابی به این فرمت 1395/05/23  به خاصیت value انتخابی قرار بدم روی  input box و از اونجا در برنامه mvc خودم ارسال کنم به اکشن متد ؟ ممنونم

**Comment by Mds92** [comment]
سلام، خواهش میکنم
ببنید اول باید با استفاده از جاوا اسکریپت مقدار مورد نظرتون رو توی اینپوت تاریخ قرار بدید
```
$('#IdOdYourInput').val('1395/03/01');
```
اما برای ارسال اون به اکشن ام وی سی باید از سی شارپ استفاده کنید
اول باید یه پروپرتی تو ویو مدل خودتون ایجاد کنید
بعد اونو تو ویو خودتون استفاده کنید و تو اکشن از اون استفاده کنید

**Comment by iranidesign** [comment]
ممنونم صحیح میفرمایید این کارها انجام شده فقط سوال این هست که شما مقدار رو به صورت json به این خاصیت assign میکنید ؛data-mdpersiandatetimepickerselecteddatetime؛ من احتیاج دارم پس از انتخاب تاریخ مورد نظر به این فرمت در پراپرتی value  قرار بگیرد یعنی به این صورت value="1395/05/27

**Comment by Mds92** [comment]
من به صورت جی سان ذخیره نمیکنم
به صورت زیر ذخیره میکنم
```value="1395/05/27"```

**Comment by iranidesign** [comment]
چیزی که من میبینم این هست 

`data-mdpersiandatetimepickerselecteddatetime="{"Year":1395,"Month":3,"Day":4,"Hour":0,"Minute":0,"Second":0}"`

**Comment by Mds92** [comment]
ببینید این اتریبیوت برای پردازش های خود نرم افزارم هست
شما میتونید به مقدار داخل تکس باکس به صورت زیر دست پیدا کنید و نتیجه رو ببینید
```
$('#IdOdYourInput').val();
```

**Comment by iranidesign** [comment]
اها ممنونم متوجه شدم فقط یک سوال آیا date picker برای تاریخ میلادی هم ویرایش شده یا خیر ؟ دوم اینکه آیا دیت پیکر خوبی برای تاریخ میلادی مانند کنترل خودتون میشناسید معرفی کنید به من؟

**Comment by Mds92** [comment]
نه متاسفانه نمیشناسم
بهترین حالت اینه که روی همین من میلادی رو هم پیاده کنم 
که به علت مشغله کاری فرصت نکردم هنوز

**Comment by djary** [comment]
ظاهرا با asp.net mvc 5 مشکل دارد
من از طریق این کد 
        $("#TimepickerAz").on("propertychange change click keyup input paste", function () {
            $("#DiscountStartDate").val($(this).val());
                alert($(this).val());
        });
مقدار رو میگیرم به میدم به فیلد  hiden
و آن را به سمت سرور پاس میدم اما به کنترلر null 
پاس میده 
خیلی عجیبه

**Comment by Mds92** [comment]
این یه کد طرف کلاینت هست، منظورتون رو از اینکه با ام وی سی مشکل داره متوجه نمیشم !!!!
مشکل از طرف کدهای خودتون هست که تو اکشن کنترلر نال میبینید نه کدهای طرف کلاینت

**Comment by djary** [comment]
من وقتی به صورتی دستی تاریخ وارد میکنم درست ارسال میکنه مثلا اینطوری
1395/05/05
ولی اگر همین تاریخ رو از  تایم پیکر ، پیک کنم نال میفرسته
خودمم گیج شدم نمیدونم مشکل از کجاست
