### ISSUE TITLE
اعداد انگلیسی و فارسی

### ISSUE THREAD

**Issue by ghamshekan** [Mds92/MD.BootstrapPersianDateTimePicker#111]
در برخی پلتفرم های سرویس وقتی اعداد فارسی ارسال میشوند شناسایی نمی شوند، از طرفی مورد نظر است که نمایش تاریخ ها در  تقویم با اعداد فارسی باشند، 
ویژگی جدید برای اعداد تاریخ انتخاب شده و اعداد نمایش داده شده در تقویم وجود داشته باشد. در حال حاضر فقط یک ویژگی وجود دارد.

**Comment by Mds92** [comment]
لطفا قبل از سوال مطالعه کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

1. با مقدار دهی englishNumber اعداد انگلیسی می شوند
2. targetDateSelector را مقدار دهی کنید تا پلاگین معادل DateTime انتخاب شده را در آن قرار دهد و آن را طرف سرور استفاده نمائید

**Comment by ghamshekan** [comment]
در این صورت اعدادی که در تقویم نمایش داده میشود انگلیسی میشوند، منظورم این
بود اعداد تقویم انگلیسی نشه، مشکل دیگه تو فریم ورک ای بی پی هست که تقویم رو
از یک طرف تبدیل میکنه و لوکالایز میشه بعد از این سمت نه

**Comment by Mds92** [comment]
-  englishNumber را false کنید و از targetDateSelector استفاده کنید.
- یعنی نیاز دارید تا تاریخ UTC باشد؟

**Comment by ghamshekan** [comment]
ممنون
