### ISSUE TITLE
افزودن دیکشنری موارد دلخواه کاربر

### ISSUE THREAD

**Issue by ghamshekan** [Mds92/MD.BootstrapPersianDateTimePicker#113]
افزودن چیزی شبیه دیکشنری برای اضافه شدن اطلاعات دلخواه کاربر درون سلول های جدول تاریخ، یا معرفی تابعی از طرف کاربر برای رندر کردن خروجی ای که در سلول جدول میخواهد نمایش داده شود
![image](https://user-images.githubusercontent.com/47173733/53735279-acb66b80-3e9b-11e9-8a47-e6baf123d25b.png)

**Comment by Mds92** [comment]
پیشنهاد قابل توجهی هست
قصد دارم در اولین فرصت پیاده سازیش رو شروع کنم
