### ISSUE TITLE
removing change year button

### ISSUE THREAD

**Issue by ampadashi** [Mds92/MD.BootstrapPersianDateTimePicker#115]
Hi,
is it possible to remove the right and left arrows designed for year and month changing?

**Comment by Mds92** [comment]
Hello,
You have to edit template of DateTimePicker in source and rebuild it. You can find it in `~/src/jquery.md.bootstrap.datetimepicker.js` line 193, `dateTimePickerHtmlTemplate ` and line 244 `dateTimePickerMonthTableHtmlTemplate`

**Comment by ampadashi** [comment]
Thanks a lot!;)

**Comment by Mds92** [comment]
👍
