### ISSUE TITLE
مشکل در بوت استرپ نسخه 4.3

### ISSUE THREAD

**Issue by SamanSh999** [Mds92/MD.BootstrapPersianDateTimePicker#116]
سلام و تشکر از پکیج خوبتون
پکیج عالی کار میکنه با نسخه 4.0 ولی وقتی
npm 
رو اپدیت کردم و بوت استرپ روی نسخه 4.3 رفتنش دیگه پکیج شما کار نمیکنه

برای تست موضوع همون فایل مثال داخل ریپو رو روی نسخه 4.3.0 بردم و مشکل پابرجا بودش

باتشکر از زحمات شما

**Comment by Mds92** [comment]
با سلام
فعلا با بوت استرپ 4.2.* درست کار میکند
با 4.3 مشکل دارد

**Comment by Mds92** [comment]
درست شد، لطفا آخرین ورژن را دریافت و تست بفرمایید

**Comment by SamanSh999** [comment]
تشکر ویژه از حمایت و سرعت عالی شما
اپدیت کردم و به درستی کار کردش

ممنون از شما
