### ISSUE TITLE
چگونگی فراخوانی یک متد دیگر بعد از انتخاب تاریخ و بسته شدن تقویم  

### ISSUE THREAD

**Issue by dornarad** [Mds92/MD.BootstrapPersianDateTimePicker#117]
یا سلام
من خواستم بپرسم چطور میتونم بعد از انتخاب تاریخ و بسته شدن تقدیم یک متد مقایسه تاریخ رو در برنامه فراخوانی کنم؟
از onblur استفاده کردم ولی موفق نشدم.
ممنون

**Comment by Mds92** [comment]
سلام
باید از اونت های پاپ آور خود بوت استرپ استفاده نمایید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#events
https://getbootstrap.com/docs/4.3/components/modal/#events

**Comment by dornarad** [comment]
با سلام مجدد
ممنون از پاسختون
اما من نمیدونم دقیقا توی فرم چطور برای هاید تابع رو بنویسم.

**Comment by Mds92** [comment]
تو لینک هایی که بهتون دادم نمونه کدش هست
اگر باز هم متوجه نشدید سرچ کنید، نمونه کدهاش زیاد هست

**Comment by dornarad** [comment]
کلا آیا بعد از انتخاب شدن تاریخ از تقویم راهی برای محاسبه اختلاف تاریخ انتخاب شده با تاریخ جاری روز وجود دارد؟
من میخوام که این مقدار اختلاف به روز به فرم اصلی برنامه پاس داده بشه.

**Comment by dornarad** [comment]
سلام وقت به خیر
ببخشید دوباره مزاحم شدم. خواستم بپرسم قسمت کد فرم در بخش جاوا اسکریپت جایی که میخوام کد زیر رو بنویسم به جای mypopover چی بنویسم؟

$('#mypopover').on ('hidden.bs.popover .....

**Comment by Mds92** [comment]
سلام
باید سلکتوری رو بنویسید که باهاش تقویم رو فعال کردید
