### ISSUE TITLE
بستن تقویم با انتخاب ماه

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#118]
با سلام و عرض ادب
 yyyy-MM  من دنبال روشی هستم بجای اینکه کاربر روز را  انتخاب کرد و تقویم بسته شد زمانی که فرمت رو بصورت  انتخاب کردیم  و ماه مورد نظر را انتخاب کرد تقویم بسته شود.ممنون

**Comment by Mds92** [comment]
سلام
برای این کار بهتر است از دیت پیکر استفاده نکنید و به جاش از دوتا کمبو باکس سال  و ماه استفاده کنید
این دیت پیکر این قابلیت رو نداره
