### ISSUE TITLE
مشکل الاینمنت

### ISSUE THREAD

**Issue by nimamsv** [Mds92/MD.BootstrapPersianDateTimePicker#119]
من یه مشکلی دارم با الاینمنت. زمانیکه صفحه در حالت چپ به راست قرار داره مشکلی نداره اما رمانیکه صفحه راست به چپ میشه دیت پیکر سمت راست قرار میگیره و کلا نصفش از صفحه بیرونه 
ممنون میشم منو راهنمایی کنید

**Comment by nimamsv** [comment]
من با دیباگر بررسی کردم متوجه شدم زمانی که پاپ اور ایجاد میشه دقیقا زیر تک تکست باک ایجاد نمیشه میبره اخرین قسمت بادی تگ رو درست میکنه

**Comment by Mds92** [comment]
> من با دیباگر بررسی کردم متوجه شدم زمانی که پاپ اور ایجاد میشه دقیقا زیر تک تکست باک ایجاد نمیشه میبره اخرین قسمت بادی تگ رو درست میکنه

این رفتار پاپ اور بوت استرپ هست
ببینید مشکلی که میگید مشکل شما با پاپ اور بوت استرپ هست و پلاگین موجود کاری در این زمینه نمیکنه
شاید با آپشن placement
بتونید مشکلتون رو حل کنید

https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by nimamsv** [comment]
من این مشکل رو الان با این کد روی سی اس اس حل کردم اما محبورم کل پاپ اور رو بدم . اما میخوام تنها اون ای دی پاپ اور تغییر کنه با بوت استرپ ای دی رو گرفتم اما نمیدونم چطور میشه سی اس اس اعمال کرد. یه نکته دیگه ایم هم هست توی تمپلیت هم میشه این کار رو کرد اما مشکلی که بوجود میاد این هستش که بار اول اعمال میشه و زمانیکه برای بار دوم باز میشه دیگه تمپلیت رو ایجاد نمیکه

in code moshkel rtlcss nodejs ro tooye picker shoma hal mikone:
`    template: '<div class="popover" role="tooltip" style="right: unset;"><div class="arrow"></div><h3 class="popover-header" data-name="Md-DateTimePicker-Title"></h3><div class="popover-body" data-name="Md-DateTimePicker-PopoverContent"></div></div>'`
va in code ham age tooye css ezafe beshe hamun kar ro mikone:
```
.popover {
  /*rtl:ignore*/
  right: unset !important;
}
```

**Comment by vahidalvandi** [comment]
دقیقا زدی به خال
