### ISSUE TITLE
popover does not hide when target does not exists anymore

### ISSUE THREAD

**Issue by mahyarff** [Mds92/MD.BootstrapPersianDateTimePicker#12]
Hi

Thanks for your great plugin :+1: 

I have an inline form for editing grid row, which one of its controls is MdPersianDateTimePicker (**target**)
there's a situation when user clicks on target and datetimepicker popover pops up, and then user cancels the form (clicks on form cancel button), the popover does not hide.
I think this is happening because of **target** element does not exists anymore after that inline form has been removed from body, and what i understood from MD.BootstrapPersianDateTimePicker.js source code, the popover will be hidden based on found **target**

What can I do to fix this issue?

Regards
Mahyar

**Comment by Mds92** [comment]
It is a Bootstrap's popover behavior.
So, you have to hide popover manually, before the target removing.
```
$('#targetId').popover('show')
```

**Comment by mahyarff** [comment]
Thanks for your workaround, it helped

I think as alternate way you can give each calendar popup an idendity or classname, and then in method **hidePopover** use that id or classname to hide specific popup. this way even if target element is lost, we can handle popovers.

besides I have a suggestion, of course if you had free time:
- please add numeric (+/-) increment arrows to hour/minute/second textboxes

Best Regards
Mahyar

**Comment by Mds92** [comment]
Your-welcome
Your suggestion is good and I add this feature as soon as possible.
