### ISSUE TITLE
enableTimePicker مشکل با

### ISSUE THREAD

**Issue by nimamsv** [Mds92/MD.BootstrapPersianDateTimePicker#120]
با اینکه اتریبیوت enableTimePicker رو فالس میکنم اما همچنان تایم نمایش داده میشه
آیا راهی برای این هست؟

**Comment by Mds92** [comment]
دقت شود با اتریبیوت نمیتونید کار کنید و باید با جی کوئری مقدار ست نمائید

**Comment by nimamsv** [comment]
اخه ورژن ۱.۷ این قابلیت رو داشت. فقط لطف کنید بفرمایید توی جی کوری چه پارامتری رو باید ست کنم که این قابلیت بوجود بیاد؟

**Comment by Mds92** [comment]
در صفحه اول مطالعه نمائید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by nimamsv** [comment]
توی توضیحات نوشتین اگه enableTimePicker فالس بشه نمایش داده نمیشه

**Comment by nimamsv** [comment]
من مشکل رو با جی کوری و تغییر توی تمپلیت حل کردم
