### ISSUE TITLE
تفاوتtargetTextSelector و targetDateSelector 

### ISSUE THREAD

**Issue by nimamsv** [Mds92/MD.BootstrapPersianDateTimePicker#121]
تفاوت این دو اپشن چیه؟ ممنونم میشم توضیح بدین

**Comment by Mds92** [comment]
targetTextSelector:
المانی که متن تاریخ انتخاب شده در آن قرار میگیرد
برای نمایش

targetDateSelector:
المانی که تاریخ انتخاب شده در فرمت قابل پارس برای زبان های برنامه نویسی در آن قرار میگیرد
برای ارسال به سرور

**Comment by nimamsv** [comment]
ممنون بابت توضیحات شما. واقعا خیلی زیبا و بی نقص طراحی کردین میخواستم تبریک هم عرض کنم خدمت شما بابت این طراحی بنده شخصا لذت بردم.

**Comment by Mds92** [comment]
تشکر از شما
خوشحال میشم مورد استفاده واقع شده باشه
