### ISSUE TITLE
تبدیل تاریخ شمسی به timestamp

### ISSUE THREAD

**Issue by irandoct** [Mds92/MD.BootstrapPersianDateTimePicker#122]
با سلام 
من با استفاده از bootstarp datepiker تاریخ هجری شمسی را به صورت یک متغییر به یک فایل php ارسال می کنم . قصد دارم در فایل php تاریخ را به میلادی تبدیل کنم 
چطوری ؟

**Comment by Mds92** [comment]
با سلام
دقت کنید که این پلاگین تنظیمی دارد که تاریخ میلادی انتخاب شده را در المانی که شما گفته اید قرار میدهد، بنابراین نیاز نیست تا تاریخ شمسی را سمت سرور ارسال کنید، تاریخ میلادی را ارسال نمائید.
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options
```
targetDateSelector
```
لطفا فایل 
Readme
را با دقت مطالعه نمایید
