### ISSUE TITLE
غیر فعال کردن روزهای پنجشنبه و جمعه روی تقویم

### ISSUE THREAD

**Issue by irandoct** [Mds92/MD.BootstrapPersianDateTimePicker#123]
با سلام
چطوری می شود کلیه روزهای پنجشنبه و جمعه را روی تقویم غیر فعال کرد ... موقع انتخاب تاریخ این روزها غیر فعال شود ؟
ممنون

**Comment by Mds92** [comment]
با سلام
الان این امکان به شکل زیر فراهم است
باید تاریخ های میلادی روزهای مد نظر را در پارامتر 
disabledDates
قرار دهید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

اما با توجه به اینکه موضوع ممکن هست استفاده کننده های بیشتری داشته باشد، ممکن هست این امکان را اضافه کنم تا روز های خاصی از هفته غیر فعال شوند

**Comment by Mds92** [comment]
لطفا تا آخر امروز صبر کنید شاید این امکان در ورژن جدید قرار بدم

**Comment by irandoct** [comment]
ممنونم... منتظر می مونم

**Comment by Mds92** [comment]
انجام شد
الان با پارامتر 
disabledDays
که آرایه ای از ایندکس های روزهای هفته هست میتونید روز هایی رو در هفته کاملا غیرفعال و غیر قابل کلیک کنید

با تشکر

**Comment by irandoct** [comment]
شماره روز را بدیم مثلا 6,7 ??

**Comment by Mds92** [comment]
ایندکس هست
از 0 تا 6
