### ISSUE TITLE
غیر فعال شدن تایم

### ISSUE THREAD

**Issue by nimamsv** [Mds92/MD.BootstrapPersianDateTimePicker#124]
زمانیکه پیکر روی یه پاپ اور دیگه باز میشه دیگه نمیشه تایم رو تغییر داد قابل کلیک نیست میشه لطفا رهنمایی کنید؟

**Comment by Mds92** [comment]
متوجه مشکل نمیشم
یعنی یه پاپ اور دارید که این دیت پیکر توی اون باز میشه !!!
اگر اینطور هست، بنظرم کار جالبی نیست و نوع نمایش را تغییر دهید

**Comment by nimamsv** [comment]
نه اون از جنس پاپ اور نیست  زمانیکه فیلد توی اون باشه دیت پیکر باز میشه اما زمان رو نمیشه تغییر داد

**Comment by Mds92** [comment]
ابزاری که استفاده میکنید چیست؟
ببینید در مورد این گونه مشکلات باید خودتون مشکل رو حل کنید
چون ممکن هست هر کدام از استفاده کنندگان از ابزار خاصی استفاده کنن و نمیشه پلاگین رو برای همه درست کرد
بنظرم باید مشکل از css 
باشد
