### ISSUE TITLE
مشکل بهم ریختن تاریخ انتخابی با تنظیم زمان

### ISSUE THREAD

**Issue by majidlx67** [Mds92/MD.BootstrapPersianDateTimePicker#125]
هنگامی که زمان را تغییر می دهیم تاریخ انتخاب شده نادیده گرفته شده و تاریخ امروز در نظر گرفته می شود
همچنین اگر بعد از تنظیم زمان تاریخ را انتخاب کنیم زمان تنطیم شده به هم می ریزد.

**Comment by Mds92** [comment]
لطفا از آخرین ورژن استفاده نمائید
آیا در فایل دمو هم این مشکل را مشاهده میکنید؟

**Comment by majidlx67** [comment]
من از آخرین نسخه استفاده کردم. توی فایل دمو حالتی که من استفاده کردم وجود نداره. ولی انگار مشکل مربوط به زمانیه که به صورت inline استفاده می شه این مشکل به وجود میاد
من یه فیلم از مشکل تهیه کردم ضمیمه می کنم.
[Rec 0005.zip](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3194792/Rec.0005.zip)

**Comment by Mds92** [comment]
فیلم رو دیدم، بررسی میکنم

**Comment by Mds92** [comment]
مشکلی رو مرتفع کردم
لطفا ورژن جدید را دریافت و بررسی نمائید
با تشکر

**Comment by majidlx67** [comment]
مشکل برطرف شده اما یه مشکل جدید ایجاد شده
در حالتی که دو تا تقویم توی صفحه وجود داره انتخاب تاریخ توی یه تقویم تقویم دیگه رو از بین می بره
فیلم رو ضمیمه کردم
[Rec 0007.zip](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3206274/Rec.0007.zip)

**Comment by Mds92** [comment]
شما از دو تا تقویم InLine
در صفحه استفاده میکنید؟

**Comment by majidlx67** [comment]
بله. برای یه فرم گزارش گیری تاریخ و ساعت شروع و پایان. خواستم از رنج استفاده کنم اما قابلیت انتخاب ساعت نداشت.

**Comment by Mds92** [comment]
بررسی میکنم و اطلاع میدم
تشکر بابت گزارش باگ

**Comment by Mds92** [comment]
لطفا ورژن جدید را دریافت و بررسی نمائید
