### ISSUE TITLE
destroy method

### ISSUE THREAD

**Issue by nimamsv** [Mds92/MD.BootstrapPersianDateTimePicker#126]
پیشنهاد میکنم متد دستروی هم بهش اضافه کنید

**Comment by Mds92** [comment]
تشکر از پیشنهاد شما
الان غیرفعال کردن وجود داره

**Comment by nimamsv** [comment]
بله غیر فعال وجود داره اما دستروی وجود نداره

**Comment by Mds92** [comment]
لطفا ورژن جدید را دریافت نمائید
توضیحات destroy
را در فایل readme
مشاهده نمائید

**Comment by alimo2** [comment]
متود destroy
در آخرین نسخه وجود نداره؟
در readme
که نیست
