### ISSUE TITLE
bug in toDate and fromDate propoerty in version 3.4.3

### ISSUE THREAD

**Issue by mortezafs** [Mds92/MD.BootstrapPersianDateTimePicker#127]
hi.
In your new version we have a problem with 2 important properties (toDate and fromDate).
Datepicker popup will not shown days or other elements, when we setting this properties with groupId property.
Please check this problem.

a simple sample

        $('#activation_date').MdPersianDateTimePicker({ 
          targetTextSelector: '#activation_date',
          enableTimePicker: true,
          dateFormat: 'yyyy-MM-dd HH:mm:ss',
          textFormat: 'yyyy-MM-dd HH:mm:ss',
          groupId: 'activationRange'
        });
        
        $('#expire_date').MdPersianDateTimePicker({ 
          targetTextSelector: '#expire_date',
          enableTimePicker: true,
          dateFormat: 'yyyy-MM-dd HH:mm:ss',
          textFormat: 'yyyy-MM-dd HH:mm:ss',
          groupId: 'activationRange',
          fromDate: true
        });

Regards

**Comment by Mds92** [comment]
Please see sample file in source code.
I could see a bug in INLINE mode

**Comment by Mds92** [comment]
Please check new version

**Comment by mortezafs** [comment]
Thank you.
Bug fixed and problem solved.

Also, our example had a mistake and the true example is:

        $('#activation_date').MdPersianDateTimePicker({ 
            targetTextSelector: '#activation_date',
            fromDate: true,
            enableTimePicker: true,
            groupId: 'activationRange',
            dateFormat: 'yyyy-MM-dd HH:mm:ss',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
        });
        
        $('#expire_date').MdPersianDateTimePicker({ 
            targetTextSelector: '#expire_date',
            toDate: true,
            groupId: 'activationRange',
            enableTimePicker: true,
            dateFormat: 'yyyy-MM-dd HH:mm:ss',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
        });
