### ISSUE TITLE
مشکل در مخفی شدن

### ISSUE THREAD

**Issue by RezaAVS** [Mds92/MD.BootstrapPersianDateTimePicker#128]
سلام
زمانی که روی 
target
دوبار کلیک کنی یه popup کوچک نمایش می دهد
![Untitled](https://user-images.githubusercontent.com/51018682/58760268-ed7d5980-854a-11e9-84f8-f9ac72211003.png)

**Comment by Mds92** [comment]
سلام
من مشکلی را که شرح دادید ندیدم !
لطفا با دیدن کنسول مرورگر مطمئن شوید که خطایی ندارید

**Comment by RezaAVS** [comment]
در کنسول هیچ خطایی نداره
![image](https://user-images.githubusercontent.com/51018682/58775127-4e537300-85d9-11e9-8406-e601eb6d4d80.png)

**Comment by maedekaboli** [comment]
من هم این مشکل رو دارم و دلیلش مشخص نیست

**Comment by Mds92** [comment]
لطفا با مرورگرهای مختلف امتحان کنید

**Comment by RezaAVS** [comment]
آخرین نسخه هم مشکل دارد و در مرورگرهای کروم ، فایرفاکس، و نسخه کرومیوم هم تست کردم و این مشکل وجود دارد

**Comment by RezaAVS** [comment]
من یه پاپ آپ درست کردم و مشکل رو به این شکل حل کردم

 $(function () {
       $(document).on(clickEvent, '#js-userarea', function () {
        if ($('.js-userareapopover').length === 1) {
            hideUserAreaPopover();
            return;
        }

        var $self = $(this);
        $.get($self.data('url'), function (response) {
            $self.popover({
                title: ' ',
                content: '',
                container: 'body',
                trigger: 'manual',
                placement: 'bottom',
                template: response,
                sanitize: false,
                html: true
            }).popover('show');
        });
        return;
    });

    $(document).click(function (e) {
        var $userArea = $('#js-userarea');
        if (!$userArea.is(e.target) && $userArea.has(e.target).length === 0)
            hideUserAreaPopover();
    });

    getShoppingCartCount();
});

function hideUserAreaPopover() {
    $('.js-userareapopover').closest('.popover').popover('hide');
}
