### ISSUE TITLE
date format and multiselect date

### ISSUE THREAD

**Issue by vahid-jml** [Mds92/MD.BootstrapPersianDateTimePicker#13]
hi
how can i set date format like 1395.10.3. and is there an option to multiselect date from different months?

**Comment by Mds92** [comment]
Hello,
In current version - 1.7.3.4, you can't set format in another string. Maybe in next version.
> and is there an option to multiselect date from different months?
What do you mean? I couldn't understand you.
If you mean, select multi dates from a date picker, No, you can't.

**Comment by vahid-jml** [comment]
لطفا اگه امکانش هست یکم راهنمایی کنید تا بتونم خودم امکان تنظیم کردن فرمت را اضافه کنم

**Comment by Mds92** [comment]
شما میتونید عوض کنید فرمت رو به صورت دستی و از داخل سورس
خط 220 سورس رو ببینید
اما اینکه این امکان رو اضافه کنید تا فرمت از کاربر بگیره، باید کد رو بخونید
کار خیلی ساده ای نیست

**Comment by Mds92** [comment]
See new Version
