### ISSUE TITLE
کار نکردن تایم پیکر

### ISSUE THREAD

**Issue by rahnama7m** [Mds92/MD.BootstrapPersianDateTimePicker#130]
سلام. عرض ادب. 
من نصب کردم پکیج رو با npm. همچنین کدها رو به html ام اضافه کردم ولی کار نمیکنه و این خطا را در بروزگر میگیرم: 
with-tehran-function-1:387 Uncaught TypeError: $(...).MdPersianDateTimePicker is not a function
(anonymous) @ with-tehran-function-1:387

**Comment by Mds92** [comment]
سلام
به فایل دمو نگاه کنید و مطابق آن انجام دهید
خطای زیر باید از کدهای دیگری باشد
```
with-tehran-function-1:387 Uncaught TypeError:
```

**Comment by rahnama7m** [comment]
آقا محمد من طبق فایل دمو رفتم جلو. حتی برای اطمینان از کدهای دمو که توی سورس html هست استفاده کردم. حدسم این هست که فایلهایی که باید ایمپورت کنم اشتباه بوده باشه. دقیقا چه فایلهایی باید ایمپورت بشند ؟ من همون هایی که گفته بودید رو ایمپورت کردم ولی انگار کافی نیست.

**Comment by kamalrahimi** [comment]
hi dear @Mds92 . thanks for this nice plugin first of all. but time picker inputs not work on modals. they are not editable.

**Comment by Mds92** [comment]
Bootstrap 4+ Popover has an issue with modal if you want to use input into them: https://github.com/twbs/bootstrap/issues/22249

You have to remove `tabindex="-1"` attr from modal.
I added new sample in source
