### ISSUE TITLE
مشکل نمایش در بوت استرپ راست چین

### ISSUE THREAD

**Issue by ghasem110deh** [Mds92/MD.BootstrapPersianDateTimePicker#131]
سلام و تشکر
دو تا مشکل برای من بوجود اومده ...
اول اینکه من از بوت استرپ راست چین استفاده می کنم و بعد از کلیک روی دکمه انتخاب چیزی نمایش داده نمیشه
و دوم اینکه الان از الان از لینک های رفرنس داره جی کوئری و ... رو میخونه من پروژه ام تحت شبمه هست و به اینترنت دسترسی نداره؛ چند بار فایل های جی کوئری و مابقی رفرنس ها رو گرفتم و به صفحه اضافه کردم ولی کلا به هم میریخت!
ممنون میشم راهنمایی کنید

**Comment by Mds92** [comment]
سلام
در مورد راست چین، این کتابخانه با استاندارد خود بوت استرپ نوشته شده است، برای سازگاری آن با کتابخانه های دیگر خودتان باید فایل های css 
را بررسی و ویرایش نمائید.
در مورد مشکل دوم نمیدونم علت این مشکل شما چی هست
فایل دمو در سورس نیز دقیقا همین کار شما را انجام میدهد و مشکلی نیست
