### ISSUE TITLE
مقدار نمایشی شمسی و مقدار value میلادی

### ISSUE THREAD

**Issue by mahdisky** [Mds92/MD.BootstrapPersianDateTimePicker#132]
ظاهرا در حال حاظر برای یک input مقدار text و value  یا شمسی یا میلادی قرار میگیره.
چجوری میشه برای یک input مقدار نمایشی (تکس) شمسی باشه و مقدار value میلادی؟

**Comment by Mds92** [comment]
فایل readme
را مطالعه نمایید و یا فایل دمو را مشاهده نمائید

**Comment by mahdisky** [comment]
مطالعه کردم قبلا این مورد رو توش ندیدم
من دوباره توضیحش میدم
شما یک تکس باکس داری
وقتی رووش کلیک میکنی تقویم باز میشه
وقتی روی رو انتخاب میکنی مقدار شمسیش توی تکس باکس میریزه 
و مقدار شمسیش توی ولیو همون تکس باکس
(تا اینجا خب درست)
اما-->
حالا من میخوام
مقدار شمسیش توی تکس باکس بریزه 
و مقدار میلادیش توی ولیو همون تکس باکس (اینو ندیدم داشته باشه)

**Comment by Mds92** [comment]
> وقتی روی رو انتخاب میکنی مقدار شمسیش توی تکس باکس میریزه
> و مقدار شمسیش توی ولیو همون تکس باکس

اینو متوجه نمیشم، مقدار شمسی در یک تکس باکس بزار و میلادی را در یک هیدن فیلد قرار بده و در سرور ازش استفاده کن

**Comment by mahdisky** [comment]
بله میدونم همین کار رو میکنم
به عنوان پیشنهاد میگم
چرا هیدن رو حذف نمیکنی و با همون یک تکس باکس کار نمیکنی که مقدار شمسی توی تکس (نمایشی) ذخیره بشه و قسمت میلادی توی ولیو تکس باکس
که نیاز نباشه هیدن تعریف بشه و راحت تر میشه

**Comment by Mds92** [comment]
ممنون میشم یه نمونه پر شده HTML
اینجا بزارید ببینم منظورتون دقیقا چی هست؟

**Comment by mbasirati** [comment]
@mahdisky خب اینپوت اچ تی ام الی، تکستش همون ولیوش هست. دوتا چیز متفاوت نیست که
