### ISSUE TITLE
مشکل santizeFn  برای datePicker در angular

### ISSUE THREAD

**Issue by alirezabahary** [Mds92/MD.BootstrapPersianDateTimePicker#133]
سلام . 
من موقع استفاده از
  datepicker 
 در انگولار ۸ با خطای
  santizeFn  
مواجح میشم 

 bootstrap version 4.3.1
jquery: 3.4.1

 ERROR Error: TOOLTIP: Option "sanitizeFn" provided type "window" but expected type "(null|function)".
    at Object.typeCheckConfig (bootstrap.bundle.min.js:6)
    at i.t._getConfig (bootstrap.bundle.min.js:6)
    at i (bootstrap.bundle.min.js:6)
    at new i (bootstrap.bundle.min.js:6)
    at HTMLInputElement.<anonymous> (bootstrap.bundle.min.js:6)
    at Function.each (jquery.min.js:2)
    at k.fn.init.each (jquery.min.js:2)
    at k.fn.init.i._jQueryInterface [as popover] (bootstrap.bundle.min.js:6)
    at HTMLInputElement.<anonymous> (jquery.md.bootstrap.datetimepicker.js:1968)
    at Function.each (jquery.min.js:2)

**Comment by Mds92** [comment]
سلام
این کتابخانه برای استفاده در انگولار نوشته نشده است.
برای این کار باید تغییراتی در کتابخانه بدهید

**Comment by alirezabahary** [comment]
یعنی 
fork 
بشه ؟؟؟
کدوم قسمت باید عوض بشه؟؟؟
نسخه ای که برای بوت استرپ ۳ بود تو انگولار جواب میداد

**Comment by alirezabahary** [comment]
mds-angular-datetime-picker-package
 میشه این نسخه رو استفاده کرد؟؟؟

**Comment by Mds92** [comment]
فکر نمیکنم بتونید از اون ورژن استفاده نمائید
اون ورژن نیازمند بررسی دوباره است

**Comment by alirezabahary** [comment]
ممنون 
فکر کنم بشه با این mds-angular-datetime-picker-package
 کنار امد . 
فعلا برنامه ای واسه گسترش این نسخه ندارید .

**Comment by reza3vi** [comment]
اگه امکانش هست این مشکل رو حل کنید

**Comment by reza3vi** [comment]
> اگه امکانش هست این مشکل رو حل کنید

با اجازه سورس رو دستکاری کردم مشکل برطرف شد
اگه امکان داره شما هم برطرف کنید

**Comment by alirezabahary** [comment]
> > اگه امکانش هست این مشکل رو حل کنید
> 
> با اجازه سورس رو دستکاری کردم مشکل برطرف شد
> اگه امکان داره شما هم برطرف کنید

سلام . نسخه ای که دستکاری کردید رو میشه برا من هم بفرستید ؟؟؟

**Comment by reza3vi** [comment]
> > > اگه امکانش هست این مشکل رو حل کنید
> > 
> > 
> > با اجازه سورس رو دستکاری کردم مشکل برطرف شد
> > اگه امکان داره شما هم برطرف کنید
> 
> سلام . نسخه ای که دستکاری کردید رو میشه برا من هم بفرستید ؟؟؟

ایمیل بفرست یا به تلگرامم پیام بده

@reza3vi
