### ISSUE TITLE
امکان نمایش سال بدون ماه و روز

### ISSUE THREAD

**Issue by irandoct** [Mds92/MD.BootstrapPersianDateTimePicker#134]
با سلام
ایا ممکن است با انتخاب تاریخ هجری فقط سال در فیلد نمایش یابد 
dateFormat: 'Y',

ممنون

**Comment by Mds92** [comment]
سلام
از پراپرتی dateFormat
استفاده کنید
راهنما
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#string-format

**Comment by irandoct** [comment]
در واقع باید مقدار textFormat: 'yyyy', ست شود ؟؟ درسته

**Comment by Mds92** [comment]
بله درست هست
