### ISSUE TITLE
مشکل با پلاگین jquery.validate.unobtrusive

### ISSUE THREAD

**Issue by MostafaEsmaeili** [Mds92/MD.BootstrapPersianDateTimePicker#135]
با سلام خدمت به شما
از این که این کتابخانه بسیار عالی رو با ما به اشتراک گذاشتید بسیار سپاسگذارم
هنگامی که روی اینپوت خاصی ولیدیشن میگذارم با خطا مواجه میشوم
از ولیدیشن های دات نت ام وی سی استفاده میکنم
خطا به این صورت است که تقویم باز می شود اما هیچ کدام از دکمه ها و انتخاب روز ها کار نمی کند
در صورت غیر فعال کردن ولیدشن روی فیلد تاریخ مورد نظر همه چی درست است
خطای زیر در کنسول مشاهده می شود.
![Capture](https://user-images.githubusercontent.com/4990106/59701171-39e2bd80-920a-11e9-8187-67c01d1ed2b3.PNG)

با بررسی هایی که کردم به فانکشن زیر رسیدم :
```
 function getPopoverDescriber($element) {
        // المانی را بر میگرداند که کاربر پلاگین را روی آن فعال کرده است
        var $popoverDescriber = $element.parents(mdDatePickerFlagSelector + ':first'); // inline
        // not inline
        if ($popoverDescriber.length <= 0) {
            $popoverDescriber = $element.parents(mdDatePickerPopoverSelector + ':first');
            $popoverDescriber = $('[aria-describedby="' + $popoverDescriber.attr('id') + '"]');
        }
        return $popoverDescriber;
    }

```
که نمیتواند المان پلاگین را برگرداند
ممنون میشم راهنمایی کنید چطور این مشکل را رفع کنم

**Comment by AliHaydari** [comment]
سلام
من این مشکل را به صورت زیر حل کردم

```
public class ViewModel
    {
        [HiddenInput]
        [Required(ErrorMessage = "(*)")]
        [Display(Name = "تاریخ")]
        public DateTimeOffset DateAssigned { get; set; }
    }
```

View.cshtml :
```
<div class="form-group row">
 <label asp-for="DateAssigned" class="col-md-3 col-form-label text-md-left"></label>
  <div class="col-md-9">
   <input asp-for="DateAssigned" />
    <div class="input-group">
     <div class="input-group-prepend">
      <span class="input-group-text cursor-pointer" id="date1">
       <i class="fa fa-calendar" aria-hidden="true"></i>
      </span>
     </div>
    <input type="text" id="inputDate1-text" class="form-control" placeholder="لطفا تاریخ را وارد کنید" aria-label="date1" aria-describedby="date1">
   </div>
  </div>
</div>
```
```
<script type="text/javascript">
    $('#date1').MdPersianDateTimePicker({
        targetTextSelector: '#inputDate1-text',
        targetDateSelector: '#DateAssigned'
    });
</script>
```

امیدوارم مفید باشه

**Comment by koohsaran** [comment]
با سلام
منم با این مشکل برخورد کردم و با تبدیل :
` $popoverDescriber = $('[aria-describedby="' + $popoverDescriber.attr('id') + '"]');`
 به :
 ` $popoverDescriber = $('[aria-describedby*="' + $popoverDescriber.attr('id') + '"]');`
 مشکل حل شد.
 مشکل اینجا بود که در زمان کلیک روی روز تقویم، jquery validation برای اون اینپوت میومد aria-describedby رو دستکاری میکرد و یه چیزایی بهش اضافه میکرد به همین خاطر پلاگین تقویم نمیتونست اینپوت رو پیدا کنه.
 با اضاقه کردن * بعد از aria-describedby، جی کوئری میره و دنبال اینپوتی میگرده که aria-describedby شامل $popoverDescriber.attr('id') باشه نه کاملاً مساوی با $popoverDescriber.attr('id')
