### ISSUE TITLE
بازشدن پلاگین با قرار گرفتن focus بر روی تارگت مورد نظر

### ISSUE THREAD

**Issue by amiryxe** [Mds92/MD.BootstrapPersianDateTimePicker#137]
<p dir="rtl">
لطفا در صورت امکان، انتخابگر زمان و تاریخ با وارد شدن focus به داخل المنت مربوطه باز شود.
<br>
به این شکل کاربر میتونه به راحتی با زدن کلید Tab متوجه پلاگین انتخابگر بشه.
<br>
ممنون بخاطر پلاگین فوق‌العادت
</p>

**Comment by Mds92** [comment]
این موضوع به خودتان و تنظیمات پلاگین مربوط می شود
trigger

https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by amiryxe** [comment]
<p dir="rtl">
بله البته با این آپشن میشه رویداد رو تغییر داد اما یه مشکل کوچیک هست و اونم اینه که اگر رویداد focus رو بذارم، با وارد شدن focus پلاگین باز میشه اما با خارج شدن focus پلاگین بسته نمیشه و اگر برای trigger دوتا رویداد focus و click رو بفرستم، یکم دچار مشکل میشه
</p>
