### ISSUE TITLE
مشکل با رویداد on()

### ISSUE THREAD

**Issue by mhnpc** [Mds92/MD.BootstrapPersianDateTimePicker#138]
سلام وقت بخیر
لطفاً کد زیر را تست بگیرید ولی روی المان مورد نظر کلیک می شود تقویم باز می شود بدون مشکل ولی وقتی مجدد روی المان کلیک می شود تقویم خود به خود باز و بسته می شود.

    $(document).on('click', 'span.contract_date', function () {
        $(this).MdPersianDateTimePicker({
            placement: 'bottom',
            trigger: 'click',
            enableTimePicker: false,
            targetDateSelector: 'input[name=contract_date_text]',
            targetTextSelector: 'input[name=contract_date]',
            groupId: '',
            toDate: false,
            fromDate: false,
            disableBeforeToday: false,
            dateFormat: 'yyyy/MM/dd',
            //textFormat: 'yyyy/MM/dd',
            isGregorian: false,
            englishNumber: false,
        });
    });

**Comment by Mds92** [comment]
سلام
کد زیر باید حذف شود
`$(document).on('click', 'span.contract_date', function () {`
شما با هر کلیک روی المانی خاص دوباره اومدید دیت پیکر را مقدار دهی کردید که غلط هست و باید فقط یکبار دیت پیکر ایجاد شود

**Comment by mhnpc** [comment]
بله درست هست ولی بنده توسط ایجکس اینپودهای فرم رو ظاهر میکنم برای همین مجبور که از متدد
on()
استفاده کنم.

**Comment by mhnpc** [comment]
پاسخی ندارید؟
لطفا بفرمایید برای دسترسی به تایم پیکر با فانکشن چطور اقدام کنم؟
