### ISSUE TITLE
تاریخ اکنون و responsive با bootstrap 4

### ISSUE THREAD

**Issue by nazaninhesari** [Mds92/MD.BootstrapPersianDateTimePicker#139]
سلام چطور میتونم تاریخ اکنون رو که کلیک میکند انتخاب بشه و در تاریخ بذاره؟ و مورد دوم وقتی زمان و ساعت رو فعال  میکنم رسپانسیو صفحه بهم میخوره چطور این مشکل رو برطرف کنم؟

**Comment by Mds92** [comment]
> سلام چطور میتونم تاریخ اکنون رو که کلیک میکند انتخاب بشه و در تاریخ بذاره؟

متوجه منظورتون نمیشم

> و مورد دوم وقتی زمان و ساعت رو فعال میکنم رسپانسیو صفحه بهم میخوره چطور این مشکل رو برطرف کنم

لطفا عکس ارسال نمائید، نباید مشکلی باشه

**Comment by hamedzare2** [comment]
سلام دوست عزیز برای من هم این مشکل وجود داشت


> > سلام چطور میتونم تاریخ اکنون رو که کلیک میکند انتخاب بشه و در تاریخ بذاره؟
> 
> متوجه منظورتون نمیشم
> 
> > و مورد دوم وقتی زمان و ساعت رو فعال میکنم رسپانسیو صفحه بهم میخوره چطور این مشکل رو برطرف کنم
> 
> لطفا عکس ارسال نمائید، نباید مشکلی باشه
