### ISSUE TITLE
رفع مشکل مخفی نشدن

### ISSUE THREAD

**Issue by rbsdotnet** [Mds92/MD.BootstrapPersianDateTimePicker#140]
سلام
وقتی دوبار بروی target کلیک میکنیم دوباره popover ظاهر می شود ولی بدون اطلاعات
این مشکل رو من برطرف کردم ممنون میشم در نسخه جدید اعمال کنید

[jquery.md.bootstrap.datetimepicker.txt](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3386087/jquery.md.bootstrap.datetimepicker.txt)

در این فایل متغییر showDatePicker رو اضافه کردم و چک کردم اگر نمایش داده شده برگشت انجام شود
در متد on

> .on(setting.trigger, function () {
                        if (showDatePicker === true) {
                            showDatePicker = false;
                            return;
                        }

**Comment by Mds92** [comment]
متغیر
showDatePicker 
کی فالس میشه؟
تو کد نبود جایی که فالس بشه !
آیا مشکل در فایل دمو قابل مشاهده است؟
من نتونستم مشکل را باز تولید کنم

**Comment by RezaAVS** [comment]
زمانی که برای بار دوم کلیک میشه به
false
تغییر میکنه
بله من از موزیلا استفاده میکنم و این مشکل هست
اما این مشکل در کروم به صورت پرش های پرتکرار هست
به نظرم باید بعد از نمایش در صورت کلیک بروی تارگت اگر popop باز هست از رویداد خارج شود
