### ISSUE TITLE
نحوه استفاده از تابع disabledDates

### ISSUE THREAD

**Issue by mhmsignin** [Mds92/MD.BootstrapPersianDateTimePicker#143]
با سلام و خسته نباشد
میشه یک مثال برای تابع disabledDates بزارین ؟
من تو تست مشکل دارم با این و disable نمیشه روزهایی که بهش دادم
با سپاس

`
    var days = [new Date(2019, 7, 14), new Date(2019, 7, 16), new Date(2019, 7, 18), new 
    Date(2019, 7, 19)];
        $('#dates').MdPersianDateTimePicker({
            inLine: true,
            disabledDates: days,
        });
`

**Comment by Mds92** [comment]
من دوباره با اطلاعات شما بررسی کردم
مشکلی نبود
مشکل چی هست دقیقا

**Comment by mhmsignin** [comment]
همون اسکریپتی که دیدین رو اجرا میکنم ، روزهای ارسالی غیرفعال نمیشه، همچنان سره حال و فعالن؟ :D

**Comment by Mds92** [comment]
با اطلاعات پست اول ارسالی توقع دارید کدام ماه ها غیر فعال بشن؟

**Comment by mhmsignin** [comment]
ماه رو نمیخوام غیرفعال کنم، روزهایی که تو آرایه فرستادم رو میخوام غیر فعال بشن

**Comment by mhmsignin** [comment]
جسارتن فرمت روزهایه تعطیل در آرایه رو تو جیت هاب اشتباه درج کردین ، بعد از آزمون و خطا این فرمت درست کار میکرد
[new Date('2019/7/18'), new Date('2019/7/20'), new Date('2019/7/21')]

**Comment by mhmsignin** [comment]
ولی برایه غیرفعال کردن همچنان کار نمیکنه

**Comment by Mds92** [comment]
جسارتا حتما میدونید که new Date(2019, 7, 14)
یعنی ماه August میلادی

**Comment by mhmsignin** [comment]
درسته، خوب؟

**Comment by mhmsignin** [comment]
من اشکالم کجاست دقیقا متوجه نشدم ..
الان من تونستم که روزهایه تعطیل رو با آرایه ارسال کنم و کار کرد.
اما نمیتونم همین کارو با روزهایه غیر فعال انجام بدم، آرایه رو میفرستم ولی روزها غیرفعال نمیشه
از اول توضیح دادم عذر میخوام، برا شفافیت بود :D

**Comment by Mds92** [comment]
برای تست دقیق تر تقویم را میلادی کنید
ببینید روز های مد نظر شما غیر فعال میشن یانه

**Comment by mhmsignin** [comment]
var days = [new Date(2019, 7, 18), new Date(2019, 7, 20), new Date(2019, 7, 21)];
            $('#dates').MdPersianDateTimePicker({
                isGregorian: true,
                inLine: true,
                textFormat: 'yyyy/MM/dd ',
                targetTextSelector: '#SelectedDay',
                disabledDates: days,
                //holiDays: days,
            });
کار نکرد ....

**Comment by mhmsignin** [comment]
اگه لطف کنی و یه تابعی به نام
selectedDays 
مثله روزهایه تعطیل با ورودیه آرایه تعریف کنی که عالی میشه و واقعن از 
kendo و بقیه پلاگین ها بهتر میشه
چون من برا پارس هم از پلاگینه شما استفاده میکنم و خیلی عالیه و کامل
این امکان به تقویم اضافه بشه رو دست نداره

**Comment by Mds92** [comment]
آیا در فایل های دمو هم مشکل عدم غیر فعال شدن روز ها وجود دارد
یه نمونه میتونید ارسال کنید؟
کد شما رو تست کردم مشکلی نداره

اینی که میگید کلی ابهامات داره:
selectedDays یعنی چند روز همزمان انتخاب شده اند؟
نحوه نمایش روزهای انتخابی چگونه است
چطور در targetSelector نمایش داده بشه
مقدار چطور ذخیره بشه ؟
...
...
...

**Comment by mhmsignin** [comment]
نه نمیخواد امکان چند انتخابی رو اضافه کنی (بعدن اگه دوست داشتی ) فعلن فقط مثله روزهایه تعطیل روزهایی که با آرایه فرستاده میشه رو مثلن با رنگه سبز نشون بده

**Comment by mhmsignin** [comment]
اینطوری زیاد لازم نیست چیزی رو تغییر بدی
--------------------------------------------
بعدن اگه خواستی میتونی امکان چند انتخابی رو اضافه کنی که در اون صورت میتونی با تعریف یه کلید و نگه داشتنه اون کلید
 و انتخابه روزها در تقویم همشون با هم سبز بشن و در یک اینپوت مثلن با کاما از هم جدا بشن 
--------------------
این روشیه که kendo در ورژن هایه جدید استفاده میکنه و اگه کلید ctrl رو نگه دای میتونی جند روز رو انتخاب کنی بصورت همزمان

**Comment by mhmsignin** [comment]
> آیا در فایل های دمو هم مشکل عدم غیر فعال شدن روز ها وجود دارد
یه نمونه میتونید ارسال کنید؟

-------------------------------------------------------------
بله الان تست کردم در فایله دمو هم مشکل داره

![Capture](https://user-images.githubusercontent.com/6012147/61181439-d9de0c00-a63b-11e9-8a29-d4b43e131870.PNG)

**Comment by Mds92** [comment]
باید ماه آگوست را ببینید
لطفا دیت تایم در جاوااسکریپت را با دقت بیشتری مطالعه کنید
https://www.w3schools.com/jsref/jsref_obj_date.asp

**Comment by mhmsignin** [comment]
دیت تایم جاوا اسکریپت رو هم تست کردم چون ماهش از 0 شروع میشه باید ماه رو 6 میذاشتم 
با این حال بازم کار نکرد

**Comment by Mds92** [comment]
> دیت تایم جاوا اسکریپت رو هم تست کردم چون ماهش از 0 شروع میشه باید ماه رو 6 میذاشتم

اینکه میگید دیت تایم جاوااسکریپت رو هم تست کردم متوجه نمیشم، مگه تا الان با جاوااسکریپت کار نمیکردید !
من بازم تست کردم مشکلی نیست و روزهایی که در disabledDates داده میشه
غیر فعال میشن
