### ISSUE TITLE
نمایش روزهای انتخاب شده

### ISSUE THREAD

**Issue by mhmsignin** [Mds92/MD.BootstrapPersianDateTimePicker#144]
اگه لطف بفرمایین و همانند تابع های disabledDates و روزهای تعطیل
بشه آرایه ای فرستاد و اون روزها رو بصورت سبز رنگ نشون بده کاره منو راه انداختی و کاره چندین بیمارستان راه میفته و خدایی ثواب میبری منم دعات میکنم داداش
خیلی گلی
سپاس

**Comment by Mds92** [comment]
:-)
این یه css
ساده هست که خودت میتونی تو فایل css
مربوطه به پلاگین درست کنی
ببین روز های غیر فعال چیا دارن همونو ویرایش کن

**Comment by mhmsignin** [comment]
آخه فقط رنگش مشکل نیست، میخوام بشه رویه روزایه فعال کلیک کرد ...

**Comment by mhmsignin** [comment]
سلام مجدد مهندس
دیروز عصبانی شدید و تیکت رو بستین،
ولی واقعا راهنماییت رو نیاز دارم عزیز
من یکبار دیگه نمونه کد رو میزارم شما تست کن، اگه ر.وزهایه غیرفعال ، کارکرد ، من میفهمم که اشکال از منه 

`<div id="dates" name="dates" class="col-md-4"></div>
<label id="SelectedDay" />
@*@Html.Partial("List")*@


@section Scripts
{
    <script type="text/javascript">

        $(document).ready(function () {
            $('.search').keypress(function (e) {
                if (e.keyCode == 13)
                    $('#searchBtn').click();
            });

            var days = [new Date(2019, 6, 18), new Date(2019, 6, 20), new Date(2019, 6, 22)];
            $('#dates').MdPersianDateTimePicker({
                //isGregorian: true,
                //englishNumber: true,
                inLine: true,
                textFormat: 'yyyy/MM/dd ',
                targetTextSelector: '#SelectedDay',
                disabledDays: days,
                //holiDays: days,
            });
        });
    </script>
}`

**Comment by mhmsignin** [comment]
روزهایه تعطیل درست کار میکنه فقط روزهایه غیرفعال مشکل دارم
ممنون میشم ازت

**Comment by Mds92** [comment]
سلام
ممنون میشم یه نمونه HTML
آماده کنی که توش خطا وجود داره
اونو اینجا بزار
من مشکلی باشه حتما درست میکنم
هدف من هم بهتر شدن این کتابخانه و استفاده خلق ا... است
تشکر از شما

**Comment by mhmsignin** [comment]
ممنونم ازت، فایله
 zip رو مشاهده بفرمایی

[MD.Calendar.zip](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3391078/MD.Calendar.zip)

**Comment by Mds92** [comment]
قبل از اینکه اینقدر وقت بزارید که خطا رو توضیح بدید ورژن نرم افزار را بررسی میکردید
ورژن فایل شما 3.1.8 هست که اصلا چنین ویژگی در آن نبوده
ورژن جدید رو بگیر درست هست
من با ورژن جدید بررسی کردم درست بود
کمی دقت باعث میشه زمان خودت و دیگران را به هدر ندی

**Comment by mhmsignin** [comment]
عذر خواهی میکنم
ورژنی که ناگت ارائه میئه 2.3.1 هست

**Comment by mhmsignin** [comment]
عزیز من آپدیت کردم و درست شد، سپاسگزارم
جسارتن یه خواهشی که دارم اینه که:
من میخوام روزهایی که غیرفعال میکنم امکان گرفتن تاریخش مثله بقیه روزا باشه، 
کجایه جاوا اسکریپت رو تغییر بدم که از انتخابه تاریخش جلوگیری نکنه؟

**Comment by Mds92** [comment]
پس چرا غیر فعال میکنی؟ !!!
بگو میخوای چیکار کنی راهنماییت کنم

**Comment by mhmsignin** [comment]
میخوام با استایل رنگ اونا رو سبز کنم
این روزها رو به عنوانه روزهایه انتخاب شده به کار ببرم نه غیر فعال
----------------------------------------------
اولین پاسخی که تو این تیکت به من دادید رو ببینید لطفا

**Comment by Mds92** [comment]
میشه یه ویژگی به نرم افزار اضافه کرد مثلا
specialDates = آرایه ای از تاریخ ها
که یه css
خاص روی اونا اعمال بشه
این روز های غیر فعال نیستن و  قابل انتخاب هستند
اینطوری هم یه ویژگی به نرم افزار اضافه میشه و هم شاید مشکل شما حل شه

**Comment by mhmsignin** [comment]
دقیقا همین منظورم بود
استفاده زیاد داره ، در سیستمهای حمل و نقل برایه تشخیص روزهایه فعال
در بیمارستانها برایه تشخیص روزهای ویزیت پزشک و الی آخر
خدایی این اضافه بشه عالی میشه

**Comment by Mds92** [comment]
لطفا آخرین ورژن را دریافت نمائید
و specialDates 
را بررسی نمائید

**Comment by mhmsignin** [comment]
سالاری برادر

**Comment by mhmsignin** [comment]
محمد جان ممنونتم ، خدا عوضه خیر بهت بده داداش

**Comment by mhmsignin** [comment]
این شده البته استایل رو دستکاری کردم
![Capture](https://user-images.githubusercontent.com/6012147/61213489-6f4fcd80-a71a-11e9-868e-e9afa938e907.PNG)

**Comment by mhmsignin** [comment]
برادر میشه تویه رویدادهایه ماهه قبلی و بعدی تابعی تعریف کرد؟
یعنی وقتی رویه ماهه قبل و یا ماهه بعد کلیک کرد، یه تابعی اجرا بشه؟ امکانش هست؟

**Comment by Mds92** [comment]
بله میشه
لطفا درخواست را در issue
جدید ثبت کنید

**Comment by mhmsignin** [comment]
چشم و سپاس
