### ISSUE TITLE
انتخاب روزهای تعطیل 

### ISSUE THREAD

**Issue by MiiisterBR** [Mds92/MD.BootstrapPersianDateTimePicker#146]
میخوام جمعه هم قابل انتخاب باشه نمیشه یه selectFriday هم داشه باشم که true کنیم و قابل انتخاب باشه
کلا دوتا آپشن دیگه هم موجود باشه
selectFriday :true
holiDay:true

**Comment by Mds92** [comment]
جمعه ها و تعطیلات قابل انتخاب هستند
مشکلی نیست

**Comment by MiiisterBR** [comment]
کدوم آپشن؟

**Comment by MiiisterBR** [comment]
برای روزهای جمعه دیدم حق با شماست بو ممنونم  برای  تعطیلات رسمی کدوم آپشن هستش

**Comment by Mds92** [comment]
با آپشن 
holiDays
میتونید برخی روزها را به عنوان تعطیل
علامت بزنید

**Comment by MiiisterBR** [comment]
اکی
یعنی تمامی تعطیلات رسمی رو باید خودم معرفی کنم درسته؟

**Comment by Mds92** [comment]
بله

**Comment by MiiisterBR** [comment]
سپاس فراوان
