### ISSUE TITLE
خطا در استفاده برای bootstrap>4

### ISSUE THREAD

**Issue by sara20189** [Mds92/MD.BootstrapPersianDateTimePicker#147]
سلام. وقت بخیر
من از Bootstrap v4.2.1 و jquery-3.3.1 استفاده می کنم
و حالا میخوام از تقویم فارسی طبق پروژه شما استفاده کنم
کدهای من به این صورته:

```
<head>
<link href="/Content/bootstrap.css" rel="stylesheet" type="text/css" />

<link href="/Content/MdBootstrapPersianDateTimePicker/jquery.md.bootstrap.datetimepicker.style.css" rel="stylesheet" />

<script src="/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>
   
</head>
<body>

<div class="row">
    <div class="col-md-1">
        @Html.LabelFor(model => model.Event_StartDateTime, new { @class = "control-label" })
    </div>

    <div class="col-md-3">
        @Html.TextBoxFor(model => model.Event_StartDateTime, new { @class = "form-control text-center datetimepicker", lang = "en"  })
    </div>

    <div class="col-md-2">
        @Html.ValidationMessageFor(model => model.Event_StartDateTime)
    </div>
</div>
</body>
</html>
  
    <script src="/Scripts/umd/popper.min.js" type="text/javascript"></script>

    <script src="/Scripts/bootstrap.min.js" type="text/javascript"></script>

    <script src="/Scripts/MdBootstrapPersianDateTimePicker/jquery.md.bootstrap.datetimepicker.js"></script>


<script>
$('#Event_StartDateTime').MdPersianDateTimePicker({
    targetTextSelector: '#Event_StartDateTime',
    selectedDate: new Date('2018/9/30'),
    isGregorian: false
});
    </script>
```
وقتی صفحه لود میشه خطای زیر رو دارم:

**$(...).MdPersianDateTimePicker is not a function**
روی 

```
$('#Event_StartDateTime').MdPersianDateTimePicker({
    targetTextSelector: '#Event_StartDateTime',
    selectedDate: new Date('2018/9/30'),
    isGregorian: false
});
```

لطفا راهنمایی بفرمایید.
یه موضوع دیگه اینکه تو متن گفتن از نیوگت آخرین ورژن md.bootstrappersiandatetimepicker رو نصب کنیم که ورژن 2.3 بود. از طرفی فرموده بودین از js و css هایی که خودتون قرار داده بودین استفاده بشه

لطفا راهنمایی بفرمایید از کدوم js و css باید استفاده بشه؟
و اینکه من چرا نمی تونم استفاده کنم و خطا میده؟
در ضمن از mvc5 هم استفاده می کنم

**Comment by Mds92** [comment]
سلام
لود کتابخانه جی کوئری باید قبل از پلاگین باشد
یعنی 
`<script src="/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>`
باید قبل از پلاگین لود شود

**Comment by sara20189** [comment]
> 
> 
> سلام
> لود کتابخانه جی کوئری باید قبل از پلاگین باشد
> یعنی
> `<script src="/Scripts/jquery-3.3.1.min.js" type="text/javascript"></script>`
> باید قبل از پلاگین لود شود

بنده هم جی کوئری رو تو head گذاشتم
و قبل از همه js های دیگه
احتمالا مشکل از جای دیگس

**Comment by sara20189** [comment]
مشکل رو پیدا کردم. با
placeholder.js
تداخل داشت

**Comment by Avahita** [comment]
> مشکل رو پیدا کردم. با
> placeholder.js
> تداخل داشت

و چطوری این تداخل رو رفع کردین ؟ من هم همین مشکل رو دارم اضافه که می کنیم تمام رفرنس ها رو و تمام موارد رو مثل راهنما انجام دادم ولی همین مشکل رو دارم لطفا راهنمایی کنید
