### ISSUE TITLE
بسته شدن تقویم در صورت کلیک بر روی ماه یا سال

### ISSUE THREAD

**Issue by sara20189** [Mds92/MD.BootstrapPersianDateTimePicker#148]
سلام. وقت بخیر
با تشکر از کار بسیار خوبتون.
م یه مشلی دارم.
من برای اولین بار روی تکست باکس تاریخ کلیک می کردم و تقویم باز شد، تاریخی رو انتخابکردم و تقویم رو بستم.
خواستم تاریخ رو تغییر بدم، تقویم رو باز کزدم اما وقتی روی ماه یا سال یا آیکون های کناریش کلیک می کنم، تقویم بسته میشه

ممنون میشم راهنمایی بفرمایید مشکل از کجا می تونه باشه

**Comment by Mds92** [comment]
سلام
آیا چنین مشکلی در فایل sample
هم هست؟

**Comment by sara20189** [comment]
> 
> 
> سلام
> آیا چنین مشکلی در فایل sample
> هم هست؟

خیر

**Comment by Mds92** [comment]
پس احتمال زیاد مشکلی در کد خودتان هست
باز اگر از کدتان مطمئن هستید یه نمونه فایل نمونه که خطا توش وجود داره آماده کنید و اینجا بزارید تا باگ مشاهده و تصحیح شود

**Comment by sara20189** [comment]
مشکل رو پیدا کردم.
من میخواستم با کلیک روی تکست باکس ، تقویم باز بشه به همین خاطر کد زیر رو نوشته بودم.
````
$('#date1').MdPersianDateTimePicker({
targetTextSelector: '#date1',
dateFormat: 'yyyy-MM-dd',
isGregorian: false,
enableTimePicker: true
});
````
یه span
 مثل سمپل خودتون گذاشتم حل شد.
آیا راهی برای این مورد نیست؟

------------------------
یه سوال دیگه:
راهی وجود داره که لازم نباشه به ازاء هر تقویم یکبار دستور
$('#date1').MdPersianDateTimePicker({
رو بنویسم؟
مثلا به جای 
$('#date1').MdPersianDateTimePicker({
بنویسم
$('.datetime').MdPersianDateTimePicker({
ولی تو این حالت نمی دونم آیدی تکست باکس تقویم رو برای 
targetTextSelector
چطور باید نوشت
ممنون میشم راهنمایی بفرمایید

**Comment by sara20189** [comment]
من حدودا 100 فیلد تاریخ تو برنامم دارم.
عملا نمیشه برای هر صد فیلد تاریخ من دستور 
 $('#date1').MdPersianDateTimePicker({
 رو بنویسم. میخوام یه دستور کلی برای همشون بنویسم که با یه ویژگی مشترک مثلا کلاس مشترک بشه کار رو اناجم داد و دستور
 $('#date1').MdPersianDateTimePicker({
فقط یکبار نوشته بشه

**Comment by Mds92** [comment]
باید سی اس اس سلکتوری داشته باشید که با اون پلاگین جی کوئری رو ران کنید
این سلکتور باید مخصوص دیت پیکرهاتون باشه فقط
مثلا
`data-datepicker="true"`
و اینطوری پلاگین را روشون فعال کنید
```
$('[data-datepicker="true"]').MdPersianDateTimePicker();
```

**Comment by sara20189** [comment]
> 
> 
> باید سی اس اس سلکتوری داشته باشید که با اون پلاگین جی کوئری رو ران کنید
> این سلکتور باید مخصوص دیت پیکرهاتون باشه فقط
> مثلا
> `data-datepicker="true"`
> و اینطوری پلاگین را روشون فعال کنید
> 
> ```
> $('[data-datepicker="true"]').MdPersianDateTimePicker();
> ```
تو این حالت 
targetTextSelector
رو چزور مقداردهی باید کرد؟

**Comment by Mds92** [comment]
نمونه کد
```
var counter = 0;
$('[data-datepicker="true"]').each(function(){
  var $this = $(this);
  $this.MdPersianDateTimePicker({
     targetTextSelector: '[data-datepicker-counter="'+counter+'"]'
   });
  counter ++;
});
```
این سوالات مربوط به جی کوئری هست، لطفا در فاروم های جی کوئری مطرح نمائید

**Comment by sara20189** [comment]
چشم. سپاسگزارم
