### ISSUE TITLE
کانفلیکت jquery.md.bootstrap.datetimepicker.js با  jquery.validate.min.js و  jquery.validate.unobtrusive.min.js

### ISSUE THREAD

**Issue by sara20189** [Mds92/MD.BootstrapPersianDateTimePicker#149]
سلام.
من از کد razor زیر برای فیلد تاریخ استفاده می کنم
````
@Html.TextBoxFor(model => model.Event_StartDateTime, new { @class = "form-control text-center", @lang = "en", data_datetimepicker_counter = "0", data_datetimepicker = "true" })
````
که به صورت زیر تبدیل میشه در html:
````
<input class="form-control text-center valid" data-datetimepicker="true" data-datetimepicker-counter="0" data-val="true" data-val-required="*" id="Event_StartDateTime" name="Event_StartDateTime" type="text" value="" data-mdpersiandatetimepicker="" data-original-title="" title="" aria-invalid="false" aria-describedby="Event_StartDateTime-error" lang="en">
````
وقتی یکبار روی تکست باکس کلیک می کنم ، تقویم رو باز می کنه و تاریخ هم باز میشه. وقتی برای بار دوم کلیک می کنم تا تقویم باز شه و تاریخ رو عوض کنم، تقویم باز میشه اما وقتی روی روز جدید کلیک می کنم در تکست باکس، تاریخ رو قرار نمیده و در کنسول خطای زیر رو میده :

خطای setting is undefined در jquery.md.bootstrap.datetimepicker.js

**Comment by sara20189** [comment]
وقتی تبدیل به اچ تی ام ال میشه، مشکلش با قسمت زیره:
data-val="true" data-val-required="*"
وقتی حذفش کردم کار کرد

**Comment by sara20189** [comment]
ظاهرا کلا با اجباری شدن فیلد مشکل داره.
وقتی به صورت زیر هم می نویسم باز کار نمی کنه
````
<input type="text" class="form-control text-center" id="Event_StartDateTime" name="Event_StartDateTime" data-datetimepicker="true" data-datetimepicker-counter="0" lang="en" value="@Model.Event_StartDateTime" required/>
````

یه required اضافه کردم
اجباری بودن رو حذف می کنم کار می کنه

**Comment by sara20189** [comment]
یه جای دیگه هم همین خطا رو میده:
در .net mvc
اگر از regular expression
استفاده کنیم باز هم، خطای 

رو میده
وقتی به html 
تبدیل می کنه، به صورت زیر هست
````
<input class="form-control text-center input-validation-error" data-datepicker="true" data-datepicker-counter="0" data-val="true" data-val-regex="فرمت تاریخ صحیح نیست.مثال فرمت صحیح: 1391/05/01" data-val-regex-pattern="^\d{4}/\d{2}/\d{2}$" data-val-required="*" id="AdvanceMoney_Date" name="AdvanceMoney_Date" type="text" value="1398/05/03" data-mdpersiandatetimepicker="" data-original-title="" title="" aria-invalid="true" aria-describedby="AdvanceMoney_Date-error" lang="en">
````

**Comment by sara20189** [comment]
پیدا کردم مشکل از کجاست
jquery.md.bootstrap.datetimepicker.js
با دو جی اس زیر کانفلیکت داره
jquery.validate.min.js
jquery.validate.unobtrusive.min.js

زمانیکه هر دو فایل جی اس مربوط به ولیدیشن رو فراخوانی کنیم تقویم کار نمی کنه اما اگر یکی شونو غیرفعال کنیم، تقویم کار می کنه

**Comment by koohsaran** [comment]
با سلام
منم با این مشکل برخورد کردم و با تبدیل :
` $popoverDescriber = $('[aria-describedby="' + $popoverDescriber.attr('id') + '"]');`
 به :
 ` $popoverDescriber = $('[aria-describedby*="' + $popoverDescriber.attr('id') + '"]');`
 مشکل حل شد.
 مشکل اینجا بود که در زمان کلیک روی روز تقویم، jquery validation برای اون اینپوت میومد aria-describedby رو دستکاری میکرد و یه چیزایی بهش اضافه میکرد به همین خاطر پلاگین تقویم نمیتونست اینپوت رو پیدا کنه.
 با اضاقه کردن * بعد از aria-describedby، جی کوئری میره و دنبال اینپوتی میگرده که aria-describedby شامل $popoverDescriber.attr('id') باشه نه کاملاً مساوی با $popoverDescriber.attr('id')
