### ISSUE TITLE
نمایش چند روز در تقویم

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#151]
با سلام وخسته نباشی
من دنبال این ویژگی ها هستم حالا نمیدونم شما زحمتشو کشیدید وجود دارد یا خیر
1- انتخاب چند روز به طور همزمان. 
2- افزودن دیکشنری دلخواه (https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/issues/113)
با سپاس

**Comment by Mds92** [comment]
سلام
ویژگی های مورد نظر وجود ندارد

**Comment by amir3164** [comment]
ممنون ایا در اینده توسعه داده می شود؟

**Comment by Mds92** [comment]
در مورد انتخاب چندین روز خیر
اما در مورد استفاده از دیکشنری نمیدونم منظورت چی هست؟

**Comment by amir3164** [comment]
ممنون از پاسخگویی تون. درخواست این لینک مد نظر بود
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/issues/113

**Comment by Mds92** [comment]
این ویژگی مد نظرم هست، اما دنبال روشی هستم که بیشترین کاربرد را برای استفاده کنندگان داشته باشد

**Comment by amir3164** [comment]
انتخاب چند روز به طور همزمان ویژگی خوبه که من الان خودم درگیرشم هستم اگه بتونید پیاده سازی کنید که واقعا متشکرم.در غیر اینصورت اگه راهنمایی بفرمایید خودم پیاده سازیش کنم در روند کارم از شما کمک بگیرم.ممنون

**Comment by Mds92** [comment]
فعلا برای انتخاب چندین روز باید از چندین دیت پیکر یا یک دیت پیکر با چندین تنظمیات استفاده کنید

**Comment by amir3164** [comment]
با سلام دوباره
 مهندس تو خود ورژن بوت استرپ خاصیت 
multidate
داره  که در لینک زیر هست.
من کدهای شما رو نگاه کردم یه تنظیم 
multidate بهش اضافه کردم که اگر
 if (selectedDateNumber == currentDateNumber && setting.multidate) {}
بتونه تشخیص بده چند تا تاریخ رو انتخاب کنه 
مشکلی که هست td جاری رو میاد   $td.attr('data-selectedday', ''); اضافه میکند میخام روی تاریخ بعدی رو انتخاب کرد data-selectedday   تاریخ قبلی پاک نشه و رنگشم فرق کند.ممنون
https://stackoverflow.com/questions/25874375/multiple-dates-in-bootstrap-date-picker

**Comment by Mds92** [comment]
لینکی ک دادید یه پلاگین هست و برای شرکت بوت استرپ نیست

**Comment by amir3164** [comment]
کتابخونه های یکی هست   
این لینک مطالع بفرمایید 
https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#multidate
اگه لینک فوق مد نظر شما نبود اون لینکی که خودتون مطالعه کردید رو لطفا بزارید 
ممنون از شما که وقت میزارید.

**Comment by amir3164** [comment]
من این قسمت رو پیاده سازی کردم.
![image](https://user-images.githubusercontent.com/10501720/62365358-203ad280-b539-11e9-8e36-60453f0d08f2.png)
