### ISSUE TITLE
تعیین روز های تعطیل در یه تاریخ مشخص

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#152]
با سلام مجدد و خسته نباشید
من دبنال راهی هستم در یک بازه مثلا 1398/01/01 تا 1400/01/01
 بگم مثلا شنبه ها یا 5 نشبه ها تعطیل باشند.
چطوری  روزه های شنبه  یا 5شنبه رو برای تقویم  تشخیص بدم
سپاسگذارم

**Comment by Mds92** [comment]
سلام
میتونید از ویژگی
holiDays
استفاده کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by amir3164** [comment]
ممنون فرمت
holiDays  
 [new Date(), new Date(2017, 3, 2)]  اینطوری هست چون من میخام از سمت سرور پاس بدم این فرمت ساختنش کمی سخته .فرمت دیگری نداره ؟

**Comment by Mds92** [comment]
فرمتش استاندارد هست
برای ایجاد دیت در جاوااسکریپت از روش زیر هم میتونید استفاده کنید
```
new Date(Date.parse('2018-02-03 21:22:32'))
```

**Comment by amir3164** [comment]
new Date(Date.parse('2018-02-03 21:22:32')) این فرمت تست کردم کار نمیکنه مهندس
