### ISSUE TITLE
امکان ارسال روزهای شمسی به آرایه برای روزهای تعطیل یا روزهای ویژه

### ISSUE THREAD

**Issue by mhmsignin** [Mds92/MD.BootstrapPersianDateTimePicker#153]
سلام محمد جان
مزاحمه همیشگی هستم
آقا با عرض پوزش امکانش هست برای روزهای ویژه و تعطیل آرایه تاریخ شمسی ارسال کنیم ،
چون وقتی میخوام از اکشن آرایه ارسال کنم باید اول به میلادی تغییرشون بدم، یکی اینکه زمان بر هست و دوم اینکه تویه کست دقیق نیست و روزها رو درست کست نمیکنه.
اگه شمسی بفرستیم و دیگه تبدیل نکنیم عالی میشه
ممنونم ازت

**Comment by Mds92** [comment]
سلام
این یه ویژگی جدید هست که باید اضافه شود
در فرصت های بعد انشالا انجام میدم

**Comment by mhmsignin** [comment]
محمد جان خیلی سالاری
میدونم سرت شلوغه ... ولی زودتر ردیفش کنی دعات میکنم بخدا
این پلاگین رو پولی کنی، خودم ازت میخرم چون ارزش داره
