### ISSUE TITLE
  تعطیلات  قمری و شمسی

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#155]
سلام
مهندس برای تعطیلات  تاریخ های شمسی مخصوصا قمری چه پیشنهادی دارید.چطوری اینا رو بگیریم.
ممنون.

**Comment by Mds92** [comment]
سلام
باید در بک اند این تاریخ ها را به میلادی تبدیل و برای کلاینت ارسال کنید
بعدش میتونید تو این پلاگین ازش استفاده کنید
