### ISSUE TITLE
مشکل در isGregorian

### ISSUE THREAD

**Issue by smartmob98** [Mds92/MD.BootstrapPersianDateTimePicker#156]
سلام وقت بخیر 
کارتون حرف نداره و عالبه
فقط من یه مشکلی رو دیدم نمیدونم مشکل از کدای من  هستش یا کتابخونه ؟
با وجود این که من 
isGregorian
رو
false
زدم ولی وقتی تاریخی رو انتخاب میکنی و میخوای در اینپوت نشون داده بشه به صورت میلادی نشون میده نه فارسی

**Comment by Mds92** [comment]
سلام 
حدس من این هست که تارگت ها را اشتباه ست کرده اید
```
$('#id').MdPersianDateTimePicker({ 
  targetTextSelector: '#inputTextDate1', // برای نمایش
  targetDateSelector: '#inputHiddenDate1', // برای ذخیره تاریخ به میلادی
});
```
لطفا فایل readme
را با دقت بیشتری مطالعه کنید

**Comment by smartmob98** [comment]
بله کاملا درست فرمودین مشکلم حل شد
بازم ممنون از زحماتتون واقعا یه کار خوب و مطلوبی شده
