### ISSUE TITLE
فونت نمایشی

### ISSUE THREAD

**Issue by hosein1122** [Mds92/MD.BootstrapPersianDateTimePicker#159]
با سلام
من از این تقویم در سایتم استفاده کردم ولی فونت تقویم دیفالت سیستم عامل هست بنظرم 
در صورتی که بقیه قسمتهای سایت فونت درست رو نمایش میدهند.
میشه لطفا کمک کنین چیکار کنم؟
ممنون

**Comment by Mds92** [comment]
سلام
باید css
هاتون رو بررسی کنید
مشکل css
دارید

**Comment by hosein1122** [comment]
سلام
پس باید css رو چک کنم . ممنونم
از تقویم عالی که نوشتین تشکر میکنم
🙏🙏
