### ISSUE TITLE
تبدیل به تاریخ میلادی

### ISSUE THREAD

**Issue by PouriaParhami** [Mds92/MD.BootstrapPersianDateTimePicker#16]
سلام ، ممنون از کد بسیار خوبی که در اختیار قرار دادین، 
می خوام تاریخ برای نمایش و انتخاب به کاربر شمسی باشه اما زمانی که می خوام تاریخ به دیتا بیس بفرستم 
میلادی باشه  در کد های شما فانکشنی برای کانورت به میلادی دیدم چطور ازش استفاده کنم ؟
var hello = var hello = toGregorian(yy, mm, dd);
alert(hello.gy.toString() + " " + hello.gm.toString() + " " + hello.gd.toString());
همیشه مقدار متغییرهای رشته ای بعد از تبدیل به اینت با دستور پارس اینت ، نن می باشد و تبدیلی صورت نمیگیره

**Comment by Mds92** [comment]
سلام
برای این کار در دات نت مثالی میزنم
شما اطلاعات رو به همون شکل فارسی به سرور ارسال کنید
حالا سمت سرور با استفاده از کتابخانه زیر متن فارسی تاریخ رو پارس کنید و تبدیل به میلادی کنید، 
https://github.com/PouriaParhami/MD.PersianDateTime
برای زبان های دیگر خودتون باید یه پارسر بنویسید
اما اگر منظورتون تو همون جاوااسکریپت هست، فعلا راه کاری برای اون ندارم و این راه رو توصیه نمیکنم

**Comment by PouriaParhami** [comment]
سلام منظورم جاوا اسکریپت بود ، ممنونم

**Comment by PouriaParhami** [comment]
این کدی هست که برای تبدیل تاریخ به میلادی در جاوا اسکریپ زدم و درست کار می کرد 
 function getUserDate() {
        var dkDrSplitOb, dkdrY, dkDrM, dkDrD, dkDrRturnDate;

        //convert Numbers Arabic/Persian To English Numbers
        function parseArabic(str) {
            return Number(str.replace(/[٠١٢٣٤٥٦٧٨٩]/g, function (d) {
                return d.charCodeAt(0) - 1632;
            }).replace(/[۰۱۲۳۴۵۶۷۸۹]/g, function (d) {
                return d.charCodeAt(0) - 1776;
            }));
        }

        dkDrSplitOb = dkDrGetUserDate.value.split("/");
        for (var i = 0; i < dkDrSplitOb.length; i++) {
            dkdrY = dkDrSplitOb[0];
            dkDrM = dkDrSplitOb[1];
            dkDrD = dkDrSplitOb[2];
        }

        dkDrRturnDate = toGregorian(parseInt(parseArabic(dkdrY), 10), parseInt(parseArabic(dkDrM), 10), parseInt(parseArabic(dkDrD), 10));
        dkDrRturnDate = dkDrRturnDate.gy + "/" + dkDrRturnDate.gm + "/" + dkDrRturnDate.gd;
        return dkDrRturnDate;

    }
