### ISSUE TITLE
ساخت دوباره تقویم  در جی کویری

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#162]
با سلام
من میخام تقویم دوباره با تنظیمات جدید ساخته بشه در محیط جاوا اسکریپت.
راهی وجود دارد. ممنون

**Comment by Mds92** [comment]
سلام
متوجه منظورتون نمیشم
شاید منظورتون این هست که یه بار 
destroy
کنید و دوباره بسازید
اگر این هست از متد 
destroy
استفاده کنید و دوباره پلاگین را فراخوانی کنید

**Comment by amir3164** [comment]
ممنون.
من دوتا کارمیخام انجام بدم
1- ساخت دوباره تقویم با تنظیمات جدید
کهdestroy
 لطفا  فراخوانی این متد رو کامل بنویسید.
2- من میخام با یه تابع تعطیلات تقویم رو ست کنم  امدم
$('#date5').MdPersianDateTimePicker('setOption', 'holiDays', daysCreate)
از این استفاده کردم ولی کار نمی کنه.
سپاسگذارم

**Comment by Mds92** [comment]
در باره مشکل دوم لطفا آخرین ورژن را دریافت و تست نمائید
دقت کنید که ایندکس ماه های میلادی از 0 هست
