### ISSUE TITLE
غیرفعال کردن سالهای آتی

### ISSUE THREAD

**Issue by hamid-bhz** [Mds92/MD.BootstrapPersianDateTimePicker#163]
سلام دوست عزیز
من از تقویم برای انتخاب تاریخ تولد استفاده میکنم و میخوام بدونم امکانش هست که بتونم مثلا از سال 1400 به بعد رو غیر فعال کنم؟

**Comment by Mds92** [comment]
سلام
می تونید از 
disableAfterDate
استفاده نمائید
لطفا صفحه نخست یا همان
readme
با دقت بیشتری مطالعه شود
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options
