### ISSUE TITLE
مشکل در آپشن disableAfterDate و disableBeforeDate

### ISSUE THREAD

**Issue by babakjalilian** [Mds92/MD.BootstrapPersianDateTimePicker#164]
با سلام!
من بخاطر محدود کردن کاربر برای انتخاب تاریخ قبل از یک تاریخ مشخص شده باید از disableAfterDate استفاده کنم اما زمانی که تاریخ را به تقویم میدهم برای ماه های 1و2و8و9و10و11و12 در تعدادی از سال ها کل تقویم disable میشوداما در برخی از ماه ها درست کار میکند و در بعضی از سال ها(که حدس میزنم سال های کبیسه باشد برای مثال 2008و2012و2016)در تمام ماه ها درست کار میکند!
تاریخی که من در آن به مشکل برخوردم 2009/2/20 بوده و تاریخی که درست کار میکند 2008/2/20!!!
با تشکر

**Comment by Mds92** [comment]
ممنون میشم کدتون رو بنویسید
حتما میدونید که ایندکس ماه های میلادی از 0 هست

**Comment by babakjalilian** [comment]
بله این قضیه را لحاظ نمودم اما به طور کلی رفتار برنامه نباید با تغییر ماه تغییر کند و اینکه عرض کردم در تاریخ هایی که در ماه های ذکر شده باشد کل تاریخ ها و صفحات disable میشود چه تاریخ های قبل و چه بعد از تاریخ ورودی مد نظر!!

HTML

<app-input-date-picker formControlName="BirthDateM" [disableAfterDate]='date'></app-input-date-picker>

js

 date= new Date(2009, 2, 21);

این قطعه کد مربوط به datepicker هستش!
عذرخواهی میکنم چون کل کد طولانی هستش و dependency های زیادی داره کل کد رو نذاشتم فقط صرفا میخوام بدونین که درست ازش استفاده میکنم!!
اگر نیاز بود بگید که من کل کد رو بذارم!

**Comment by Mds92** [comment]
از کدتون بنظرم دارید با انگولار کار میکنید
من چیزی برای استفاده از این پلاگین در انگولار ننوشتم، از سورس برنامه مطمئن شید و اگر باگی هست بفرمایید تا درست کنم
اینی که میگید بعد از یه تاریخی غیر فعال میشه
اون تاریخ همونی نیست که در 
disableAfterDate
هست؟
