### ISSUE TITLE
کارنکردن دوبار کلیک

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#165]
سلام 
چرا من از این تابع استفاده میکنم 
    $(document).on('dblclick', mdDatePickerContainerSelector + ' [data-day]', function (event) {
                alert('test')
 });
کار نمیکند

**Comment by Mds92** [comment]
سلام
مشکل جی کوئری هست
من بنظرم سلکتور شما پیدا نمیشه
اینم در نظر داشته باشید که اونت
click
روی روز ها هندل شده

**Comment by amir3164** [comment]
بله درست چون روی 
click  هندل شده 
روی دوباره کلیک کار نمی کنه.

**Comment by amir3164** [comment]
مهندس روشی به نظرت میرسه
مشکل رو حل کنیم.عجیب گیر هستیم

**Comment by Mds92** [comment]
وقتی روی روز کلیک میکنه مقدار داخل  
targetTextSelector
عوض میشه
روی اون اونت 
change
بزار

**Comment by amir3164** [comment]
من میخام روی دوبار کلیک یه  مودال باز بشه.
چون روی کلیک کردن یسری کارهای دیگه انجام میدم.
میخام روی دوباره کلیک یه مودال باز بشه که  یه متی روی اون تاریخ بنویسه
 مثل دفترچه یاداشت برای اون روز.

**Comment by Mds92** [comment]
برای این کار بهتر است که کاربر تاریخ رو انتخاب کنه
بعدش دکمه کنار دیت پیکر باشه تا بزنه و مدال باز شه
چون کلیک روی روزها هندل شده است
البته شاید راهی داشته باشه اما من نمی دونم

**Comment by amir3164** [comment]
فکر خوبیه. فقط چطوری المنت که روی 
روز کلیک کرده رو بگیرم
  var $this = $(this),
یعنی روی اون دکمه که زدم بتونم تشخیص بدم کدوم 
روز کلیک شده چون 
setting = getSetting1($this),
لازم دارم  استفاده کنم

**Comment by Mds92** [comment]
المانی که روش کلیک شده پس از مخفی شدن تقویم از بین میره
برای چی اون المان رو میخوای ؟ باید با تاریخش کار کنی
از 
targetDateSelector
استفاده کن

**Comment by amir3164** [comment]
من اون المان رو لازم دارم تا بتونم وقتی براش یاداشت ثبت کردم شکل اون 
td
رو عوض کنم استایلشو که قابل  تشخیص باشه
 $td.addClass('calender-custome');

**Comment by Mds92** [comment]
این کار ساده ای نیست
بنظرم بهتر هست از 
specialDates
استفاده کنید

**Comment by amir3164** [comment]
ممنون مهندس.
دیگه مجبور شدم از کلیک راست استفاده کنم


> >    $(function() {
> >         $.contextMenu({
> >             selector: '.days td', 
> >            callback: function(key, options) {
> > 
> >                 var $this = $(this),
> >             disabled = $this.attr('disabled'),
> >             dateNumber = Number($this.attr('data-number')),
> >             setting = getSetting1($this),
> >             selectedDateJson = setting.selectedDate == undefined ? undefined : >>getDateTimeJson1(setting.selectedDate),
> >             selectedDateToShow = getClonedDate(setting.selectedDateToShow);
> >                 var content = $(this).text();
> >                 alert("You clicked on: " + dateNumber);
> >             },
> >             items: {
> >                 "custome": {name: ",ثبت یاداشت روزانه", icon: "calender"},
> >                 "quit": {name: "خروج", icon: function(){
> >                     return 'context-menu-icon context-menu-icon-quit';
> >                 }}
> 
>             }
>         });
>     });
