### ISSUE TITLE
انتخاب طول تاریخ با وجود روزهای غیرفعال

### ISSUE THREAD

**Issue by Misaghahmadi97** [Mds92/MD.BootstrapPersianDateTimePicker#168]
سلام
خسته نباشید
موقعی که rangeSelect فعال هست ، اگه روزهای غیرفعال داخل این رنج باشه ، بازم رنج تاریخ قابل انتخاب هست
طوری باشه که تاریخ انتهایی قبل از یکی از این روز های غیرفعال باشه
مثلا برای رزرو اتاق اگه 20 شهریور قبلا رزرو شده ، دیگه نشه از 18 شهریور تا 24 شهریور رو رزرو کرد .

**Comment by Mds92** [comment]
سلام
یعنی در مد انتخاب رنج روزهای غیرفعال، غیر فعال نیستن

**Comment by Misaghahmadi97** [comment]
اون روز های غیرفعال ، غیرفعال هستند ولی بازم میشه رنجی رو انتخاب کرد که روز غیر فعال بینش باشه
طوری باشه که اگه کاربر یه رنجی رو خواست انتخاب کنه ، روزهای غیر فعال داخل اون روز نباشن

**Comment by Misaghahmadi97** [comment]
اگه مقدور هست آیدی تلگرام بدید یا یه راه ارتباطی باهاتون در ارتباط باشم

**Comment by Mds92** [comment]
خوب باید روزهایی رو غیر فعال کنید که امکان انتخاب رنجی که توش غیر فعال هست نباشه
