### ISSUE TITLE
focus

### ISSUE THREAD

**Issue by aminimohammad** [Mds92/MD.BootstrapPersianDateTimePicker#169]
how to focus in angular?
spamle:
this.birthdate.elmentnative.focus()

**Comment by aminimohammad** [comment]
سلام و خسته نباشید
لطفا راجب focus راهنممایی می کنید

**Comment by Mds92** [comment]
متوجه نمیشم منظورتون چی هست !

**Comment by aminimohammad** [comment]
توی یک کامپوننت از تاریخ استفاده کردم
حالا میخوام با 
typescript
کنترل تاریخ را 
focus 
کنم
مثلا کنترل 
input 
تابع 
focus 
داره
مثل 👍 

 @ViewChild("firstName", { static: false }) firstName: ElementRef;
this.lastName.nativeElement.focus();

**Comment by Mds92** [comment]
این کتابخانه برای typescript
نوشته نشده
اما بنظرم خط زیر تقویم را نمایش نمیده
```
this.lastName.nativeElement.focus();
```
برای نمایش تقویم باید از خود متد های تقویم استفاده کنید
`show`
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#functions

اما اگر دنبال فوکس کردن روی یه المان هستی که تو typesciprt
در بیاری، تو گوگل سرچ کن
