### ISSUE TITLE
غیر فعال کردن انتخاب تاریخ از یک زمان 

### ISSUE THREAD

**Issue by masoud5098** [Mds92/MD.BootstrapPersianDateTimePicker#17]
سلام  
آیا هم اکنون امکان غیر فعال کردن تاریخ از یک زمان خاص وجود دارد ؟
مثلا قبل از سال 94 ممکن نباشد یا بعد از 94 ممکن باشد

**Comment by Mds92** [comment]
سلام، بله وجود دارد، شما باید از ویژگی زیر استفاده کنید
```
ToDate: false, 
    FromDate: false, 
```
مثال های پیوست شده در سورس رو ببینید
```
MD.BootstrapPersianDateTimePicker/Views/
```

**Comment by masoud5098** [comment]
ممنون ، فکر کنم سوال رو درست نپرسیدم 
منظورم این بود که به یک باکس به تنهایی بازه بدیم نه این که دو تا باکس رو به هم وابسته کنیم

**Comment by Mds92** [comment]
برای این کار یه اینپوت مخفی بزارید و اتریبیوت های زیر رو براش مقدار دهی کنید
```
ToDate: false, 
FromDate: false, 
```
و مقدار این اینپوپ مخفی رو مقدار مد نظر خودتون بدید، حالا تکس باکس مورد نظر خودتون رو بزارید و با این اینپوپ مخفی هم گروه کنید، بنابراین مقدار تکس باکس شما محدود میشه به مقدار اینپوت مخفی شما

**Comment by masoud5098** [comment]
سپاس از راهنمایی هوشمندانه شما

**Comment by Masoud1365** [comment]
من دقیقاً همین مشکل را دارم
منتها من میخوام زمانی که از تاریخ تا تاریخ را انتخاب میکنم روزهای قبل از امروز غیر فعال باشه
چطوری باید این کارو بکنم ؟ آیا امکانش هست ؟
برای سیستم های رزرواسیون این خیلی مهم هست چون تاریه های قبل از امروز باید غیر فعال باشه

**Comment by Mds92** [comment]
فعلا چنین امکانی وجود ندارد که قبل از یه تاریخی برای از تایخ تا تاریخ غیر فعال باشد

**Comment by Mds92** [comment]
See new Version
