### ISSUE TITLE
باگ: به هنگام انتخاب بازه، تاریخ شروع می تواند بزرگتر(جلوتر) از تاریخ پایان باشد

### ISSUE THREAD

**Issue by hesamkal2009** [Mds92/MD.BootstrapPersianDateTimePicker#170]
با سلام و احترام
سپاس از زحماتتون روی  این کامپوننت، 
2 مطلب وجود داره که باید خدمتتون عرض کنم، 
1 - به هنگام انتخاب بازه (RangePicker)، تاریخ شروع می تواند بزرگتر(جلوتر) از تاریخ پایان باشد و نه خطایی می دهد کامپوننت و نه انها را جابجا میکند.
2 - به نظر شما دسترسی به کلاس ها می تواند پیاده سازی ساده تری داشته باشد برای کسانی که میخواهند ظااهر تقویم را Override کنند؟
مجددا از زحمات شما سپاسگزارم.

![image](https://user-images.githubusercontent.com/8655233/65369098-543f9380-dc5e-11e9-89a2-7ef5b381c6e3.png)

**Comment by Mds92** [comment]
سلام
1. در رنج سلکتور چطور میتونید تاریخ ها را اشتباه ست نمائید
با استفاده از متد ها یا خود تقویم

2. منظورتون کلاس های css
هست دیگه
اونا قابل دسترس و ویرایش هست
تو پوشه dist
فایل css
مشاهده شود

**Comment by Ali-Azmoud** [comment]
وقت بخیر. 
من هم همین مشکل رو دارم. وقتی رنج سلکتور باشه میتونم تاریخ انتها رو ببرم قبل از تاریخ شروع بزنم با استفاده از
ui
خود دیت پیکر و دیت پیکر خطایی نمیده
