### ISSUE TITLE
تداخل با bootstrap tooltip

### ISSUE THREAD

**Issue by javadfk** [Mds92/MD.BootstrapPersianDateTimePicker#171]
سلام و تشکر از زحمات
خیلی وقت بود دنبال یه همچین برنامه شسته رفته ی کاربردی میگشتم برا تاریخ فارسی
مشکل اینجاست که وقتی روی فیلد ورودی مربوط به تاریخ، تولتپ بوت استرپ رو فعال میکنیم، دیگه نمیشه ماه و سال و تاریخ رو تغییر داد. خطا میده:

$('#persianDateInput').tooltip();

$('#persianDateInput').MdPersianDateTimePicker({ 
	targetTextSelector: '#persianDateInput',
	targetDateSelector: '#hiddenInputText',	
});

read property 'selectedDateToShow' of undefined

**Comment by Mds92** [comment]
سلام
لطفا از اینکه آخرین ورژن رو دارید مطمئن شوید
لطفا خطا را روی فایل sample
سورس ایجاد نمائید و فایل را پیوست نمائید تا بررسی شود
قبلش یه سوال
شما روی '#persianDateInput'
هم تولتیپ فعال کردید هم پاپ اور؟
این کار رو با خود بوت استرپ انجام بدید مشکلی نیست؟
