### ISSUE TITLE
خطا در خروجی برای textformat

### ISSUE THREAD

**Issue by mmhashemi** [Mds92/MD.BootstrapPersianDateTimePicker#172]
من برای textformat اومدم و فرمت زیر را اعمال کردم ولی خروجی بر حسب میلادی داده میشه
```
  $("#dt_class").MdPersianDateTimePicker({
                        targetDateSelector: "#date_class",
                        targetTextSelector: "#showDate_class",
                        textFormat : " dddd dd MMMM yyyy ",
                        isGregorian: false
                    });
```

**Comment by Mds92** [comment]
یعنی در targetTextSelector
خروجی میلادی میبینید؟

**Comment by mmhashemi** [comment]
![Capture](https://user-images.githubusercontent.com/9451500/65385307-10ba5780-dd3a-11e9-8f76-eb30347a3ada.PNG)

مثلا شما این تصویر رو نگاه کنید متوجه میشید.

**Comment by Mds92** [comment]
ببخشید متوجه نشدم
لطفا دقی قتوضیح بدید و نمونه کد html 
و جاوااسکریپت بگذارید

**Comment by mmhashemi** [comment]
برای تکست باکس های تاریخی که در تصویر قبلی میبینید 
 من اومدم و کد زیر رو زدم 
```
                   $(`#dt_class`).MdPersianDateTimePicker({
                        targetDateSelector: `#date_class`,
                        targetTextSelector: `#showDate_class`,
                        textFormat : " dddd dd MMMM yyyy ",
                        isGregorian: false
                    });
```
 وفرمتی که در کد میبینید برای نمایش تاریخ در نظر گرفتم . ولی خروجی که داره به من نمایش میده مشابه تصویر هست .

**Comment by Mds92** [comment]
تو تصویر یه سری تکس باکس هست و بنظر صحیح هست
اون یکی چی هست؟

**Comment by mmhashemi** [comment]
ببینید تاریخ ها درست هستن و در حالت نرمال مشکلی نیست ولی من خواستم متن نمایشی تاریخ فرمتش این باشه 
textFormat : " dddd dd MMMM yyyy ",
بنابراین جلوی هر تاریخ باید بگه مثلا 
سه شنیه 25 شهریور 1398 
ولی تاریخ شمسی رو میبره به میلادی و سه پس سعی میکنه به فرمت مورد نظر ببره و خروجی اشتباه هست

**Comment by Mds92** [comment]
یعنی اونایی ک مشکل دارن
#showDate_class
هستند

**Comment by mmhashemi** [comment]
بله . #showDate_class اشتباه هستن
شما اگه 2 تا شی با نام هایی که من در کد استفاده کردم، ایجاد کنید و سپس قطعه کد بنده رو اجرا کنید متوجه میشید که اشتباه چی هست

**Comment by Mds92** [comment]
برای تولید خطا لطفا یه نمونه کد 
html, javascript
ارسال نمائید
تشکر

**Comment by mmhashemi** [comment]
[bed demo.zip](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3639630/bed.demo.zip)

لطفا این دمو رو بررسی بفرمایید

**Comment by Mds92** [comment]
در حال بررسی مشکل هستم، اطلاع میدم

**Comment by Mds92** [comment]
کد شما مشکلی داشت و کد من نیز مشکلی داشت
دقت کنید در 
targetDateSelector
باید تاریخ میلادی قرار بگیرد
با قراردادن تاریخ میلادی در سلکتور بالا و دریافت آخرین ورژن تست کنید دوباره

**Comment by mmhashemi** [comment]
بله حق باشماست ممنونم از اینکه وقت گذاشتید . این اشتباهی بود که توی دمو که به شما داده بودم کرده بودم ولی تو کد خودم اوکی هست. کد جدید رو تست میکنم و نتیجه رو بهتون اطلاع میدم. بازم ممنونم

**Comment by mmhashemi** [comment]
بسیار سپاسگذارم از وقتی که گذاشتید. تست کردم و مشکل برطرف شده ظاهرا. ممنونم

‫‪Mohammad Dayyan‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۲۳
سپتامبر ۲۰۱۹ ساعت ۸:۵۸ نوشت:‬
