### ISSUE TITLE
دیت پیکر برای اینپوت های داینامیک

### ISSUE THREAD

**Issue by mbasirati** [Mds92/MD.BootstrapPersianDateTimePicker#173]
سلام
من یه تعداد اینپوت توی صفحه دارم که به صورت داینامیک ایجاد میشن و آیدی ندارن
راهی هست که بدون داشتن آیدی و فقط با کلاس از این پلاگین استفاده کرد؟

**Comment by Mds92** [comment]
سلام
بله
شما میتونید با هر مدل css selector
با این کتابخانه کار کنید
فایل readme
مشاهده شود

**Comment by mbasirati** [comment]
ممنون از پاسختون
فایل readme رو مطالعه کردم.
برای فراخوانی دیت پیکر برای یه اینپوت اگه 
`targetTextSelector: '#inputTextDate1'`
 رو نذاریم وقتی تاریخ انتخاب میشه هیچ اتفاقی نمیفته. یعنی هیچ تاریخی توی اینپوت ست نمیشه. ولی من اینپوتهام آیدی ندارن و فقط کلاس دارن

**Comment by Mds92** [comment]
پس targetTextSelector
رو با سلکتور کلاستون پر کنید

**Comment by mbasirati** [comment]
بالاتر عرض کردم که اینپوتها چندتا هستن با یه کلاس مشترک. اگر targetTextSelector رو اسم کلاس قرار بدم با هر تغییر تاریخی توی یکی از اینپوتها همه اینپوتها تغییر میکنن.

**Comment by Mds92** [comment]
بالاخره باید به نحوی اینپوت مورد نظرتون رو جدا کنید
ما ابزار دیگری در اختیار نداریم که بین یک سری اینپوت هایی که همه چیشون یکی هست یه اینپوت مد نظرمون رو جدا کنیم

**Comment by mbasirati** [comment]
من به ناچار از این پلاگین به جای پلاگین شما استفاده کردم
http://babakhani.github.io/PersianWebToolkit/doc/datepicker/example/

توی این پلاگین میشه با سلکتور کلاس به هرتعداد اینپوت که بخوایم دیت پیکر رو اعمال کنیم.
ممنون از پاسخگویی سریعتون
