### ISSUE TITLE
رفع مشکل باز شدن مجدد تقویم بدون اطلاعات

### ISSUE THREAD

**Issue by RezaAVS** [Mds92/MD.BootstrapPersianDateTimePicker#174]
<div dir="rtl">

سلام جناب مهندس
وقت بخیر
من موردی رو قبلا گزارش دادم و براش یه راه حل پیدا کردم
مورد این بود که بعد از کلیک بروی target وقتی دوباره بروی target کلیک میکنیم شکل زیر نمایش داده میشه

![image](https://user-images.githubusercontent.com/51018682/65943430-4b0fad00-e43c-11e9-8fa9-c141a02eef0a.png)

من خط زیر رو اضافه کردم و مشکل برطرف شد
`if ($('.mds-bootstrap-persian-datetime-picker-popover').length === 1) {
                            $('.mds-bootstrap-persian-datetime-picker-popover').popover('hide');
                            return;
                        }
`

این هم فایل اصلاح شده

[jquery.md.bootstrap.datetimepicker.txt](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/3674999/jquery.md.bootstrap.datetimepicker.txt)

ممنون میشم در نسخه جدید اعمال کنید با تشکر

**Comment by Mds92** [comment]
با سلام

من همان موقع هم تست کردم، مشکل را نتونستم ببینم
ممنون میشم بفرمایید با چه مرورگری تست میکنید و آیا فقط در مدال ها اینطور هست یا خیر جای دیگر هم اینطور هست
چون در هنگام ایجاد یه پاپ اور بقیه بسته می شوند و مشابه کد شما قبلا نوشته شده است

با تشکر

**Comment by RezaAVS** [comment]
<div dir="rtl">

در هر جایی استفاده بشه به این شکل می باشد

من از مرورگر فایرفاکس و کروم استفاده میکنم در هر دو همین مشکل رو دارم اما وقتی این کد رو اضافه کردم مشکل کاملا برطرف شد

از اخرین نسخه هم استفاده کردم
فایرفاکس نسخه 69.0.1
کروم نسخه 77.0.3865.90 (Official Build) (64-bit)
---------------------------
نکته: در کروم مرتب نمایش داده می شود که به نظرم ایراد هست
اگر نیاز هست بهتون ریموت بدم؟

**Comment by Mds92** [comment]
تو فایرفاکس مشکل رو متوجه شدم
به عنوان باگ تصحیح شد
لطفا ورژن جدید را دریافت نمائید

**Comment by RezaAVS** [comment]
<div dir="rtl">

جناب مهندس ممنون از لطفتون
فقط اگر میشه در صورت کلیک بروی target تقویم بسته شود خیلی عالی می شود

**Comment by Mds92** [comment]
بررسی میکنم
لطفا تو چند روز آینده یادآوری شود
