### ISSUE TITLE
ست کردن دو آپشن با setOption

### ISSUE THREAD

**Issue by Misaghahmadi97** [Mds92/MD.BootstrapPersianDateTimePicker#175]
سلام و وقتتون به خیر
از اونچایی که ست آپشن برای یک مورد هست فقط ، بنده میخواستم به محض تغییر چندین آپشن رو ست کنم یا تغییر بدم . میخواستم ببینم راهکار چیه
دو تا انتخاب تاریخ دارم یکی تاریخ ورود و یکی خروج هست . میخوام بگم تاریخ ورود انتخاب شد ، روز های قبل از تاریخ ورود و روز های بعد از 5 روز از تاریخ ورود رو غیر فعال کن
مثلا 2019-10-3 تاریخ ورود هست ، قبل از اون غیر فعال بشه برای تاریخ خروج و 2019-10-9 به بعد هم غیر فعال بشه .
اگه یه آپشن باشه میشه ست کرد ولی دو تا آپشن رو نمیشه ست کرد
$('#selectExitDate').MdPersianDateTimePicker('setOption', 'disableAfterDate', new Date(2019, 9, 8));
 $('#selectExitDate').MdPersianDateTimePicker('setOption', 'disableBeforeDate', new Date(2019, 9, 3) );

**Comment by Mds92** [comment]
سلام
یعنی تکه کدی که نوشتید کار نمیکنه؟

**Comment by Misaghahmadi97** [comment]
بله . کار نمیکنه

**Comment by Mds92** [comment]
آیا آخرین ورژن را دریافت کرده اید
اگر بله لطفا یه نمونه کد html
اینا بگذارید تا بتونم خطا را ببینم و تصحیح کنم

**Comment by Misaghahmadi97** [comment]
با آپدیت به آخرین نسخه مشکل برطرف شد . 
با عرض پوزش
بنده چندین سوال دیگه هم داشتم میخواستم ببینم راه ارتباطی دیگه نیست که باهاتون در ارتباط باشیم ؟ تلگرام ، ایمیل یا ....

**Comment by Mds92** [comment]
لطفا سوالات خودتون را همینجا مطرح نمائید
