### ISSUE TITLE
آیا امکان نمایش تقویم به صورت شمسی و میلادی به صورت همزمان وجود دارد ؟ 

### ISSUE THREAD

**Issue by MehranMazhar** [Mds92/MD.BootstrapPersianDateTimePicker#177]
آیا امکان نمایش تقویم به صورت شمسی و میلادی به صورت همزمان وجود دارد ؟ 
یعنی امکانی باشد تا تقویم به شمسی و میلادی تغییر کند .

**Comment by Mds92** [comment]
بله میتونید
پراپرتی 
isGregorian
معین میکند این تقویم شمسی است یا میلادی
یه متد هم هست به نام
changeType
که میتونید نوع تقویم را عوض کنید
لطفا بررسی نمائید

**Comment by MehranMazhar** [comment]
بله در داکیومنت متوجه شدم .
منظورم این بود امکانی نیست تا بر روی خود تقویم دکمه ای  باشد که تقویم به میلادی و  شمسی تغییر کند ؟

**Comment by Mds92** [comment]
خیر چنین امکانی نداریم
