### ISSUE TITLE
سلام این ارور در هنگام انتخاب تاریخ برگردانده میشود

### ISSUE THREAD

**Issue by iranidesign** [Mds92/MD.BootstrapPersianDateTimePicker#18]
jquery.Bootstrap-PersianDateTimePicker.js:715 

Uncaught TypeError: Cannot set property 'Day' of undefined

```
// تغییر روز
            case changeDateTimeEnum.DayChanged:
                newDateTimeInJsonFormat.Day = Number(toEnglishNumber($.trim($senderObject.text())));
                hidePopover($popoverDescriber);
                break;
```
مشکل از کجا می باشد؟

**Comment by Mds92** [comment]
نمیدونم مشکل از کجاست
اطلاعات گفته شده کافی نیست
لطفا منتظر نسخه جدید باشید تا چند روز دیگه قابل دانلود هست

**Comment by mbasirati** [comment]
I had this problem too. 
because I used "livequery" jquery plugin.
When I removed this plugin, my problem solved.
