### ISSUE TITLE
disable days

### ISSUE THREAD

**Issue by saeid94a** [Mds92/MD.BootstrapPersianDateTimePicker#180]
سلام وقتتون بخیر
تشکر فراوان بابت تقویم عالیتون
میخواستم بدونم راهی وجود داره که خاصیت غیرفعال کردن روزهای خاص، که در ورژن 4 اضافه شده را برای ورژن 3 با بوت استرپ 3 اضافه کنیم؟

**Comment by Mds92** [comment]
سلام، خوشحالم که مورد استفاده واقع شده
ورژن 3 دیگه بروز رسانی نمیشه و امکان اضافه کردنش وجود نداره
