### ISSUE TITLE
MdPersianDateTimePicker Uncaught TypeError: Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by kabiri** [Mds92/MD.BootstrapPersianDateTimePicker#182]
وقتی در به صورت دینامیک ادیتی برای تقویم میسازم با کلیک روی دکمه تقویم باز نمیشه
و اگه از دستور زیر استفاده کنم
$('#TSelL').MdPersianDateTimePicker('show');
ارورر میده
MdPersianDateTimePicker Uncaught TypeError: Cannot read property 'trigger' of undefined

البته id درست ست شده و تکراری نیست

**Comment by Mds92** [comment]
دقت شود پس از ایجاد المان به صورت داینامیک باید دوباره پلاگین روی آن فعال شود
یعنی چنین چیزی:
```
$('#TSelL').MdPersianDateTimePicker();
```
لطفا خطایی که تو این کد میگیرید را ارسال کنید

**Comment by kabiri** [comment]
بعد از ایجاد به صورت داینامیک کد رو اضافه کردم و با کلیلک روی دکمه کار نکرد

بعد کد رو به حالت
$('#TSelL').MdPersianDateTimePicker({targetTextSelector: '#TSel',
        toDate: false,
        placement: 'top',
        dateFormat: 'yyyy/MM/dd',
        textFormat: 'yyyy/MM/dd'});

در اوردم و این ارور رو میده
jquery-3.3.1.min.js:2 Uncaught SyntaxError: Invalid regular expression: /(^|\.)bs\.(?:.*\.|)popover(\.|$)/: Maximum call stack size exceeded

**Comment by Mds92** [comment]
بنظرم مشکلی در کدهای خودتان هست
من چنین اکسپرشنی در این پلاگین ندارم

لازم به توضیح هست که بهتر هست 
targetDateSelector 
را هم مشخص کنید

**Comment by kabiri** [comment]
من یه باتن برای اضافه کردن یه رکورد به جدول دارم
یکی از ستون های جدول تاریخ هست
تو این ستون این اطلاعات رو قرار میدم
`<div class="input-group">     <div class="input-group-prepend">         <span class="input-group-text cursor-pointer TSelL" id="TSelL" name="TSelL" data-mdpersiandatetimepicker="" data-mdpersiandatetimepicker-group="" data-todate="" data-original-title="" title="">تاریخ</span>     </div>    <div style="width:100px">        <input enable="Enable" class="form-control inputstl text-box single-line" id="TSel" name="TSel" type="text" value="">     </div> </div>`
بعد اضافه کردن این ستون
این رو فراخوانی کردم
$('#TSelL').MdPersianDateTimePicker();
همین
بعد کلیک روی باتن مدتی به حالت هنگ میمونه
همون پیام ارور قبلی رو میده بعد صفحه انتخاب تاریخ نمایش داده میشه

**Comment by kabiri** [comment]
ممنون مشکل رو فهمیدم
تو کلاس
TSelL
رو هم اضافه کرده بودم که حذف کردم درست شد
فقط دیت پیکر کل عرض صفحه رو میگیره چیکار کنم مثل  عکس شما مربع باشه

**Comment by Mds92** [comment]
خدا رو شکر
باید ببینید کدام css
شما داره css
های پلاگین را override
میکنه

**Comment by kabiri** [comment]
من از 
css
های خود بوت استراپ 4 استفاده کردم
کدوم کلاس طول و عرض رو مشخص کرده؟

**Comment by kabiri** [comment]
> خدا رو شکر
> باید ببینید کدام css
> شما داره css
> های پلاگین را override
> میکنه

چطور بفهمم؟
من خیلی سعی کردم ولی نشد

**Comment by Mds92** [comment]
باید با کروم یا مرورگر دیگری روی المان 
Inspect
بزنید و بررسی کنید چه CSSیی
داره کارو خراب میکنه

**Comment by kabiri** [comment]
من استایل
<style>
.popover
{
right:auto
}
</style>
رو به صفحه اضافه کردم و درست شد
ولی من همچین کلاسی تعریف نکرده بودم که کانفلیک کنه
