### ISSUE TITLE
selectedDate

### ISSUE THREAD

**Issue by kabiri** [Mds92/MD.BootstrapPersianDateTimePicker#183]
سلام
تاریخ انتخاب شده رو چطور میشه به شمسی داد
تو راهنما گفته
selectedDate
میلادیه
همچنین ساعت انتخابی پیش فرض رو چطور میشه ست مرد

**Comment by Mds92** [comment]
سلام
selectedDate
رو مقدار دهی نکنید و تاریخ شمسی به همراه زمان را در 
targetSelectedText
قرار بدید
ببینید مشکل حل میشه؟
برای مقدار دهی زمان، کافی هست 
selectedDate
با زمان صحیح پر شود

**Comment by kabiri** [comment]
مقدار
"۱۳۹۸/۰۸/۰۵ ۱۶:۵۹:۰۰"
رو توی متفییر دخیره دارم پاس میدم ولی نشون نمیده

`           $('#TSelL').MdPersianDateTimePicker({
                targetDateSelector: 'input[name=TSelL]',
                targetTextSelector: 'input[name=TSel]',
                dateFormat: 'yyyy/MM/dd HH:mm',
                textFormat: 'yyyy/MM/dd HH:mm',
                targetSelectedText: DT,
                enableTimePicker: true
            });`

**Comment by Mds92** [comment]
نه اینطوری منظورم نیست
تاریخ را داخل تکس باکسی بزارید که تقویم روش فعال میشه
یعنی تاریخ رو داخل
input[name="TSel"]
بگذارید

**Comment by kabiri** [comment]
آها اونجا گداشته بودم ولی نشد
وقتی خودش اون رو پر میکنه درسته ولی اگه خودم پرکنم روز جاری رو نشون میده

**Comment by Mds92** [comment]
> وقتی خودش اون رو پر میکنه درسته ولی اگه خودم پرکنم روز جاری رو نشون میده
این یعنی چی؟

آیا 
setDatePersian
رو هم تست کردی؟
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker

**Comment by kabiri** [comment]
> > این یعنی چی؟

یعنی تو همون اینپوتی که خودش تاریخ رو مینویسه من تاریخ رو بنویسم کار نمیکنه و تاریخ امروز زو میاره

تابع
setDatePersian
هم یه مشکلی داره فکر کنم
دیت پیکر شما اعداد فارسی برمیگردونه یعنی عدد 1 رو به صورت ۱ (فارسی) نمایش داده میشود و به همین صورت ذخیره میشود و به همین صورت به تابع پاس داده میشود
و تابع خطا میدهد
Uncaught Error: Invalid Jalaali year -100721
    at n (jquery.md.bootstrap.datetimepicker.js:57)
    at jquery.md.bootstrap.datetimepicker.js:103
    at t (jquery.md.bootstrap.datetimepicker.js:19)
    at be (jquery.md.bootstrap.datetimepicker.js:739)
    at Q (jquery.md.bootstrap.datetimepicker.js:497)
    at V (jquery.md.bootstrap.datetimepicker.js:513)
    at w.fn.init.setDatePersian (jquery.md.bootstrap.datetimepicker.js:2068)
    at w.fn.init.e.fn.MdPersianDateTimePicker (jquery.md.bootstrap.datetimepicker.js:2100)
    at HTMLImageElement.<anonymous> (Index:443)
    at HTMLTableElement.dispatch (jquery-3.3.1.min.js:2)

**Comment by Mds92** [comment]
تو 
setDatePersian
باید اعداد انگلیسی پاس بدی دیگه
جاوااسکریپت هست

**Comment by kabiri** [comment]
ممنون
