### ISSUE TITLE
اضافه کردن قیمت

### ISSUE THREAD

**Issue by Misaghahmadi97** [Mds92/MD.BootstrapPersianDateTimePicker#184]
سلام
وقت به خیر
میخواستم از پلاگینتون برای یک سایت رزرو استفاده کنم ، برای همین در کنار پلاگین مفدیتون میخواست مامکان 
 اضافه کردن یه دیتا اتریبیوت به تقویم رو هم بدیم برای قیمت
برای تاریخ های خاص ، روز هفته و ...
اگه مقدور باشه که ممنون میشم ، در صورتی که هزینه هم داره اعلام کنید
ممنون

**Comment by Mds92** [comment]
سلام وقت بخیر
یعنی این یتا اتریبیوت یه روزها اضافه شود؟
چون کار کاملا اختصاصی خودتون هست بله هزینه داره

**Comment by Misaghahmadi97** [comment]
بله . قابلیت قیمت گذاری برای روز های مختلف هفته و همچنین تاریخ های خاض خود کاربر رو داشته باشه
و بعد از انتخاب روز ها ، قیمت کلی رو بشه گرفت
اگه مقدور هست یه راه ارتباطی بدید که صحبت کنیم
تقویم مشابه سایت شب میخواستم

**Comment by Mds92** [comment]
لطفا مستند درخواستی ، کامل ارسال شود
کمی توضیحات مبهم هست
mds.soft@gmail.com

**Comment by monazigro** [comment]
> سلام وقت بخیر
> یعنی این یتا اتریبیوت یه روزها اضافه شود؟
> چون کار کاملا اختصاصی خودتون هست بله هزینه داره

سلام من هم دقیقا همچین ویژگی رو میخوام
 توی این پلاگین این امکان وجود نداره که برای هر روز بتونیم یه مقدار اختصاص بدیم ؟(مثل قیمت)
