### ISSUE TITLE
بسته شدن با کلیک بر روی صفحه

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [Mds92/MD.BootstrapPersianDateTimePicker#186]
با عرض سلام و خسته نباشید ممنون بابت پلاگین خوبتون
من یه کاری میخواستم بکنم که هنوز موفق نشدم بعد 4 روز اینه که میخوام بعد باز شدن تقویم
با کلیک به هرجای صفحه بسته شه
الان فقط وقتی بسته میشه که روی یه تاریخی کلیک شه اما میخواستم با کلیک به هر جا بسته شه
ممنون

**Comment by Mds92** [comment]
با سلام
این عملکرد پیش فرض تقویم هست
فایل های sample در پوشه demo
مشاهده شود
مطمئن شید که آخرین ورژن نرم افزار را استفاده میکنید

**Comment by darvishiyan-mahdi** [comment]
از آخرین ورژن استفاده میکنم 
محض احتیاط چک هم کردم اما بازم کارنکرد 
نمیدونم این که دارم توی 
adminlte
استفاده میکنم موثره یا نه

**Comment by Mds92** [comment]
تو فایل های سمپل درست نیست؟
اگر تو فایل های sample درست هست
چیزی دارید تو کدهاتون که این عملکرد پلاگین را تحت تاثیر قرار میده

**Comment by darvishiyan-mahdi** [comment]
این عملکرد دقیقا توی کجای فایل ها هست من بررسی کنم ؟

**Comment by Mds92** [comment]
این عملکرد 
bootstrap popover
هست
چیزی برای آن نوشته نشده

**Comment by darvishiyan-mahdi** [comment]
درسته ممنون
