### ISSUE TITLE
انتخاب شمسی و خروجی میلادی!

### ISSUE THREAD

**Issue by mmojbo** [Mds92/MD.BootstrapPersianDateTimePicker#188]
سلام وقت بخیر
تشکر از شما برا این پلاگین

من یه مشکل دارم که هرچی بررسی کردم متوجه نشدم

تاریخی که از datepicker انتخاب میشه
شمسی هست

اما میلادی میشینه تو فیلد

ممنون میشم راهنمایی کنید

**Comment by Mds92** [comment]
سلام
ببینید شما دو تافیلد باید برای پلاگین تعیین کنید
یه فیلد، اونی هست که توش تاریخ فارسی رو قرار میده و بهتر هست فقط برای نمایش استفاده شود 
`targetTextSelector`
یه فیلد برای قرار دادن معادل میلادی تاریخ انتخاب شده است که برای ارسال به بک اند استفاده میشه
`targetDateSelector`
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#how-to-use
فایل readme
یا همون صفحه نخست پروژه رو خوب ببینید
همچنین تو سورس یه پوشه هست به نام دمو، اونم بررسی کنید

**Comment by mmojbo** [comment]
ممنون از توضیحتون

یه سوال دیگه داشتم که ممنون میشم پاسخ بدید

اگه من در صفحه همزمان چند فیلد تاریخ داشته باشم
راهی هست که با یه اسکریپن بشه همه رو فراخوانی کرد

به عبارت دیگه مجبور نباشم برا هر فیلد پلاگین رو فراخونی کنم

ممنون

**Comment by Mds92** [comment]
اینکه میگید همه رو با یک اسکریپت فراخوانی کنم یعنی چی
منظورتون از فراخوانی همه چیه؟

**Comment by mmojbo** [comment]
تاجایی که من متوجه شدم
اگه در فرم من چند تا فیلد تاریخ داشته باشم
باید برای تک تکشون اسکریپ رو بنویسم
مثلا اگه 3 تا فیلد تاریخ داشته باشم باید این اسکریپت رو سه بار به ازای هر کدوم بنویسم

$('#date3').MdPersianDateTimePicker({
    targetTextSelector: '#inputDate3',
    monthsToShow: [1, 1]
});

میخوام بدونم راهی داره که فقط یه بار اسکریپت فعال ساری رو بنویسم ولی تو چند فیلد بتونم ازش استفاده کنم

مثلا از طریق
tag data attr

**Comment by Mds92** [comment]
خوب میتونید سلکتور خودتون رو تصحیح کنید
```
$('#date1,#date2,#date3').MdPersianDateTimePicker({
   targetTextSelector: '#inputDate3',
   monthsToShow: [1, 1]
});
```
این اسکریپت روی 3 فیلد date1 تا 3 اعمال میشه
