### ISSUE TITLE
قرار دادن اعداد انگلیسی به جای فارسی

### ISSUE THREAD

**Issue by djary** [Mds92/MD.BootstrapPersianDateTimePicker#19]
سلام خسته نباشید
می خواستم وقتی که ما تاریخ رو انتخاب میکنیم در تکست باکس به اعداد را فاررسی نمایش میدهد 
من می خواهم اعدادی که در تکست باکس قرار گرفتن به صورت لاتین باشند
میشه راهنمایی بفرمایید ؟

**Comment by Mds92** [comment]
سلام
باید مشخصه زیر رو به تگ اضافه کنید
```
data-englishnumber="true"
```
