### ISSUE TITLE
مشکل در اینترنت اکسپلورر 11

### ISSUE THREAD

**Issue by rbsdotnet** [Mds92/MD.BootstrapPersianDateTimePicker#190]
سلام وقت بخیر
آیا راهی وجوده داره که برای مرورگر اینترنت اکسپلورر 11 کار کنه؟
چون خطا داره و مشکلش هم عدم پشتیبانی از کاراکتر زیر می باشد
[ ` ]

**Comment by Mds92** [comment]
سلام
چه فایل جاوا اسکریپتی رو پیوست فایل HTML کردید؟
شما باید فایل های minify شده را استفاده نمائید، نه خود سورس اصلی را

**Comment by rbsdotnet** [comment]
من از npm استفاده کردم
و دقیقا طبق مثال این فایل رو اضافه کردم
<script src="/dist/jquery.md.bootstrap.datetimepicker.js"></script>

**Comment by Mds92** [comment]
پس فکر نمیکنم بتونید کاری کنید
مگر اینکه سورس را ویرایش کنید و هرجا ` هست را تغییر بدید

**Comment by rbsdotnet** [comment]
باید به جای کاراکتر فوق از روش چسباندن رشته ها استفاده کنم؟ درست؟
چون این ساختار برای قالب بندی رشته ها هست مثل C#

**Comment by Mds92** [comment]
بله درست هست

**Comment by rbsdotnet** [comment]
ممنون پس از اصلاح و تست نسخه ای هم برای شما ارسال میکنم که در npm قرار بدید
تا سایر دوستان هم در صورت نیاز استفاده کنن
