### ISSUE TITLE
صفر کردن دقیقه و ثانیه

### ISSUE THREAD

**Issue by uoogle** [Mds92/MD.BootstrapPersianDateTimePicker#191]
سلام

من یه مشکلی دارم

میخواستم زمان را کاربر وارد کنه و از ساعت فعلی استفاده نکنه

یا حداقل فقط ساعت را از زمان فعلی بخونه و دقیقه و ثانیه را 0 برگردونه مثل این 

http://uupload.ir/files/ta0d_screenshot-192.168.0.97-2020.03.11-11_35_47.png

ممنون میشم راهنمایی کنید

**Comment by Mds92** [comment]
سلام
یعنی میخواهید کاربر فقط ساعت رو بتونه وارد کنه
درسته؟
اگر همینطور هست میتونید با ویرایش فایل 
css
این فیلدها رو غیرفعال یا مخفی کنید

**Comment by uoogle** [comment]
اگر تصویر را نگاه کنید مشخصه

درحال حاضر ساعت ،دقیقه و ثانیه از زمان فعالی حساب میشه


من میخوام فقط ساعت را از زمان فعلی نمایش بده و ثانیه و دقیقه را 0 نشون بده


توی جاوا اسکریپت یه مقدار کد هارا تغییر دادم ولی خب یه مشکل کوچیک داره

میخوام اصولی انجام بشه

**Comment by uoogle** [comment]
بله
