### ISSUE TITLE
استفاده از پلاگین در ASP

### ISSUE THREAD

**Issue by yousefg** [Mds92/MD.BootstrapPersianDateTimePicker#192]
سلام
برای استفاده از تقویم فارسی با کلیک در تکست باکس از چه دستوری باید استفاده کرد؟
آیا این نسخه قابلیت اجرا در ajaxToolkit:ModalPopupExtender رو داره؟
ممنون

**Comment by Mds92** [comment]
سلام
با خواندن فایل 
readme
به راحتی جواب سوال رو میگرفتین!
نمایش تقویم با فوکوس کردن روی تکس باکس
```javascript
$('#textBoxId').MdPersianDateTimePicker({ 
  targetTextSelector: '#inputTextDate1',
  targetDateSelector: '#inputHiddenDate1',
  trigger: 'focus'
});
```
این یه پلاگین جی کوئری هست، آیا وقتی از 
ajaxToolkit
استفاه می کنید میتونید از پلاگین های جی کوئری استفاده کنید؟
در این صورت مشکلی نیست.
