### ISSUE TITLE
تقویم هجری و تعطیلات رسمی را نیز اضافه کنید

### ISSUE THREAD

**Issue by myehrajat** [Mds92/MD.BootstrapPersianDateTimePicker#193]
تقویم هجری و تعطیلات رسمی را نیز اضافه کنید
خیلی کاربردی است
سپاس

**Comment by Mds92** [comment]
سلام
هنوز کتابخانه ای برای محاسبه تقویم هجری پیدا نکرده ام
برای تعطیلات رسمی می توانید با مقدار دهی
holiDays
آنها را فعال کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options
