### ISSUE TITLE
How to use the plugin in laravel mix

### ISSUE THREAD

**Issue by RezDev94** [Mds92/MD.BootstrapPersianDateTimePicker#194]
من میخوام توی لاراول اینجوری از پلاگین استفاده کنم ولی داره ارور میده
`require('md.bootstrappersiandatetimepicker')`

ارور اینه
`Uncaught Error: Cannot find module 'md.bootstrappersiandatetimepicker'`

**Comment by Mds92** [comment]
خوب داره خطای درستی میده
چون این ماژولی نیست که بتونید اینطوری ازش استفاده کنید
تو فایل HTML
اضافه کنید
قسمت زیر را مطالعه کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#installing

**Comment by RezDev94** [comment]
به نظرم اگر میشد توی وبپک هم ازش استفاده کرد خیلی خوب میشد
به هر حال ممنون
