### ISSUE TITLE
مشکل با ajax

### ISSUE THREAD

**Issue by omoridi** [Mds92/MD.BootstrapPersianDateTimePicker#195]
سلام، پس از فراخوانی ایجکس، تقویم نمایش داده میشود و میپرد.
البته بعد از فراخوانی ایجکس دوباره تمامی تنظیماتی که در داکیومنت ردی هست رو دوباره فراخوانی میکنم ولیکن بازم مشکل است.

**Comment by Mds92** [comment]
سلام
مشکل همان مقدار دهی دوباره تقویم هست
تقویم باید یکبار مقدار دهی شود
مقدار دهی دوباره باعث تولید دوباره کد و پرش تقویم میشود

**Comment by omoridi** [comment]
سلام انجام میشه ولی باز همون مشکل است.
البته در تو ایونت 
یکی 
$(document).ready
و دیگری
$(document).ajaxComplete
هر دو یک تابع تنظیم صدا میشوند اولی درست  .ولی دومی نه

**Comment by Mds92** [comment]
در هر حالت فقط یکبار باید مقدار دهی شود
دقت کنید فقط یکجا مقدار دهی شود
وقتی تقویم میپره داره چند جا مقدار دهی میشه
