### ISSUE TITLE
مشکل با متد "setDateRange"

### ISSUE THREAD

**Issue by mheidarian** [Mds92/MD.BootstrapPersianDateTimePicker#196]
$('#DateReport').MdPersianDateTimePicker('setDateRange',new Date(fromDateString),new Date(toDateString));

در این قطعه کد اگر تاریخ "از" و تاریخ "تا" یکی باشد خطای زیر رخ می دهد
"مقدار ورودی نا معتبر است, تاریخ شروع باید بزرگتر از تاریخ پایان باشد"

jquery.md.bootstrap.datetimepicker.js:2086 Uncaught Error: MdPersianDateTimePicker => setDateRange => مقدار ورودی نا معتبر است, تاریخ شروع باید بزرگتر از تاریخ پایان باشد
    at w.fn.init.setDateRange (jquery.md.bootstrap.datetimepicker.js:2086)
    at w.fn.init.e.fn.MdPersianDateTimePicker (jquery.md.bootstrap.datetimepicker.js:2197)
    at WorkTimeReport?DateReport=۱۳۹۹%2F۰۲%2F۱۷+-+۱۳۹۹%2F۰۲%2F۱۷&MemberId=7:424

**Comment by Mds92** [comment]
لطفا مقادیر 
fromDateString و toDateString
را بنویسید
وقتی دارید تاریخ را وارد میکنید خوب نباید برابر باشند در غیر اینصورت رنج تاریخی نمی شود

**Comment by mheidarian** [comment]
$('#DateReport').MdPersianDateTimePicker('setDateRange',new Date(2020,5,8),new Date(2020,5,8));

 من حالت رنج رو برای یک گزارش عملکرد استفاده کردم که خب ممکنه کاربر بخواد اون گزارش رو برای یک روز بگیره. یعنی عملکرد روزانه. اونجا تکلیف چی میشه؟

**Comment by Mds92** [comment]
این قابلیت رو اضافه کردم اما بهتر هست که برای انتخاب یک روز ساده تر عمل کنید تا کاربر نیز راحت تر باشه
مثلا یه رادیو باتن داشته باشید که کاربر بزنه یک روز یا یک ماه
بعد برای انتخاب ماه که یه دراپ داون انتخاب ماه باشه و برای یک روز از دیت پیکر استفاده شود
:-)

ورژن 3.7.1 را دریافت کنید
