### ISSUE TITLE
نبود آپشن Range Date Disable

### ISSUE THREAD

**Issue by amirjelodarian** [Mds92/MD.BootstrapPersianDateTimePicker#198]
سلام این دیتاپیکر عالیه اما اینو کم داره
خودم یکم سرم شلوغه وگرنه میتونستم آپشنشو اضافه کنم
ولی چه بهتر ک این آپشنو صاحبه مهندسش اضافه کنه

**Comment by Mds92** [comment]
سلام
متوجه نشدم چیو کم داره!

**Comment by amirjelodarian** [comment]
سلام
من از دیتا بیس رنجی از تاریخ رو میگیرم
مثلا
1399/03/01 1399/03/9
میخوام این دو تا تاریخ رو بدم به تقویم و این رنج رو غیر فعال کنه
اگر میلادی تقویم قبول میکنه برای عیر فعال کردن مشکلی نیس با پی اچ پی شمسی رو به میلادی تبدیل میکنم
اما میخوام رنجی غیر فعال کنه 
نه هر روز هر روز

خیلی ممنون بابت این تقویم عالییی

**Comment by Mds92** [comment]
می تونید از option ها در مقداردهی اولیه استفاده کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options
این ها رو ببینید
```
selectedDate رنج رو به صورت روز به روز به این آرایه بدید
```
اگر هم رنج ممکن هست خیلی طولانی باشه از دو آپشن زیر استفاده کنید
``` 
disableBeforeDate
disableAfterDate
```

**Comment by amirjelodarian** [comment]
رنج که زیاد هست 
این تقویم رو میخوام برای رزرویشن استفاده کنم
یعنی ممکنه چند نفر چند تا رنج روزو رزرو کنن
اگه چند تا رنج اونجوری باشه 
دونه دونه باید غیر فعال کنم اون روزو که این خیلی بد میشه

**Comment by Mds92** [comment]
پس از دو آپشن گفته شده استفاده کنید
```
disableBeforeDate
disableAfterDate
```

**Comment by amirjelodarian** [comment]
یک مشکل کوچیک به چشمم خورد
disabledDates: [
            new Date(2020,5,22)
        ]
از این استفاده کردم 
اما 22 ماه بعد رو غیر فعال کرد
مثل اینکه یک ماه جلوترو غیرفعال میکنه

**Comment by Mds92** [comment]
دقت کنید تو مقدار دهی 
Date در جاوااسکریپت 
ماه میلادی از 0 شروع میشه
https://www.w3schools.com/jsref/jsref_getmonth.asp
