### ISSUE TITLE
گرفتن مقدار میلادی از ورودی اصلی و تبدیل و نمایش آن

### ISSUE THREAD

**Issue by RezaKamalian** [Mds92/MD.BootstrapPersianDateTimePicker#199]
سلام.
‍
آیا امکان گرفتن مقدار میلادی از ورودی اصلی و تبدیل و نمایش آن به تاریخ شمسی در همان ورودی هست؟

‍`<input type="text" id="inputDate3" class="form-control"
                        placeholder="DateTimePicker" aria-label="date3" aria-describedby="date3"
                        value="2020/02/01">‍`

**Comment by Mds92** [comment]
سلام
این قسمت را ببینید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#functions
```
setDate
setDatePersian
```

**Comment by RezaKamalian** [comment]
ممنون. اما مگر `setDate` برای بعد از انتخاب تاریخ استفاده نمیشه؟ 

منظور من مقدار پیش‌فرض ورودی بود.

**Comment by Mds92** [comment]
بنظرم منظورتون 
selectedDate
هست
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by RezaKamalian** [comment]
حتما من نتونستم درست منظورم رو بیان کنم.

فرض بفرمایید ما مقدار تاریخ رو به میلادی(2020/02/01) وارد دیتابیس کردیم. حالا نیاز به نمایش آن  تاریخ  توی صفحه به شمسی داریم. در این حالت مقدار ورودی رو از دیتابیس توی (ولیو) ورودی قرار میدیم.

‍`<input type="text" id="inputDate3" class="form-control" placeholder="DateTimePicker" aria-label="date3" aria-describedby="date3" value="2020/02/01">‍`

 در حال حاضر به صورت میلادی در خروجی نمایش داده می شود درصورتی که نمایش خروجی باید شمسی باشد. توی فایل توضیحات با روش دریافت مقدار از طریق ورودی تارگت انجام شده است نه از طریق ورودی مبدا.

**Comment by Mds92** [comment]
اینطوری نمیتونید مقداردهی اولیه کنید
باید از option های خود پلاگین استفاده کنید
مثلا این روش مقدار اینپوت شما رو به عنوان مقدار اولیه به پلاگین میده
```javascipt
$('#inputDate3').MdPersianDateTimePicker({ 
  targetTextSelector: '#inputDate3',
  targetDateSelector: '#inputHiddenDate1',
  selectedDate: new Date(Date.parse($('#inputDate3').val()))
});
```
