### ISSUE TITLE
ارور در زمان اجرا

### ISSUE THREAD

**Issue by hp1361** [Mds92/MD.BootstrapPersianDateTimePicker#2]
با عرض سلام و تشکر بابت ارائه این تقویم

در زمان اجرا برنامه ارور زیر رو میده

Unhandled exception at line 701, column 17 in http://localhost:16932/Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js

0x800a138f - JavaScript runtime error: Unable to set property 'Day' of undefined or null reference

ممنون

**Comment by Mds92** [comment]
با سلام
این پروژه، یه پروژه MVC نیست، من برای اینکه تو محیط ویژوال استادیو اونو گسترش بدم تو یه پروژه MVC روش کار کردم.
اول : نباید پروژه رو تو ویژوال استادیو بیلد کنید.
برای اجرا، برید تو پوشه Views و فایل های HTML رو تو مرورگر خودتون باز کنید.

من باز تست کردم مشکلی ندیدم.
