### ISSUE TITLE
very thanks for your work

### ISSUE THREAD

**Issue by vahidalvandi** [Mds92/MD.BootstrapPersianDateTimePicker#20]
hello dear @Mds92  i use your date picker in my projects

من چطوری میتونم به جای / از خط تیره - بین روز و ماه و سال استفاده کنم

thank you very much

**Comment by Mds92** [comment]
سلام
آخرین ورژن رو دانلود کنید
تغییرات زیادی کرده
الان تقویم میلادی هم داره
الان میتونید به تقویم فرمت بدهید تا به فرمت مورد نیاز شما روز انتخاب شده رو نمایش بده
لطفا فایلی که در مسیر زیر هست رو مطالعه کنید و یا دموی 3 رو ببینید
اما به طور عاجل باید مشخصه زیر رو به تگ مورد نظر خودتون اضافه کنید
```
data-format="yyyy-MM-dd"
```
