### ISSUE TITLE
وقتی englishNumber را True قرار میدهیم بخشی از اعداد انگلیسی نمی شوند

### ISSUE THREAD

**Issue by myehrajat** [Mds92/MD.BootstrapPersianDateTimePicker#200]
is:issue is:open وقتی englishNumber را True قرار میدهیم بخشی از اعداد انگلیسی نمی شوند
تصویر : https://img.techpowerup.org/200603/capture.png

**Comment by Mds92** [comment]
تشکر بابت گزارش مشکل
تصحیح شد
ورژن جدید را دانلود کنید

**Comment by myehrajat** [comment]
سپاس
