### ISSUE TITLE
مشکل در نمایش در مودال

### ISSUE THREAD

**Issue by arbabi2010** [Mds92/MD.BootstrapPersianDateTimePicker#203]
سلام. ممنون از کتابخونه خوبتون.
توی بوتسترپ 4 وقتی از پکیج توی مودال استفاده میکنم نمایش درستی نداره و زیر مودال قرار میگیره. من حتی tabindex رو هم برداشتم اما فرقی نکرد

**Comment by Mds92** [comment]
سلام
تو پوشه 
demo
یه فایل هست برای مدال های بوت استرپ
اونم بررسی کردید؟
