### ISSUE TITLE
مشکل در تابع getDateRange

### ISSUE THREAD

**Issue by KAJOOSH** [Mds92/MD.BootstrapPersianDateTimePicker#204]
سلام
احتراما تابع getDateRange در زمان استفاده از رنج تاریخ مشکل دارد و خطای ذیل داده می شود.
`setting is undefined`

**Comment by Mds92** [comment]
سلام
دقت کنید اگر تاریخی انتخاب نشده باشد هر دو 
undefined
بازگشت داده می شود
ورژن جدید را دریافت و بررسی کنید
