### ISSUE TITLE
مشکل با تول تیپ

### ISSUE THREAD

**Issue by AliEkrami** [Mds92/MD.BootstrapPersianDateTimePicker#205]
سلام وقتتون بخیر و تشکر بابت دیت پیکرتون.من اون فایل هایی ک لازم بود رو ضمیمه کردم و  اخرین نسخه جی کوپری و بوت استرپ روهم دانلود کردم وضمیمه کردم ولی موقعی ک میخوام از پلاگین استفاده کنم این خطا رو بهم میده....
Uncaught TypeError: n is not a constructor
    show tooltip.js:284
    _jQueryInterface popover.js:161
    jQuery 2
    _jQueryInterface popover.js:144
    jQuery 4
ممنون میشم جوابمو بدید ک مشکلم برطرف بشه

**Comment by Mds92** [comment]
سلام
خیلی خطا کلی هست
نمی تونم متوجه مشکل بشم

لطفا تو پوشه demo
برید، نمونه کدها اونجا هست

مطابق اونا عمل کنید
