### ISSUE TITLE
مشکل زمان در تاریخ میلادی

### ISSUE THREAD

**Issue by Mohammad3062** [Mds92/MD.BootstrapPersianDateTimePicker#206]
وقتی از فرمت 
dateFormat: 'yyyy-MM-dd hh:mm:ss'
استفاده می کنی در تاریخ میلادی مشکل پیدا می کنی،به این صورت که زمان به طور خودکار بعد از انتخاب تاریخ تنظیم نمی شود

**Comment by Mds92** [comment]
سلام
لطفا در مورد خطا بیشتر توضیح بدهید
اینکه میگید زمان به طور خودکار انتخاب نمیشه یعنی چی؟
من تو پوشه دمو فایل sample1
رو با فرمت شما تغییر دادم مشکلی ندیدم

**Comment by Mohammad3062** [comment]
[](url)
