### ISSUE TITLE
مشکل در نمایش زمان در تاریخ میلادی

### ISSUE THREAD

**Issue by Mohammad3062** [Mds92/MD.BootstrapPersianDateTimePicker#207]
با سلام مجدد
فکر کنم کامنت قبلی پاک شده،مجبور شدم دوباره پیغام جدید بزارم.
براتون یک فیلم از مشکل می زارم تا بهتر متوجه بشوید که من چی میگم.

http://s12.picofile.com/file/8402368500/2020_07_09_9_43_20.mp4.html

**Comment by Mds92** [comment]
سلام
مشکل رو متوجه شدم
درست کردم
آخرین ورژن را دریافت کنید
