### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by Mohammad3062** [Mds92/MD.BootstrapPersianDateTimePicker#208]
سلام.من دارم از بوت استرپ نسخه 3.3.4 استفاده می کنم و امکان اپدیت هم ندارم.برای استفاده از این تقویم بنظرتون باید چکار کنم؟

**Comment by Mds92** [comment]
سلام
این ورژن بوت استرپ 3.0 هست
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/tree/master-bs3
البته ویژگی های ورژن 4 رو نداره و بروز رسانی اونو متوقف کردم

**Comment by Mohammad3062** [comment]
ممنون.
کاربرد این خصیصه چیه؟

data-mddatetimepicker="true"


در تاریخ جمعه ۱۰ ژوئیهٔ ۲۰۲۰،‏ ۰۵:۵۳ Mohammad Dayyan <
notifications@github.com> نوشت:

**Comment by Mds92** [comment]
این برای پیدا کردن دیت پیکر از طریق سی اس اس سلکتور هست

**Comment by Mohammad3062** [comment]
سلام.
event
هاش رو چجوری استفاده کنم؟

**Comment by Mds92** [comment]
سلام
اونت های این دیت پیکر همون اونت های پاپ آور بوت استرپ هست
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#events
https://getbootstrap.com/docs/4.5/components/popovers/#events

**Comment by Mohammad3062** [comment]
سلام.این ابزار روشی برای تبدیل تاریخ از میلادی به شمسی ارائه می دهد؟

**Comment by Mds92** [comment]
سلام
فعلا خیر
