### ISSUE TITLE
رویداد تغییر تاریخ در jquery

### ISSUE THREAD

**Issue by aliramir** [Mds92/MD.BootstrapPersianDateTimePicker#209]
توی jquery چه رویدادی بنویسم که وقتی تاریخ عوض شد عملی صورت بگیره؟

**Comment by Mds92** [comment]
سلام
انتخاب تاریخ را داخل یه تکس باکس دارید نشان میدید؟
روی change event
تکس باکسی که دارید توش تاریخ را نشان میدید یه هندلر رویداد بنویسید

**Comment by aliramir** [comment]
خیر توی خود دیت پیکر خودش نشون میدم و رویداد تغییر اصلا با سلکت تاریخ از تقویم اتفاقی نمی فته مگر اینکه دستی تاریخ را تایپ کنیم.

**Comment by Mds92** [comment]
تاریخ انتخاب شده را کجا ذخیره می کنید
روی اون هندلر تغییر بنویسید

**Comment by aliramir** [comment]
توی دیت پیکر خودش انتخاب میشه جایی دیگه ذخیره نمیشه ! 
دیت پیکر DatePicker 
!!
 که رویداد change در صورتی عمل میشه که دستی عدد بزنیم. !  !! !
مشکل من جی کوئری و اینکه چطوری ایونت بنویسم و چی را از کجا بگیرم نیست. 
مشکل اینه که ایونت چنج روی این datepicker در select عکس العمل نشون نمیده. ! میخواستم بدونم ایونت اختصاصی داره یا خیر!

**Comment by aliramir** [comment]
`<input asp-for="EndDate" type="text" id="EndDate" class="form-control" placeholder="" aria-label="persiandate"
                                                   aria-describedby="persiandate" required dir="ltr">`

`$("#EndDate").change(function () {.....{):`

این کد در صورتی که دستی تاریخ را تغییر بدم عمل می کنه ولی اگر از تقویم سلکت بشه عکس العملی نشون نمیده.
نمی دونم واضح گفتم یا خیر

**Comment by Mds92** [comment]
متوجه نمیشم 
تو این پلاگین دو تا آپشن زیر است
targetTextSelector: '#inputTextDate1',
targetDateSelector: '#inputHiddenDate1',
که حداقل باید دومی رو مقدار بدید
اگر اینا رو هم مقدار ندادید که صحیح کار نکردید
برای هندل کردن اونت هم از on استفاده کنید

https://api.jquery.com/on/

**Comment by aliramir** [comment]
targetDateSelector: '#inputHiddenDate1', چطور مقدار داده میشه؟

**Comment by Mds92** [comment]
لطفا فایل های داخل پوشه دمو را مشاهده کنید و فایل 
Readme
صفحه نخست پروژه را مطالعه نمائید
