### ISSUE TITLE
داشتن قابلیت برگرداندن تاریخ اصلی در زمان صدا زدن فرستادن فرم

### ISSUE THREAD

**Issue by sijav** [Mds92/MD.BootstrapPersianDateTimePicker#21]
با سلام و تشکر
خیلی خوب میشد اگه یه متدی وجود داشت که تاریخ انتخاب شده در حال حاظر به صورت تاریخ جاوا اسکریپت یا همون
DateTime
برگردانده میشد اینطوری دیگه نیازی به پارس کردن هم نبود
و حتی بعد میشه در زمان صدا زدن
val
مثل کامپوننت
InputMask
زمان اصلی رو برگردوند اینطوری حتی در زمان فرستادن فرم و سریالایز کردنش هم بدن نیاز به هیچ عملیاتی به تاریخ صحیح تبدیل شده و به سمت سرور میرفت و دیگه نیازی نبود داخل سرور رشته گرفته بشه و دوباره پارس بشه.

مرسی از این کار خیلی خوب 👍

**Comment by Mds92** [comment]
با سلام
این متد وجود دارد
دموهای گنجانده شده در سورس رو ببینید
اما برای پاسخ اینجا
برای گرفتن تاریخ از متد زیر استفاده کنید:
```
$('selectorString').MdPersianDateTimePicker('getDate');
```

**Comment by Mds92** [comment]
با سلام
این متد وجود دارد
دموهای گنجانده شده در سورس رو ببینید
اما برای پاسخ اینجا
برای گرفتن تاریخ از متد زیر استفاده کنید:
```
$('selectorString').MdPersianDateTimePicker('getDate');
```
