### ISSUE TITLE
How to disabe go Today button?

### ISSUE THREAD

**Issue by hamid80386** [Mds92/MD.BootstrapPersianDateTimePicker#210]
How to disable 'go today'? its not in options list.

چطور میتونیم دکمه امروز رو پنهان کنیم؟ تو لیست آپشن ها نیست.

**Comment by Mds92** [comment]
با تغییرات در فایل css میتونید اون رو مخفی کنید

**Comment by hamid80386** [comment]
کاش میومد جزء تنظیمات
