### ISSUE TITLE
rangeSelector

### ISSUE THREAD

**Issue by alimo2** [Mds92/MD.BootstrapPersianDateTimePicker#211]
Hi,
In range selector mode, when input field has default value e.g. **1399-01-01 - 1399-05-30**, second date part removed & only show first date part (e.g only 1399-01-01 ramains). I think MD.BootstrapPersianDateTimePicker remove every extra things except yyyy-MM-dd & don't knows it is ranged & format is **yyyy-MM-dd - yyyy-MM-dd**

**Comment by Mds92** [comment]
Hello,

> when input field has default value e.g. 1399-01-01 - 1399-05-30

You mean an already selected range?

>second date part removed & only show first date part

When? When second part removed,

Could you please send a sample code to me to find the bug better.

**Comment by alimo2** [comment]
When i select range & submit form & pass submitted range value to input box then  `MdPersianDateTimePicker()` fired & second part removed.
Just call `MdPersianDateTimePicker()` on textbox with ranged date as default value:

`<input id="i_am_range_date_picker" type="textbox" value="1399-01-01 - 1399-05-30">`
```

$('#i_am_range_date_picker').MdPersianDateTimePicker({
        targetTextSelector: '#i_am_range_date_picker',
        textFormat: 'yyyy-MM-dd',
        englishNumber: true,
        monthsToShow: [1, 1],
        rangeSelector: true
});
```

**Comment by Mds92** [comment]
Thanks for reporting.
Please get the latest version and use the following code:
```javascript

$('#i_am_range_date_picker').MdPersianDateTimePicker({
        targetTextSelector: '#i_am_range_date_picker',
        textFormat: 'yyyy-MM-dd',
        englishNumber: true,
        selectedRangeDate: [new Date(2020, 6, 20), new Date(2020, 7, 10)],
        monthsToShow: [1, 1],
        rangeSelector: true
});

```
You can see `RangeSelector` sample file in demo folder.

**Comment by alimo2** [comment]
I think jalali date convert also has problem; It converts today (2020/8/16) to (1399-06-26) while today is 1399-05-26!
`selectedRangeDate: [new Date(2020,8,16), new Date(2020,8,16)],` -> `1399-06-26 - 1399-06-26`

**Comment by alimo2** [comment]
When we use time stamp in Date object, it also convert to wrong jalali date:
`selectedRangeDate: [new Date(1597557361), new Date(1597557361)],` -> `1348-10-29 - 1348-10-29`

**Comment by Mds92** [comment]
Please read more about Date in javascript: `https://www.w3schools.com/jsref/jsref_getmonth.asp`
Month index start from 0

**Comment by alimo2** [comment]
Tnx for your response & nice date-picker

**Comment by vahidtakro** [comment]
dear Mohammad,
is it also possible to use this for Perfex CRM system? I've tried a lot, no success...
