### ISSUE TITLE
گزارش باگ: تبدیل اعداد فارسی در targetDateSelector

### ISSUE THREAD

**Issue by KAJOOSH** [Mds92/MD.BootstrapPersianDateTimePicker#213]
سلام
طی بررسی انجام شده در نگارش 3.9.0 در زمان تکمیل فیلد اصلی باتوجه به پارامتری که در targetDateSelector مشخص شده است، تاریخ میلادی با اعداد فارسی مشخص می کند.
در نگارش 3.8.0 این مشکل وجود نداشت.

باتشکر

**Comment by Mds92** [comment]
سلام
تشکر بابت گزارش باگ
لطفا آخرین ورژن را دریافت و بررسی نمائید

**Comment by KAJOOSH** [comment]
> سلام
> تشکر بابت گزارش باگ
> لطفا آخرین ورژن را دریافت و بررسی نمائید

سلام، نگارش 3.9.1 تست و بررسی شد و مورد برطرف شده است.
