### ISSUE TITLE
گزارش باگ: عدم تنظیم ساعت جاری در صورت فعال بودن enableTimePicker

### ISSUE THREAD

**Issue by KAJOOSH** [Mds92/MD.BootstrapPersianDateTimePicker#214]
سلام
در صورتی که پارامتر 
enableTimePicker
فعال باشد تا امکان تکمیل زمان نیز فراهم شود. در صورتی که قبلا تکست باکس تاریخ و زمان تکمیل شده باشد و پس از زدن دکمه ی امروز تا تاریخ و زمان جاری تنظیم شود در ابتدا ، تاریخ و زمان صحیح نمایش داده است اما پس از بستن پنجره فقط تاریخ آن تنظیم شده است و زمان همان قبلی می باشد.

تست شده در نگارش های: 3.8.0 - 3.9.0 - 3.9.1
باتشکر

**Comment by Mds92** [comment]
با سلام
ورژن 3.9.2 را دریافت و. بررسی نمایید

با تشکر

**Comment by KAJOOSH** [comment]
> با سلام
> ورژن 3.9.2 را دریافت و. بررسی نمایید
> 
> با تشکر

سلام
طی بررسی در نگارش 3.9.2 این مورد برطرف شده است.
سپاسگذارم
