### ISSUE TITLE
date time picker with default value for time picker

### ISSUE THREAD

**Issue by Mehran-Isapour** [Mds92/MD.BootstrapPersianDateTimePicker#215]
Hi!
Thank you for your very good program!
When the time picker is active, the value of the hour, minute and second is set to the now by default.
How can I set the default value of time to 00:00:00?
Thanks a lot.

**Comment by Mds92** [comment]
Hello, 
You can set DateTime by `setDate` method
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#functions

**Comment by Mehran-Isapour** [comment]
Thank you very much.
I tried it but I could not succeed.
I added " setDate: new Date().setHours(0,0,0,0) " to my js.

It's my html code:
```
  <div class="input-group">
          <div class="input-group-prepend">
              <span class="input-group-text cursor-pointer" id="date1">icon</span>
          </div>
          <input type="text" id="inputDate" class="form-control" placeholder="تاریخ و ساعت"
                 aria-label="date1" aria-describedby="date1" >
   </div>
```
and It's my js code:
```
<script type="text/javascript">
        $('#date1').MdPersianDateTimePicker({
            targetTextSelector: '#inputDate',
            enableTimePicker: true,
            dateFormat: 'yyyy-MM-dd HH:mm:ss',
            textFormat: 'yyyy-MM-dd HH:mm:ss',
            disableBeforeToday: 'true',
            setDate: new Date().setHours(0,0,0,0),
        });
</script>
````
Would you please tell me where I went wrong?

**Comment by Mehran-Isapour** [comment]
<div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text cursor-pointer" id="date1">Icon</span>
        </div>
        <input type="text" id="inputDate" class="form-control" placeholder="تاریخ و ساعت" aria-label="date1 "
               aria-describedby="date1" >
    </div>

**Comment by Mds92** [comment]
`setDate` is a method, not an option.
If you want to use an option you have to use `selectedDate`
```javascript
        $('#date1').MdPersianDateTimePicker({
            targetTextSelector: '#inputDate',
            targetDateSelector: '#inputHiddenDate',
            enableTimePicker: true,
            textFormat: 'yyyy-MM-dd HH:mm:ss',
            selectedDate: new Date(2020, 10, 4)
        });
```
