### ISSUE TITLE
گزارش باگ: عدم کارکرد calendarViewOnChange

### ISSUE THREAD

**Issue by KAJOOSH** [Mds92/MD.BootstrapPersianDateTimePicker#217]
سلام
احتراما تابع 
calendarViewOnChange
کار نمی کند
تست شده در نگارش: 3.9.2

**Comment by Mds92** [comment]
سلام
من بررسی کردم، مشکلی نبود
حتی تو فایل SamplesToDebug.html
هم اضافه کردم
میتونید ببینید

**Comment by CyberDepot** [comment]
سلام
منم تو نگارش 3.10.1 همین مشکل رو دارم

**Comment by CyberDepot** [comment]
اوکی متوجه شدم، شما برای اون دکمه های بالایی تقویم که ماه رو عوض می کنن رویداد گذاشتین
وقتی رو یه روز از تاریخ کلیک می کنیم رویدادی نذاشتین

**Comment by CyberDepot** [comment]
به نظرم بهتره یه initial value هم براش بزارین، من می خواستم تقویم خالی لود بشه یه بار ClearDate رو فراخوانی کردم

**Comment by Mds92** [comment]
سلام
در مقدار دهی اولیه آپشن 
selectedDate
همان initialValue
هست که میتونید با آبجکت Date
مقدار دهیش کنید

**Comment by Mds92** [comment]
در مورد اونت کلیک روی روزها به زودی اعمال و پابلیش می شود
calendarViewOnChange
وقتی رخ میدهد که ویو دیت پیکر تغییر می کند
