### ISSUE TITLE
Html - tag option

### ISSUE THREAD

**Issue by MajidSafari** [Mds92/MD.BootstrapPersianDateTimePicker#218]
سلام در این ورژن آخر 

data-MdDateTimePicker="true" data-targetselector="#EndDate" data-trigger="click" data-name="EndDate"

از این نوع آپشن  نمیشه استفاده کرد ؟

**Comment by Mds92** [comment]
سلام
خیر، به دلایل perfomance
این ویژگی غیر فعال شده است

**Comment by MajidSafari** [comment]
سلام مرسی از پاسخ 

` setting = $.extend({
                        englishNumber: false,
                        placement: 'bottom',
                        trigger: 'click',
                        enableTimePicker: false,
                        targetTextSelector: '',
                        targetDateSelector: '',
                        toDate: false,
                        fromDate: false,
                        groupId: '',
                        disabled: false,
                        textFormat: '',
                        dateFormat: '',
                        isGregorian: false,
                        inLine: false,
                        selectedDate: undefined,
                        selectedDateToShow: new Date(),
                        monthsToShow: [0, 0],
                        yearOffset: 15,
                        holiDays: [],
                        disabledDates: [],
                        disabledDays: [],
                        specialDates: [],
                        disableBeforeToday: false,
                        disableAfterToday: false,
                        disableBeforeDate: undefined,
                        disableAfterDate: undefined,
                        rangeSelector: false,
                        rangeSelectorStartDate: undefined,
                        rangeSelectorEndDate: undefined,
                        modalMode: false
                    }, options, $(this).data());`


اما کافیبه $(this).data() ته extend اضافه شه .
