### ISSUE TITLE
نمایش فقط سال وماه

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#219]
با سلام 
تنظیماتی نداره که زمانی که روی تکس باکس کلیک میشه پنل تقویم فقط ماه وسال نمایش داده بشه روز نمایش داده نشه

**Comment by Mds92** [comment]
سلام
خیر هنوز چنین قابلیتی وجود ندارد
برای این موارد بهتر هست از 
DropDown ها
استفاده نمائید.
