### ISSUE TITLE
قابلیت ست کردن دوباره و آنست کردن و تغییر گزینه ها Set and Unset

### ISSUE THREAD

**Issue by sijav** [Mds92/MD.BootstrapPersianDateTimePicker#22]
با سلام دوباره
این پلاگین اگه بشه دوباره با فراخانی جاوا اسکریپت دوباره ست بشه و تغییر حالت بده خیلی کمک میکنه
و از همه مهمتر باید راحی وجود داشته باشه که پلاگین ست شده روی المنتی رو بشه آنست کرد و دیگه کار نکنه. این قابلیت در قسمت های خاصی که ما میخوایم المنتی رو غیب یا غیر فعال کنیم خیلی به درد میخوره.

مرسی از توجه شما

**Comment by Mds92** [comment]
سلام
این متدها وجود دارند
برای ست کردن مقدار 
```
$('selectorString').MdPersianDateTimePicker('setValue', newValue);
```
دقت کنید نیاز نیست حتما از این متد استفاده کنید، خودتون میتونید مقدار 
target
رو با هر روشی آپدیت کنید، برای غیر فعال کردن پلاگین هم متد زیر رو استفاده کنید

```
$('selector').MdPersianDateTimePicker('disable', true);

```
