### ISSUE TITLE
save targetDateSelector value in Jalali

### ISSUE THREAD

**Issue by Mehran-Isapour** [Mds92/MD.BootstrapPersianDateTimePicker#221]
Hello!
I use the Jalali datetime in Back-end. When I checked the value of the hidden input that I specified for `targetDateSelector` (ie #inputDateHidden), I found that it was saved in Gregorian.
`targetDateSelector: '#inputDateHidden',`
Is there a way to save it in Jalali?

**Comment by Mds92** [comment]
Hello,
The best way to send datetime to backend is the way you mention it.
If you want to send Persian date to backend use `targetTextSelector`.
ie:
```javascript
targetTextSelector: '#inputTextDate1''
```
and at the backend use `inputTextDate1` value.

**Comment by Mehran-Isapour** [comment]
Thanks a lot!

**Comment by Mehran-Isapour** [comment]
Thanks a lot!
Is it possible to assign two Input to the `targetTextSelector`?
A human readable field and a hidden field for sending information to back-end.

Or, is there a way to put the code of the `targetTextSelector` function in `targetDateSelector` function in my source?

**Comment by Mehran-Isapour** [comment]
Thanks a lot!
Is it possible to assign two Input to the `targetTextSelector`?
A human readable field and a hidden field for sending information to back-end.

Or, is there a way to put the code of the `targetTextSelector` function in `targetDateSelector` function in my source, so that I can use the Jalali date in the `targetDateSelector` as well?

**Comment by Mds92** [comment]
it's a css selector. I didn't test it yet but I think it works like follows:
```
targetTextSelector: '#ID1,#ID2,.cssClass1'
```

**Comment by Mehran-Isapour** [comment]
But it seems that with this code,
The text format of both fields is the same. I meant assigning two fields to `targetTextSelector` while the hidden field text format is different from the other field

**Comment by Mds92** [comment]
>  I meant assigning two fields to targetTextSelector while the hidden field text format is different from the other field

It's not possible right now

**Comment by Mds92** [comment]
>  I meant assigning two fields to targetTextSelector while the hidden field text format is different from the other field
It's not possible right now

**Comment by Mehran-Isapour** [comment]
OK, Thanks a lot.
