### ISSUE TITLE
آپشنال شدن targetDateSelector و targetTextSelector

### ISSUE THREAD

**Issue by AliMahmodi** [Mds92/MD.BootstrapPersianDateTimePicker#222]
با سلام و سپاس از اشتراک گذاری این کتابخانه 
در صورت امکان همانند کتابخانه اصلی این امکان را فراهم کنید تا بدون نیاز به تعریف
 targetDateSelector و targetTextSelector 
در موقع استفاده بطور پیشفرض همان المانی که روی آن کلیک شده دارای مقدار 
targetTextSelector
  شود

سپاس

**Comment by Mds92** [comment]
سلام

> در صورت امکان همانند کتابخانه اصلی این امکان را فراهم کنید تا بدون نیاز به تعریف

کتابخانه اصلیش رو متوجه نشدم، این پلاگین کپی از پلاگین دیگری نیست

> در موقع استفاده بطور پیشفرض همان المانی که روی آن کلیک شده دارای مقدار
targetTextSelector
شود

در این پلاگین این امکان هست که این پلاگین را روی المانی فعال کنید که ارتباطی با 
targetTextSelector یا targetDateSelector 
ندارد
برای همین هندل کردن این موضوع کمی سخت می شود
