### ISSUE TITLE
تغییر تاریخ شروع در نمایش دیت پیکر

### ISSUE THREAD

**Issue by nimakazemi** [Mds92/MD.BootstrapPersianDateTimePicker#223]
سلام خسته نباشید 
میخواستم تاریخ شروع دیت پیکر 1 سال به عقب بره ... ولی توی اینپوت ها چیزی ننویسه ... 
یعنی نمیخوام selectedDate رو مقدار بدم 
میخوام یه کاری کنم که شروع تاریخش از یک سال پیش باشه چون کاربر باید از تاریخ تا تاریخ رو وارد که و معمولا تاریخ یک سال قبل و امروز رو میخواد
ممنون میشم راهنمایی کنین

**Comment by Mds92** [comment]
سلام
هنوز چنین قابلیتی روی این پلاگین نداریم
اما در برنامه اضافه کردن ویژگی ها قرار میگیره
تشکر

**Comment by Mds92** [comment]
آپشنی به نام 
`selectedDateToShow`
اضافه شده است که تاریخی که میخواهید تقویم از آن شروع به کار کند، هست
دقت شود پس از انتخاب تاریخ این تقویم از تاریخ انتخاب شده باز می شود
با تشکر
