### ISSUE TITLE
This package has been deprecated as it is legacy and is no longer maintained.

### ISSUE THREAD

**Issue by Mirsoltan** [Mds92/MD.BootstrapPersianDateTimePicker#224]
سلام
پلاگین خیلی جالبی نوشته اید واقعا دست مریزاد
این پیام چرا توی nuget دیده میشه
و توی پروژه زمان بروز کردن آنها میخواد که این پلاگین رو حذف کنه
آیا امکان اضافه کردن تقویم رسمی و مناسبتها هم وجود داره؟

**Comment by Mds92** [comment]
سلام
این پکیج دیگه توی نوگت بروز نمیشه و اونجا ورژن خیلی قدیمی هست که منقضی شده است.
یا از npm 
بگیرید یا از همینجا دانلود کنید.
قسمت readme 
یا همون صفحه اول رو بخونید تا دقیق متوجه نحوه نصب و راه اندازی بشید

> آیا امکان اضافه کردن تقویم رسمی و مناسبتها هم وجود داره؟

بله. قسمت زیر را مطالعه کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options
دو آپشن زیر شاید کارتون رو راه بندازه
`holiDays`, `specialDates`
