### ISSUE TITLE
استفاده برای WPF

### ISSUE THREAD

**Issue by Rasool65** [Mds92/MD.BootstrapPersianDateTimePicker#225]
سلام میشه از این برای برنامه های تحت ویندوز WPF هم استفاده کرد؟ اگر نمیشه شما کنترلری رو میشناسید که مثل این باشه ؟

**Comment by Mds92** [comment]
سلام
خیر برای تحت ویندوز با دات نت نیست
اما اگر برای ایجاد برنامه تحت ویندوز از چیزی مثل الکترون استفاده میکنید میتونید از این تقویم استفاده کنید
wpf
 خیلی وقت هست کار نمیکنم و اطلاع ندارم
