### ISSUE TITLE
خطا هنگام استفاده از am/pm ق.ظ/ب.ظ

### ISSUE THREAD

**Issue by armoonia** [Mds92/MD.BootstrapPersianDateTimePicker#226]
در تابع parsePersianDateTime در قسمت

    if (persianDateTimeInString.indexOf('ق.ظ') > -1)
        amPmEnum = amPmEnum.AM;
    else if (persianDateTimeInString.indexOf('ب.ظ') > -1)
        amPmEnum = amPmEnum.PM;

به اشتباه ست شده و باید 
    if (persianDateTimeInString.indexOf('ق.ظ') > -1)
        amPmEnum = amPm.AM;
    else if (persianDateTimeInString.indexOf('ب.ظ') > -1)
        amPmEnum = amPm.PM;
باشد
همچنین 
    switch (amPmEnum) {
        case amPmEnum.PM:
        if (numericHour < 12)
          numericHour = numericHour + 12;
        break;
        case amPmEnum.AM:
        case amPmEnum.None:
        break;
    }
باید
    switch (amPmEnum) {
        case amPm.PM:
        if (numericHour < 12)
          numericHour = numericHour + 12;
        break;
        case amPm.AM:
        case amPm.None:
        break;
    }
باشد

**Comment by Mds92** [comment]
با سلام 
تشکر بابت گزارش خطا
فقط از این به بعد لطفا کد ها را در بلاک مخصوص کد قرار بدید 
در ورژن جدید خطاها برطرف گردید

**Comment by armoonia** [comment]
سلام، مرسی از راهنماییتون
