### ISSUE TITLE
تغییر دستی تاریخ شمسی تکست باکس و تریگر تبدیل به میلادی در فیلد مخفی

### ISSUE THREAD

**Issue by dashti011** [Mds92/MD.BootstrapPersianDateTimePicker#227]
با سلام و احترام و تشکر بابت برنامه عالیتون
سوالی داشتم اینه که من یه input دارم که تاریخ توسط تقویم به صورت فارسی نمایش داده میشه و یه  input مخفی هم  برای (targetDateSelector ) دارم که معادل میلادی در اون ثبت میشه.
مثلا من تاریخ 27-12-1399 ا انتخاب میکن و تا اینجا مشکلی نیست، حالا میام بدون باز کردن مجدد تقویم ، مقدارفیلد (targetTextSelector) را تغییر میدم مثلا به 28-12-1399 اما فیلد مخفی مربوط به targetDateSelector بروز رسانی نمیشه.
راهی برای اون هست ؟

**Comment by Mds92** [comment]
سلام، خواهش میکنم
چطور مقدار فیلد تاریخ رو تغییر می دهید
دستی تغییر می دهید یا توسط برنامه؟
مثلا با جاوا اسکریپت تغییر می دهید؟

**Comment by dashti011** [comment]
دستی خودم تغییر میدم یا حتی برخی مواقع کلا Delete هم میکنم ولی اون فیلد مخفی اپدیت نمیشه

**Comment by Mds92** [comment]
من دوباره آخرین ورژن رو تست کردم
فایل Sample1 در پوشه DEMO
مشکلی از این بابت نبود
ممکن هست کدهای دیگر در رفتار تقویم تاثیر گذاشته اند
لطفا مطمئن شید که آخرین ورژن رو دارید و فایل sample1
را بررسی کنید
اگر اونجا هم مشکلی بود بگید

**Comment by dashti011** [comment]
ممنون که وقت گذاشتین ، بررسی میکنم
