### ISSUE TITLE
مشکل با تاریخ قبلی

### ISSUE THREAD

**Issue by hmbmirzaei** [Mds92/MD.BootstrapPersianDateTimePicker#228]
وقتی فوکوس روی فیلد اتفاق میفته و از قبل اطلاعاتی در فیلد هست، خطای زیر ظاهر میشه:
Invalid Jalali year -100721

**Comment by Mds92** [comment]
سلام
با دریافت آخرین ورژن دوباره بررسی شود
لطفا فایل readme
مطالعه شود و مطابق آن عمل شود
