### ISSUE TITLE
مشکل با تاریخ جدید

### ISSUE THREAD

**Issue by hmbmirzaei** [Mds92/MD.BootstrapPersianDateTimePicker#229]
وقتی فوکوس روی یک فیلد خالی اتفاق میقته و تاریخ انتخاب میشه، تاریخ میلادی ثبت میشه. در صورتی که میبایست تاریخ شمسی ثبت بشه

**Comment by Mds92** [comment]
سلام
اینکه میگید تاریخ میلادی ثبت میشه یعنی چی
کجا ثبت میشه
تو فیلد `targetTextSelector`
میلادی قرار میگیره یا تو فیلد `targetDateSelector`

**Comment by hmbmirzaei** [comment]
سلام
اولا کارتون بسیار زیباست
دوما
من اینجوری استفاده میکردم
[image: image.png]

ولی

دو مشکل وجود دارد. یکی اینکه تاریخ میلادی ثبت میشه. دوم اینکه اگه از قبل
اطلاعاتی در فیلد موجود باشه، خطا میده. که در issue ها گذاشتم.
09121908378

**Comment by hmbmirzaei** [comment]
واتس آپ هم میتونید تماس بگیرید

**Comment by Mds92** [comment]
برای من عکسی لود نشد
لطفا مطمئن شید که آخرین ورژن رو دارید
بعد مطابق توضیحات فایل
readme
عمل کنید
نمونه ها در پوشه demo 
نیز هست

**Comment by hmbmirzaei** [comment]
$(l).MdPersianDateTimePicker({    targetDateSelector: l,
targetTextSelector: l});

**Comment by Mds92** [comment]
توضیحات فایل 
readme
را مطالعه نمایید 
تا طرز صحیح استفاده از پلاگین را متوجه شوید
