### ISSUE TITLE
مشکل در placement

### ISSUE THREAD

**Issue by dashti011** [Mds92/MD.BootstrapPersianDateTimePicker#23]
سلام ، ممنون از  کد عالی شما و تشکر از تلاشتون، من از تقویم شما در برنامه
 asp.nwt mvc  
نسخه 5   استفاده کردم و نسخه
 bootstrapt  و  jquery  هم به اخرین نسخه ارتقا دادم .
مشکلی در استفاده از کد شما دارم و این که  در صورتی که یکی یا بیشتر تقویم در صفحه باشه همیشه تقویم در گوشه سمت راست صفحه باز میشه
حتی اگر چند تا تقویم باشه منو تقویم بعد از کلیک در جای مناسب نشون داده نمیشه
چند عکس از این موضوع ضمیمه کردم .
باتشکر از توجه شما!
![snap9](https://cloud.githubusercontent.com/assets/16411644/18947315/7426cbbe-863f-11e6-8b2e-db67cbd6cc6a.png)
![snap10](https://cloud.githubusercontent.com/assets/16411644/18947316/742989a8-863f-11e6-9d17-3c880a9e2ec7.png)
![snap11](https://cloud.githubusercontent.com/assets/16411644/18947317/742df632-863f-11e6-87de-f6b0c056172c.png)

**Comment by Mds92** [comment]
سلام
شما بوت استرپ رو چطور راست به چپ کردید، احتمال میدم مشکلتون همین باشه
از شکل کنترل هاتون به نظرم درست بوت استرپ رو راست به چپ نکردید

**Comment by dashti011** [comment]
بله درست بود مشکل از راست چین بوت استرپ بود
