### ISSUE TITLE
مشکل در لود شدن کامل تولتیپ

### ISSUE THREAD

**Issue by ermya** [Mds92/MD.BootstrapPersianDateTimePicker#231]
درود بر شما
چه جوری میشه فهمید این مشکل عدم نمایش بخاطر چی هست ؟
![186](https://user-images.githubusercontent.com/17262112/112891297-3a053200-90ed-11eb-80b9-cfb6c1f8d774.png)

**Comment by Mds92** [comment]
درود
باید کنسول مرورگر را بررسی نمائید
ببینید خطایی دریافت کرده اید یا خیر
همچنین ممکن هست اشتباه در قرار دادن
CssSelector
باشد
