### ISSUE TITLE
selected date event

### ISSUE THREAD

**Issue by arbabi2010** [Mds92/MD.BootstrapPersianDateTimePicker#232]
Hi , I need an event when i select a date from datePicker.
how can i do this?
i don't want to use `$('#id'),on('change') ` because this event work when i use `$('#id').MdPersianDateTimePicker('setDate', new Date(2018, 11, 12));`
just event when i click on a date from datepicker

**Comment by Mds92** [comment]
Hello
Do you look at event section of readme file?
`https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#events`

**Comment by arbabi2010** [comment]
سلام . بذارید کامل توضیح بدم در مورد همین رویدادها
من از این رویدادها استفاده کردم. من میخام وقتی روی یک تاریخی کلیک شد یه اتفاقی بیافته. اگر روی تابع 
change input
نوشته بشه ممکنه من با استفاده از یک تابع جی کوئری هم بخام مقدار این اینپوت رو تغییر بدم و نباید عملیات انجام بشه. 
وقتی از این رویداد های گفته شده در داکیومنت استفاده کنم هیچ مفهومی برای زمانی که روی یک تاریخ خاص کلیک کنم نداره و فقط برای نمایش و عدم نمایش 
popover 
هست. ممکنه من پیکر زمان رو باز و بسته بکنم ولی عملیاتی انجام ندم!

**Comment by Mds92** [comment]
آخرین ورژن دریافت شود و فایل readme
مطالعه شود
رویداد onDayClick
اضافه شد
