### ISSUE TITLE
Time Selector Not Working Can Not Change Time

### ISSUE THREAD

**Issue by nrnavid** [Mds92/MD.BootstrapPersianDateTimePicker#234]
i can not change any part of time inside the date time picker time is not editable.

**Comment by Mds92** [comment]
Hello,
I couldn't see the problem.
Please see demo files

**Comment by ghost** [comment]
@Mds92 He's right. Inputs are not editable when datepicker is in a modal. (not in modal mode). Removing tabndex="-1" fixes the issue.
