### ISSUE TITLE
مشکل مقدار پیش فرض در موبایل

### ISSUE THREAD

**Issue by farshidpg** [Mds92/MD.BootstrapPersianDateTimePicker#235]
اگر فیلد ما مقدار پیش فرض ( گرفته شده از میلادی ) داشته باشه و به فرمت درست شمسی هم تبدیل بشه و به فیلد مقدار دهی اولیه بشه روی موبایل دیت پیکر باز نمیشه و امکان انتخاب تاریخ وجود نداره .

بنده برای تست تاریخ رو تبدیل نشده به شمسی هم  به فیلد دادم اما باز روی موبایل همچنان همین مشکل  رو داره 

جالب اینجاست که توی نسخه وب تاریخ رو حتی اگر تبدیل نشده به شمسی به فیلد بدیم اتومات بعد از اجرا شدن پلاگین تبدیل میشه و نیازی به تبدیل از سمت بک اند نیست  اما روی موبایل اگر تاریخ رو تبدیل نشده بدیم  به صورت اتوماتیک تبدیل نمیشه 
بنا بر تست این دو حالت امکان مقدار دهی اولیه در لود صفحه از سمت سرور یا پارامتر ها در موبایل به فیلد نیست 

من با آخرین ورژن پلاگین و آخرین ورژن  آی او اس به این مشکل خوردم ، کسی همچین مشکلی داره ؟

**Comment by Mds92** [comment]
> اگر فیلد ما مقدار پیش فرض ( گرفته شده از میلادی ) داشته باشه و به فرمت درست شمسی هم تبدیل بشه و به فیلد مقدار دهی اولیه بشه روی موبایل دیت پیکر باز نمیشه و امکان انتخاب تاریخ وجود نداره .

اینکه گفته اید به فیلد داده اید یعنی چی دقیقا؟
یعنی به فیلد مربوط به
targetTextSelector
مقدار داده اید یا فیلد 
targetDateSelector

اگر خطایی هم در کنسول هست لطفا ارسال کنید

> جالب اینجاست که توی نسخه وب تاریخ رو حتی اگر تبدیل نشده به شمسی به فیلد بدیم اتومات بعد از اجرا شدن پلاگین تبدیل میشه و نیازی به تبدیل از سمت بک اند نیست اما روی موبایل اگر تاریخ رو تبدیل نشده بدیم به صورت اتوماتیک تبدیل نمیشه

کلا نیازی به تبدیل تاریخ نیست
فقط کافی هست مقدار میلادی را درفیلد مربوط به 
targetDateSelector
قرار بدید
خود دیت پیکر اون رو به شمسی تبدیل و در فیلد 
targetTextSelector
نمایش میده

**Comment by farshidpg** [comment]
ممنونم از  پیگیری سریعتون 

منظورم از فیلد 
targetTextSelector
هستش 

بنده 
targetDateSelector
رو هیدن کردم و فقط برای ارسال دیتا به سرور از اون استفاده میکنم .

این نمونه کد HTML

**targetTextSelector:**
`<input type="text" value="{{ @request('date_start') }}" placeholder="از تاریخ و ساعت" class="form-control" id="start_date_text" autocomplete="off">`

**targetDateSelector :** 
`<input type="text" name="date_start" value="{{ @request('date_start') }}" placeholder="از تاریخ و ساعت" autocomplete="off" class="form-control d-none" id="start_date_date">`

این هم کد مربوط به فراخوانی پلاگین در


    $('#start_date_text').MdPersianDateTimePicker({
        trigger:'click',
        targetTextSelector: '#start_date_text',
        targetDateSelector: '#start_date_date',
        textFormat:'yyyy/MM/dd HH:mm',
        dateFormat:'yyyy-MM-dd HH:mm',
        englishNumber:true,
        inLine: false,
        enableTimePicker: true,
        fromDate: true,
        groupId: 'ads-date_start_end-range'
      });

    $('#end_date_text').MdPersianDateTimePicker({ 
      trigger:'click',
      targetTextSelector: '#end_date_text',
      targetDateSelector: '#end_date_date',
      textFormat:'yyyy/MM/dd HH:mm',
      dateFormat:'yyyy-MM-dd HH:mm',
      englishNumber:true,
      inLine: false,
      enableTimePicker: true,
      toDate: true,
      groupId: 'ads-date_start_end-range'
    });


توی   دسکتاپ هیچ مشکلی نیست ، اما توی موبایل وقتی مقدار اولیه 


    value="{{ @request('date_start') }}"


وجود داره  پلاگین فراخوانی نمیشه ظاهرا 

با بروزر استک تونستم تست کنم روی موبایل اما توی کنسول هیچ ارور یا خطایی وجود  نداره 

این مورد که میگم پلاگین فراخوانی نمیشه به این خاظره که اصلا تاریخ تبدیل نمیشه و همون فرمت میلادی میمونه بنابراین میشه حدس زد که پلاگین فراخوانی نمیشه وگرنه تبدیل رو انجام میداد

این موضوع باعث شده که توی موبایل در صورتی که فیلد تاریخ از قبل تکمیل شده باشه دیگه دیت پیکر باز نشه

**Comment by Mds92** [comment]
پس بنظرم باید بررسی کنید که چرا پلاگین فراخوانی نمیشه
چون در صورت مقداردهی اولیه یا باید خطا دریافت کنید یا باید نتیجه کار به نحوی معلوم بشه

**Comment by farshidpg** [comment]
ممنونم از حال تستم نتیجه رو همینجا اعلام میکنم

**Comment by farshidpg** [comment]
بنده یک پروژه خام با استفاده از دمو  پروژه در گیت هاب ایجاد کردم و  حالتی که توضیح دادم رو تست کردم ، 

روی موبایل مشکلی وجود دارد

اگر  ما دو فیلد به صورت زیر داشته باشید 

    
    <input type="text" id="inputDate10" value="2021-05-17 00:45:00"  class="form-control" placeholder="">
    <input type="text" id="inputDate11" value="2021-05-17 00:45:00"  class="form-control" placeholder="">


سپس پلاگین را به این صورت فراخوانی کنیم

    $('#inputDate10').MdPersianDateTimePicker({
         targetTextSelector: '#inputDate10',
         targetDateSelector: '#inputDate11',
         inLine: false,
         textFormat:'yyyy/MM/dd HH:mm',
         dateFormat:'yyyy-MM-dd HH:mm',
         enableTimePicker: true,
    });


نتیجه بدون مشکل در مروگر دسکتاپ اجرا میشود و با انتخاب تاریخ جدید دیت پیکر باز میشه و امکان انتخاب تاریخ وجود دارد 


اما در مروگر موبایل دیت پیکر فراخوانی نمیشه 

یک حالت دیگه هم تست کردم  به نمونه زیر دقت کنید لطفا

    <input type="text" id="inputDate10"  class="form-control" placeholder="">
    <input type="text" id="inputDate11" value="2021-05-17 00:45:00"  class="form-control" placeholder="">

با توجه به قابلیت پلاگین و توضیحات شما ، کد بالا هم به درستی کار میکنه و مقدار فارسی هم محاسبه و در فیلد مربوط به تکست قرار میده 
این هم روی دسکتاپ  بدون مشکل کار میکنه اما روی موبایل دقیقا مثل کد اول اجرا نمیشه و. حتی تبدیل تاریخ هم انجام نمیده .


این امکان رو من برای زمانی  لازم دارم که کاربر در فیلتر جستجو تاریخی رو انتخاب میکنه و سرچ رو انجام میده و باید تاریخ انتخاب شده رو در صفحه جدید لود شده از پارامتر ها دریافت کنم و در مقدار فیلد تاریخ قرار بدم  که خوشبختانه روی دسکتاپ مشکلی نداره اما روی  مروگر موبایل توضیحات رو گفتم خدمتتون

**Comment by farshidpg** [comment]
من احتمال میدم این مشکل  مربوط این قسمت پلاگین  هستش

`jquery.md.bootstrap.datetimepicker.js`
`line : 2025`

    if (setting.targetDateSelector) {
          var targetValue = $(setting.targetDateSelector).val();
          if (targetValue) {
            setting.selectedDate = new Date(Date.parse(targetValue));
            setting.selectedDateToShow = getClonedDate(setting.selectedDate);
          }
        } else if (setting.targetTextSelector) {
          var textValue = $(setting.targetTextSelector).val();
          if (textValue) {
            setting.selectedDate = parseDateTime(textValue, setting);
            setting.selectedDateToShow = getClonedDate(setting.selectedDate);
       }


پیرو این مشکل که قبلا مشکل مشابه ای در قسمتی از یک تم خارجی انگولار داشتم لینک زیر رو برسی بفرمایید

https://stackoverflow.com/questions/13363673/javascript-date-is-invalid-on-ios

**Comment by farshidpg** [comment]
پیرو این مشکل که قبلا مشکل مشابه ای در انگولار داشتم لینک زیر رو برسی بفرمایید

https://stackoverflow.com/questions/13363673/javascript-date-is-invalid-on-ios

**Comment by farshidpg** [comment]
با تست کردن  الرت گرفتن روی موبایل در تیکه کد زیر

`jquery.md.bootstrap.datetimepicker.js`
`line : 2025`

    if (setting.targetDateSelector) {
          var targetValue = $(setting.targetDateSelector).val();
          if (targetValue) {
            setting.selectedDate = new Date(Date.parse(targetValue));
            setting.selectedDateToShow = getClonedDate(setting.selectedDate);
            --->alert(getClonedDate(setting.selectedDate));
          }
        } else if (setting.targetTextSelector) {
          var textValue = $(setting.targetTextSelector).val();
          if (textValue) {
            setting.selectedDate = parseDateTime(textValue, setting);
            setting.selectedDateToShow = getClonedDate(setting.selectedDate);
           --->alert(getClonedDate(setting.selectedDate));
       }


با پیغام 

invalid Date 

رو به شدم

و با این تغییر مشکل بر طرف شد

    setting.selectedDate = new Date(Date.parse(targetValue.replace(' ', 'T')));

**Comment by farshidpg** [comment]
این کد بهتر و کامل تر که مشکل رو کاملا بر طرف میکنه فقط یک شرط اضافه کردم و مقدار
setting.selectedDateToShow
در صورت اجرا شدن شرط اورراید کردم 

اگر شما راه حل بهتری دارید یا ادیت بیشتری لازم داره لطفا انجام بدید و به کتابخانه اضافه کنید 

ممنونم از پیگیریت 👍 

`jquery.md.bootstrap.datetimepicker.js`
`line : 2025`

    if (targetValue) {

            setting.selectedDate = new Date(Date.parse(targetValue));
            
            // In case its IOS, parse the fulldate parts and re-create the date object.
            if(Number.isNaN(setting.selectedDate.getMonth())) {
              var arr = targetValue.split(/[- :]/);
              setting.selectedDate = new Date(arr[0], arr[1]-1, arr[2], arr[3], arr[4], arr[5]);
            }
            setting.selectedDateToShow = getClonedDate(setting.selectedDate);
          }


این کد فقط با فرمتی سازگاره که جدا کننده تاریخ - باشه و برای ساعت از : استفاده شده باشه ، در صورت تمایل میتونید با فرمت ورودی کاربر ترکیبش کنید و شرش رو برای همیشه بکنید

**Comment by Mds92** [comment]
سلامی دوباره و تشکر بابت پیشنهاد
کد بهبود داده شد
آخرین ورژن دریافت شود
