### ISSUE TITLE
فواصل مضرب دار برای انتخاب دقیقه

### ISSUE THREAD

**Issue by arsalanses** [Mds92/MD.BootstrapPersianDateTimePicker#236]
سلام

میخوام ورودی زمان فقط اجازه انتخاب زمان هایی با فواصل مضرب 5 بده

متغییری مثل
stepping
میتونه اینکار رو انجام بده؟

مثال:
https://stackoverflow.com/questions/39538786/how-to-make-bootstrap-datetimepicker-to-show-time-in-15-minutes-interval

**Comment by Mds92** [comment]
سلام
خیر 
چنین قابلیتی وجود نداره

**Comment by farshidpg** [comment]
این مورد رو بنده هم نیاز دارم  و مجبور شدم پلاگین دیگه ای رو برای  انتخاب ساعت به صورت جدا استفاده کنم

این پلاگین نسبتا خوبی بود اما اگر به همین پلاگین اضافه بشه خیلی خوبه 

http://senthilraj.github.io/TimePicki/index.html
