### ISSUE TITLE
مشکل درج اشتباه تاریخ در ورودی دیگر

### ISSUE THREAD

**Issue by sobhanmoghiseh** [Mds92/MD.BootstrapPersianDateTimePicker#237]
سلام
زمانی که 2 بازه زمانی در فرم قرار میدم ، اکثر مواقع پس از انتخاب تاریخ به جای اینکه مقدار اون در اینپوت خودش قرار بگیره ، در اون یکی قرار میگیره ! یعنی تاریخ شروع رو میزنم و مقدار میگیره اما بعدش که تاریخ پایان رو میزنم مقدار اون رو داخل اینپوت تاریخ شروع نمایش میده و مقدار تاریخ پایان خالی هست !

![Capture](https://user-images.githubusercontent.com/37009956/120095115-50edf200-c139-11eb-9857-427a8f8b9a23.PNG)

کد های به کار رفته :

```
    $('#enter_date').MdPersianDateTimePicker({
        targetTextSelector: '#enter_date_1',
        targetDateSelector: '#enter_date_2',
        fromDate:true,
        groupId:'#enter_date',
        modalMode:true
    });   


    $('#exit_date').MdPersianDateTimePicker({
        targetTextSelector: '#exit_date_1',
        targetDateSelector: '#exit_date_2',
        toDate:true,
        groupId:'#enter_date',
        modalMode:true
    });
```

**Comment by Mds92** [comment]
سلام
آیا میتونید یه فایل مشابه دمو برای بررسی بهتر مشکل ارائه کنید
یعنی یه فایل که فقط دیت پیکر توش باشه و خطا بازسازی شده و قابل مشاهده باشه

**Comment by sobhanmoghiseh** [comment]
خدمت شما ، من از اشکال فیلم هم ارسال کردم .

[file.zip](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/files/6565922/file.zip)

**Comment by Mds92** [comment]
من کد ارسالی تون رو دیدم
فایل HTML
درست ایجاد نشده !!!
تگ بادی و HTML بسته نشده
من تگ ها رو درست کردم، درست شد
بازم بیشتر بررسی میکنم ببینم مشکل چیز دیگری نباشه

**Comment by Mds92** [comment]
مشکل را پیدا کردم
حل شد
لطفا آخرین ورژن را دریافت و بررسی نمائید

**Comment by sobhanmoghiseh** [comment]
سپاس ، مشکل برطرف شد .
