### ISSUE TITLE
پشتیبانی bootstrap5

### ISSUE THREAD

**Issue by mnjadidi** [Mds92/MD.BootstrapPersianDateTimePicker#238]
سلام. آیا برنامه ای برای توسعه روی بوت استرپ ۵ دارید. چون سوال های مربوط به آن را بسته بودید.
لطفا راهنمایی بفرمایید.

**Comment by Mds92** [comment]
سلام
بله حتما این کتابخانه به بوت استرپ 5 ارتقاء پیدا خواهد کرد
اما با توجه به حذف جی کوئری از بوت استرپ 5 نیاز به تغییرات بیشتری است
