### ISSUE TITLE
Problem with Bootstrap v5.x

### ISSUE THREAD

**Issue by sajadafaghiy** [Mds92/MD.BootstrapPersianDateTimePicker#239]
Latest release of the library (v3.11.5) has conflict with Bootstrap v5.x.
It seems the problem occurs because of popover built-in Bootstrap JavaScript file.
The thrown exception is: "**Bootstrap doesn't allow more than one instance per element. Bound instance: bs.popover.**"

Thanks for your attentions.

**Comment by Mds92** [comment]
The plugin not yet compatible with bootstrap 5.
You have to use bootstrap 4
