### ISSUE TITLE
تغییر فرمت 

### ISSUE THREAD

**Issue by mojtabamoosavi** [Mds92/MD.BootstrapPersianDateTimePicker#24]
سلام
با تشکر از شما
من این دیت پیکر رو استفاده کردم ، فقط تنها مشکلی که داره اینه که وقتی فرمت نمایش تاریخ رو عوض می کنم هیچ تغییری نمی کنه
ممنون میشم راهنمایی کنید

**Comment by Mds92** [comment]
سلام
منظورتون اینه که اول یه فرمت گذاشتید بعد دینامیکی فرمت رو عوض میکنید؟
در این حالت نه کار نمیکنه
فرمت اولیه استفاده میشه

**Comment by mojtabamoosavi** [comment]
سلام مجدد
متشکر از پاسختون
نه همون فرمت اولیه رو استفاده می کنم ولی اعمال نمیشه

**Comment by Mds92** [comment]
فایل های دمو رو با دقت ببینید و همون رو پیاده سازی کنید
دقت کنید که آخرین ورژن رو دریافت کرده باشید
