### ISSUE TITLE
انتخاب چند تاریخ مختلف

### ISSUE THREAD

**Issue by esmaeiliehsan** [Mds92/MD.BootstrapPersianDateTimePicker#241]
سلام
چطور میشه چند تاریخ در بازه های زمانی مختلف رو بطور همزمان انتخاب کرد؟

یه سوال دیگه از این فانکشن هم میشه استفاده کرد به چه شکل؟
onDayClick(event)

**Comment by Raymonsystem** [comment]
یه سوال دیگه از این فانکشن هم میشه استفاده کرد به چه شکل؟
onDayClick(event)

**Comment by Mds92** [comment]
سلام
امکان انتخاب چندین تاریخ وجود ندارد

برای استفاده از 
onDayClick(event)
در مقدار دهی اولیه استفاده کنید

```
$('#date1').MdPersianDateTimePicker({
    targetTextSelector: '#inputDate1-text',
    targetDateSelector: '#inputDate1-date',
    enableTimePicker: true,
    onDayClick: () => {}
});
```

**Comment by esmaeiliehsan** [comment]
سلام
یه سوال چطوری میشه کاری کرد همه تعطیلات رو نمایش بده این فقط جمعه هارو داره به عنوان تعطیلی نمایش میده

**Comment by Mds92** [comment]
سلام
holiDays
که یک آرایه از تاریخ هاست
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#options

**Comment by esmaeiliehsan** [comment]
سلام
ممنون

1. فقط یه موردی داخل اون آرایه من باید همه روزهای تعطیل سال رو مشخص کنم؟؟ و اونوقت سال بعدش چی میشه؟؟
holiDays : [new Date(),new Date(2021,8,18),new Date(2021,8,19),new Date(2021,9,27)]
اینو میزنم یک ماه جلوتر رو تعطیل میکنه الان باید 27 و 28 همین ماه رو تعطیل نشون بده ولی مال ماه بعد رو تعطیل میکنه !!
2. در مورد onDayClick: () => {} هم یک توضیح میدین؟؟
3. و اینکه اصلا امکانش نیست حالت چند انتخابی رو بهش اضافه کرد؟؟ یا هر بار که تاریخ رو انتخاب میکنیم بریزه داخل یک آرایه ای و نشون بدیم  
ممنون
