### ISSUE TITLE
مشکل انتخاب ماه در دراپ داون

### ISSUE THREAD

**Issue by farshidpg** [Mds92/MD.BootstrapPersianDateTimePicker#243]
سلام ، وقتی بازه فعال بودن تاریخ اعمال میکنیم ، مثلا از امروز تا ۴ روز دیگه دراپ داون انتخاب ماه فقط ماه جاری رو قابل انتخاب میکنه و ماه بعدی با اینکه ۱ روز فعال داره اما فقط با فلش های جلو/عقب ماه امکان پیمایش دارد 

به تصویر زیر نگاه کنید 
مثلا تاریخ امروز + ۴ روز دیگر که میشه امروز تا ۱ مرداد فعال شده با استفاده از اپشن های پلاگین 

اما انتخاب ماه مرداد از دراپ داون  امکان پذیر نیست

![F7BEC318-A178-4DEB-8D0D-ECFC8AA18475](https://user-images.githubusercontent.com/9290073/126149999-9f9e5337-072c-4117-9c0b-dd0bc4271cef.jpeg)
![1A3EAB7F-9A3B-4A57-BB6E-6BCB45416971](https://user-images.githubusercontent.com/9290073/126150003-294d6734-cf11-4743-9b8e-622d5b3103f7.jpeg)
![2EAE9056-E3EA-4F86-A137-93C57B521571](https://user-images.githubusercontent.com/9290073/126150004-511f1e9f-6076-4d66-b8b3-f5401641c5ac.jpeg)

**Comment by Mds92** [comment]
سلام
ممنون میشم نمونه کد ارسال نمائید
بازه فعال بودن رو با کدام آپشن تنظیم میکنید؟

**Comment by farshidpg** [comment]
به این صورت تعریف کردم ، اما مشکل رو کامل توضیح دادم بیشتر فکر میکنم باگ ظاهری در کلاس ها باشه

```
$('#reservation_date').MdPersianDateTimePicker({
  trigger:'click',
  targetTextSelector: '#reservation_date',
  textFormat:textFormat,
  isGregorian : isGregorian,
  hideMonthYearBox : true,
  englishNumber:true,
  inLine: false,
  modalMode : true,
  disableBeforeToday:true,
  disabledDates : disabledDates,
  disableAfterDate:disableAfterDate,
  enableTimePicker: false,
});
```


متغیر های
```
textFormat
isGregorian
disabledDates
disableAfterDate
```
به صورت صحیح و طبق داکیومنت و فرمت مورد نیاز محاسبه شده و همه چی بدون ارور و به درستی کار میکنه اما اون باگ انتخاب ماه که بالا توضیح دادم وجود داره که باعث میشه کاربر در انتخاب ماه گیج بشه

**Comment by farshidpg** [comment]
این مشکل همچنان وجود دارد …

**Comment by Mds92** [comment]
لطفا نمونه کدی ارسال نمائید که خطا قابل مشاهده باشه
لطفا مطمئن شید که آخرین ورژن را دریافت کرده اید
