### ISSUE TITLE
خطا با bootstrap 5

### ISSUE THREAD

**Issue by majidpourdavood** [Mds92/MD.BootstrapPersianDateTimePicker#244]
ممنون میشم راهنمایی کنید.

Uncaught TypeError: a.popover is not a function

**Comment by Mds92** [comment]
این کتابخانه برای بوت استرپ 4 هست  وهنوز روی ورژن 5 قابل استفاده نیست

**Comment by aakousha** [comment]
اگر روی ورژن 5 هم اوکی کنید خیلی خیلی ممنون میشم. این پلاگین به نظرم عالیه

**Comment by Mds92** [comment]
سلام
در برنچی جدا در حال توسعه است
با توجه به تغییرات زیادی که تو بوت استرپ 5 داریم فکر میکنم انشالا تا 1 ماه دیگه آماده بشه
از جمله تغییرات، حذف جی کوئری هست که این موضوع یعنی ریفکتور و بازنویسی کامل

**Comment by Mds92** [comment]
ورژن بوت استرپ 5 آماده دریافت است، برنچ پیش فرض هم روی بوت استرپ 5 سوئیچ شد
