### ISSUE TITLE
خطای نال در پوپر بوت استرپ 4

### ISSUE THREAD

**Issue by Saghachi** [Mds92/MD.BootstrapPersianDateTimePicker#245]
سلام و خسته نباشید و تشکر از اسکریپت عالی تون

من از تقویم روی بوت استرپ 4 استفاده می کنم و برای انتخاب بازه زمانی ازش استفاده میکنم
از لحاظ تاریخ خوانی و... هیچ مشکلی وجود نداره ولی هر وقت که میخوام تقویم رو باز کنم خطای زیر توی کنسول مرورگرم میاد
popper.min.js:4 Uncaught TypeError: Cannot read property 'setAttribute' of null
میخواستم بدونم این خطایی که از سمت پوپر میاد مشکلی هست که از طریق اسکریپت تقویم حل بشه؟

![تصویر صفحه 2021-08-16 112517](https://user-images.githubusercontent.com/33099345/129523265-2583c019-b6d2-4b96-8c1e-f3ec42ca4833.jpg)

**Comment by Mds92** [comment]
سلام
من دارم لاگ خطا رو میبینم از طرف دیت پیکر نیست !
احتمال داره اسکریپتی خودتون دارید که این خطا رو داده میده
اگر stacktrace
رو بگذارید بهتر میشه گفت
تو پوشه demo
میتونید نمونه های بدون مشکل رو ببینید

**Comment by Saghachi** [comment]
من از یه دکمه با کد ساخته شده زیر استفاده میکنم

```
<button class="btn btn-info dropdown-toggle px-1" data-toggle="dropdown" id="select_date" data-mdpersiandatetimepicker="" data-uniqueid="8a7fbd36-4a65-488b-8d7f-e70a07472b4f" data-original-title="" title="" aria-describedby="popover419994">
<div id="selector_date_1">
<span>از </span><span id="selected_day">جمعه</span>
<br>
</div>
<span id="selected_date">۱۴۰۰/۰۵/۲۹</span>
</button>
```
این هم تصویر تریس از خطا، بنظرتون تداخل با چیز دیگه ای هست؟
![تصویر صفحه 2021-08-20 122920](https://user-images.githubusercontent.com/33099345/130201064-7ee0a1db-7cb2-4982-b100-d363a38d2fea.jpg)
![تصویر صفحه 2021-08-20 123106](https://user-images.githubusercontent.com/33099345/130201084-474b5264-5ef4-4193-b213-0fb315324448.jpg)

**Comment by Mds92** [comment]
این خطای مربوط به کد خودتان است و ارتباطی با دیت پیکر ندارد
