### ISSUE TITLE
قرار دادن دکمه حذف و امروز در پایین تقویم

### ISSUE THREAD

**Issue by mhsprog** [Mds92/MD.BootstrapPersianDateTimePicker#248]
سلام لطفاً دکمه حذف و امروز قرار بدید
به صورت که دکمه حذف مقدار انتخاب شده رو حذف کنه و تقویم به صورت اول برگرده
دکمه امروز با زدن اون، زمان امروز درج بشه
من این کار رو کردم خیلی کاربردی تر شده
به صورت زیر

![image](https://user-images.githubusercontent.com/16506261/133195220-8f92f7bb-127d-4452-93d1-aff562440dad.jpg)

**Comment by Mds92** [comment]
سلام
تشکر از شما
روی متن "امروز ..." کلیک کردن به امروز میره
نظر من:
در مورد حذف باید روی تکس باکس قرار داده بشه تا یکی کلیک کمتر بشه و همچنین برای حذف نیاز به باز کردن دیت پیکر نباشه
