### ISSUE TITLE
محاسبه اشتباه روز تعطیل

### ISSUE THREAD

**Issue by MiladGhazizadeh** [Mds92/MD.BootstrapPersianDateTimePicker#249]
سلام
ممنون از کتابخونه عالیتون
بعضی تعطیلی های رسمی رو اشتباه اعلام میکنه
مثلا 1400/07/06 رو میگه تعطیله که روز قبلش تعطیل بوده (اربعین حسینی)

**Comment by Mds92** [comment]
سلام
این تقویم فقط جمعه ها رو به عنوان تعطیلات علامت میزنه
بقیه رو خودتان باید ست کنید 
با استفاده از option
holiDays

**Comment by MiladGhazizadeh** [comment]
سلام
ممنون از پاسختون
