### ISSUE TITLE
نمایش فقط ماه و سال

### ISSUE THREAD

**Issue by dashti011** [Mds92/MD.BootstrapPersianDateTimePicker#25]
سلام ، چطور میتونم موقع انتخاب  تاریخ فقط ماه و سال در منو  باز شده نمایش داده بشه و روز ها مخفی بماند
مثلا من میخوام کاربر فقط بتونه برای گزارش گیری بزنه از ماه مهر 1395 تا آبان 1395

**Comment by Mds92** [comment]
سلام
برای این کار نباید از دیت پیکر استفاده کنید، باید دو تا کمبوباکس برای سال و ماه بزارید
