### ISSUE TITLE
بیست و چهار ساعته بودن

### ISSUE THREAD

**Issue by iranpourX** [Mds92/MD.BootstrapPersianDateTimePicker#250]
سلام
در صورت امکان انتخاب زمان رو 24 ساعته کنید که (AM, PM) حذف بشه

**Comment by Mds92** [comment]
سلام
تایم پیکر خود HTML و مرورگرها استفاده شده است
و متاسفانه فعلا قابل حذف نیست
البته در آینده ای نزدیک این امکان فراهم می شود
