### ISSUE TITLE
ذخیره اعداد در تاریخ شمسی در فرمت لاتین

### ISSUE THREAD

**Issue by silvana-tnk** [Mds92/MD.BootstrapPersianDateTimePicker#251]
سلام
ممنون بابت اشتراک گذاری و پروژه جذابتون

من میخوام وقتی تاریخ انتخاب میشه کاراکترها بصورت لاتین در فیلدجایگذاری بشود نه فارسی، دلیلش اینه که میخوام اعداد در پایگاه داده بصورت فرمت انگلیسی ثبت شود نه فارسی .
برای مثال در هنگام انتخاب یک تاریخ به این صورت در فیلد ذخیره میشود : ۱۴۰۰-۰۷-۱۴
من میخوام همین مقدار بصورت 1400-07-14 در فیلد قرار گیرد.
ممنون

**Comment by Mds92** [comment]
سلام
برای ارسال تاریخ برای بک اند و یا کار با اون باید از آبجکت تاریخ در جاوا اسکریپت استفاده نمائید
برای این کار میتونید از 
targetDateSelector
استفاده نمائید و داخل آن تاریخ میلادی ذخیره میشه
اما اگر به دنبال نمایش خود تاریخ شمسی به انگلیسی هستید 
فعلا این امکان روی آخرین ورژن نیست
در آینده اضافه می شود

**Comment by silvana-tnk** [comment]
بله من دنبال مورد دوم هستم، پس باید صبر کنیم
ممنونم بابت پاسخگویی سریع

**Comment by Mds92** [comment]
آپشن persianNumber
اضافه شد
به صورت پیش فرض false
است
