### ISSUE TITLE
پیشنهاد TimePicker 

### ISSUE THREAD

**Issue by Saghachi** [Mds92/MD.BootstrapPersianDateTimePicker#252]
سلام، ممنون از اسکریپت کامل و عالی
یه پیشنهاد داشتم برای استفاده مستقیم یا لینک کردن تایم پیکر [اینجا ](https://weareoutman.github.io/clockpicker/)به تقویم

برای بوت استرپ 4 که مقادیر ساعت بصورت دستی باید وارد بشه و چیزی براش درنظر نگرفتین
برای بوت استرپ 5 هم بنظر من یخورده کار باهاش کاربر پسند نیست، مخصوصا برای نسخه موبایل و روش انتخاب ساعت و روش بستن ساعت باز شده

من برای تاریخ هام از اسکریپت شما و برای ساعت ها از یه فیلد جداگانه برای این تایم پیکر استفاده میکنم
فکر میکنم اگه بتونید اینو مستقیم یا با واسطه بهم لینک کنید عالی میشه

**Comment by mahdisky** [comment]
اره منم موافقم

**Comment by farshidpg** [comment]
موافقم ولی  اون تایم پیکر شاید برای همه پروژه ها مناسب نباشه و یه حالت کلاسیک داره به نظرم از این استفاده بشه خیلی بهتره 

http://senthilraj.github.io/TimePicki/

من قبلا یه سری شخصی سازی هایی هم روی این پلاگین ساعت انجام دادم ، خیلی را دسته و به راحتی  قابل شخصی سازی
