### ISSUE TITLE
انتخاب روزهای فعال (برعکس disabledDates)

### ISSUE THREAD

**Issue by mahdisky** [Mds92/MD.BootstrapPersianDateTimePicker#253]
سلام 
میخواستم آرایه روزهای فعال رو بدم به تقویم
یعنی برعکس disabledDates؟

**Comment by Mds92** [comment]
سلام
موارد زیر را مطالعه کنید
```
disabledDays
disableBeforeToday 
disableAfterToday
disableBeforeDate
disableAfterDate
```

**Comment by mahdisky** [comment]
من برعکس این مورد رو میخوام
یعنی روزهای فعال رو بهش بدم ، بقیه موارد رو غیر فعال کنه

**Comment by Mds92** [comment]
فعلا چنین امکانی تو نرم افزار دیده نشده

**Comment by mahdisky** [comment]
خب میشه این امکان رو بزارید ؟

**Comment by mahdisky** [comment]
خودم این رو بخوام درست کنم کجا میتونم این رو درست کنم؟
enabledate آرایه ای بگیره روز های فعال رو و بقیه روزها غیر فعال باشن

**Comment by Mds92** [comment]
ببینید اون یکی آپشن کجا هست
مطابق همون عمل کنید

**Comment by mahdisky** [comment]
کدوم آپشن؟

**Comment by farshidpg** [comment]
@mahdisky

منظورشون از آپشن ، پارامتر های ورودی کتابخانه هستش توی آخرین نسخه متد correctOptionValue رو سرچ کنید و کد رو بخونید از اونجا شروع میشه و متد های دیگه هم باید بخونید و بررسی کنید و طبق بقیه پارامتر های  مربوط به تاریخ ها قابلیت مد نظر خودتون رو اضافه کنید .
