### ISSUE TITLE
بعد از نصب از ناگت چیکار کنیم؟

### ISSUE THREAD

**Issue by moohamad1378** [Mds92/MD.BootstrapPersianDateTimePicker#254]
سلام توی دانت 5 وقتی از ناگت پکیچ رو دانلود میکنیم توی قسمت دبلیو دبلیو دبلیو روت چیزی اضافه نمیشه که باهاش کار کنیم و یه مشکل جدی هست چطوری رفعش کنیم؟

**Comment by Mds92** [comment]
سلام
پکیج ناگت منسوخ شده است
تو مشخصات ناگت پکیج دقت میکردید بود
باید از 
npm 
استفاده کنید یا آخرین سورس را از همینجا دانلود کنید

**Comment by moohamad1378** [comment]
ممنون
