### ISSUE TITLE
جایگذاری تاریخ فارسی در targetDateSelector 

### ISSUE THREAD

**Issue by smartmob98** [Mds92/MD.BootstrapPersianDateTimePicker#255]
سلام وقت بخیر  و ممنون از زحماتی که برای این کتاب خانه عالی کشیدید.

در آپشن 
targetDateSelector 
جیکار باید بکنیم تا همون تاریخ فارسی رو جایگذاری کنه چون خودکار تبدیل میکنه به میلادی

**Comment by Mds92** [comment]
سلام
این آپشن فقط برای تاریخ میلادی است
اگر میخواهید از تاریخ شمسی استفاده کنید از آپشن 
targetTextSelector
استفاده کنید
