### ISSUE TITLE
تنظیم ساعت بر روی 00 در زمان باز شدن تقویم

### ISSUE THREAD

**Issue by ermya** [Mds92/MD.BootstrapPersianDateTimePicker#257]
سلام آیا راهی هست بشه ساعت تقویم رو روی 00 تنظیم کرد به صورت پیشفرض زمانی که تقویم باز میشه؟

**Comment by Mds92** [comment]
سلام
از آپشن selectedDate استفاده کنید
و ساعت را 00 انتخاب کنید
