### ISSUE TITLE
تاریخ روز

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#258]
با سلام میخام تاریخ روز  که خود تقویم پیش فرض انتخاب  کرده به   داخل  input نمایش بدم ولی متد 
var t =$('#lMStartDate').MdPersianDateTimePicker('getDate')
 خالی نمایش میده

**Comment by Mds92** [comment]
اگر از ورژن  بوت استرپ 5 استفاده میکنید جی کوئری غیر قابل  استفاده است 
بفرمایید از چه ورژنی استفاده میکنید؟

**Comment by amir3164** [comment]
با سلام از ورژن 4.5

**Comment by Mds92** [comment]
با سلام
شما باید از ورژن 4 استفاده کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/tree/master-bs4
اگر در این ورژن هم مشکل هست بفرمایید تا بررسی کنم
البته برای set کردن تاریخ باید از `setDate` استفاده کنید

**Comment by amir3164** [comment]
ممنون  از وقتی که میزارید .من تاریخ  جاری روی میخام.
ولی تقویم لود میشه یه تاریخ روز خودش انتخاب  کرده  من  اون تاریخ چطوری بگیرم و داخل textbox نشون بدم
