### ISSUE TITLE
am , pm انتخاب ساعت به صورت 24 ساعته و بدون 

### ISSUE THREAD

**Issue by keivansahebdelfard** [Mds92/MD.BootstrapPersianDateTimePicker#259]
سلام می خواستم  ببینم میشه امکان انتخاب ساعت به صورت 24 ساعته در حالت باز شدن تقویمو بزارید در حال حاضر فقط میشه از داخل متنش ویرایش کرد و داخل تقویم am , pm فعال هست

**Comment by Mds92** [comment]
سلام، با فعال کردن آپشن enableTimePicker میتونید ساعت را ویرایش کنید

**Comment by keivansahebdelfard** [comment]
واضح تر منظورمو می گم : وقتی تقویمو باز می کنم نمیخوام am,pm باشه 
عکس زیر رو ببینید 
![image](https://user-images.githubusercontent.com/63717001/154402394-f1e55fff-40b9-48ed-9799-c86fe024b59d.png)
با تشکر
