### ISSUE TITLE
مشکل در شناساییه jalali-moment

### ISSUE THREAD

**Issue by miladkardgar** [Mds92/MD.BootstrapPersianDateTimePicker#261]
در هنگام کلیک بر روی اینپوت تاریخ با خطای 
Uncaught Error: Invalid Jalali year -100721

روبرو میشم
در صورتی کهmoment.js  هم در سیستم لود شده
jquery 3.6
bootstrap 4.3.1

**Comment by Mds92** [comment]
سلام، این دیت پیکر در آخرین ورژن از کتابخانه هایی که گفتید استفاده نمیکنه
لطفا مطمئن شوید که روی آخرین ورژن هستید
