### ISSUE TITLE
Validation in DatePicker

### ISSUE THREAD

**Issue by KhashayarOkhovat** [Mds92/MD.BootstrapPersianDateTimePicker#264]
با سلام
هنگام استفاده از تقویم Jquery validation با datepicker تداخل ایجاد میکنه 
ممنون میشم راه حل لازمه رو ارئه بدید 
تشکر

**Comment by Mds92** [comment]
سلام، این دیت پیکر در آخرین ورژن روی بوت استرپ 5 هست و از جی کوئری استفاده نمی کنه
باید خودتان بررسی بفرمایید
