### ISSUE TITLE
Unix Time

### ISSUE THREAD

**Issue by belquran** [Mds92/MD.BootstrapPersianDateTimePicker#265]
سلام وقت بخیر
من راه حلی پیدا نکردم که بتونم UnixTime رو از کتابخونتون بگیرم
به طور مثال:
۱۳۹۰-۰۷-۲۵ ۲۱:۲۹:۵۸ ب ظ
این تاریخ یونیکس تایمش رو میخوام که میشه این عدد
1318874398806

**Comment by Mds92** [comment]
سلام، این کتابخانه که دیت پیکر هست و قاعدتا چنین کاری نمیکنه
شما می تونید مقداری که این کتابخانه در targetDateSelector قرار میده استفاده کنید
اونو تبدیل کنید به آبجکت Date در جاوا اسکریپت و سپس از اون استفاده کنید و UnixTime را استخراج کنید

**Comment by belquran** [comment]
ممنون بابت توضیحاتتون از این کد استفاده کردم

  //تاریخ میلادی رو میگیرم
        var DateTimeYadAvarDate=  $('#YadAvarDate').MdPersianDateTimePicker('getDate');
        //یونیکس تایمشو به دست میاریم
        var UnixTime=  new Date(DateTimeYadAvarDate).valueOf()
