### ISSUE TITLE
نحوه استفاده از پکیج با استفاده از alpinejs

### ISSUE THREAD

**Issue by aminmhz** [Mds92/MD.BootstrapPersianDateTimePicker#266]
سلام و عرض خسته نباشید
با توجه به اینکه من خیلی وقته از این پکیج شما توی پروژه های خودم دارم استفاده میکنم و جدیدا هم دارم از alpinejs توی پروژه ها استفاده میکنم در بخشی از قسمت ها، میخواستم نحوه استفاده از این پکیج رو توی alpinejs هم یه توضیحی بدید در صورتی که با alpinejs آشنایی دارید. 
با سپاس

**Comment by Mds92** [comment]
با سلام 
من با alpinejs کار نکردم
