### ISSUE TITLE
مشکل نمایش تاریخ سیو شده

### ISSUE THREAD

**Issue by vahidalvandi** [Mds92/MD.BootstrapPersianDateTimePicker#268]
سلام در هنگامی که میخواهم یک تاریخ مشخص را به صورت انتخاب شده در هنگام باز شدن صفحه قرار بدهم اجرا نمیشود این موضوع در نسخه قبلی مشکلی ندارد و با قرار گرفتن تاریخ میلادی در targetDateSelector به خوبی معادل شمسی آن را نشان میداد

**Comment by Mds92** [comment]
سلام، 
1. آیا در کنسول خطایی مشاهده میکنید یا خیر
2. در این ورژن باید از متد setDate استفاده نمایید

قسمت فانکشن ها را مطالعه نمایید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker#functions
