### ISSUE TITLE
تغییر علامت / به علامت - خط تیره بین اعداد

### ISSUE THREAD

**Issue by vahidalvandi** [Mds92/MD.BootstrapPersianDateTimePicker#27]
سلام من میخوام فرمت به صورت زیر باشه
  Format: 'yyyy-MM-dd',       

چطوری میتونم این کارو انجام بدم

ممنون

**Comment by Mds92** [comment]
سلام بله می تونید
لطفا فایل منوآل رو هم مشاهده کنید
کافی هست تا اتریبیوت زیر رو اضافه کنید
```
data-fromdate="yyyy-MM-dd"
```
