### ISSUE TITLE
how enable modal mode?

### ISSUE THREAD

**Issue by rezaamya** [Mds92/MD.BootstrapPersianDateTimePicker#270]
seems it can't be enabled by setting option on creating new datetime picker.
I have used following snippet of code, but it will hang and stop working without any response or any error on client and console.

```
const dtp1Instance = new mds.MdsPersianDateTimePicker(document.getElementById('dtp1'), {
  targetTextSelector: '[data-name="dtp1-text"]',
  targetDateSelector: '[data-name="dtp1-date"]',
  modalMode: true
});
```

**Comment by Mds92** [comment]
Please see the readme file and demo link
