### ISSUE TITLE
امکان استفاده در asp.net mvc

### ISSUE THREAD

**Issue by Tahere-NJ** [Mds92/MD.BootstrapPersianDateTimePicker#272]
با سلام و تشکر
آیا امکان استفاده از این کتابخانه در پروژه های mvc با فریمورک asp.net وجود دارد؟
در صورت امکان یه توضیح مختصر بفرمائید و بگید از کدام فایل ها باید در سمت JS استفاده نمود.
ممنون

**Comment by Mds92** [comment]
سلام
بله امکانش هست، اما اینطوری نیست که به صورت Component مربوط به C# اضافه بشه
باید تو UI اضافه کنید و تو فایل های cshtml استفاده بشه
روش استفاده خاصی نداره و مشابه دمو و توضیحات فایل readme عمل کنید اکی هست

**Comment by Tahere-NJ** [comment]
> سلام بله امکانش هست، اما اینطوری نیست که به صورت Component مربوط به C# اضافه بشه باید تو UI اضافه کنید و تو فایل های cshtml استفاده بشه روش استفاده خاصی نداره و مشابه دمو و توضیحات فایل readme عمل کنید اکی هست

**Comment by Tahere-NJ** [comment]
در کدهای صفحه cshtml از همون روش دمو استفاده کردم ولی وقتی آیکن تقویم رو کلیک می کنم همچین پیغامی توی کنسول در قسمت Issues ظاهر می شه و هیچ اتفاقی هم نمی افته. 
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
می شه لطفا من رو راهنمایی کنید.
