### ISSUE TITLE
مشکل بسته شدن مودال تاریخ 

### ISSUE THREAD

**Issue by Nimachegini** [Mds92/MD.BootstrapPersianDateTimePicker#275]
با سلام 
هنگام باز شدن تاریخ دیگر نمیتوان آن را بست .

**Comment by Mds92** [comment]
با سلام
ممنون میشم آخرین ورژن را دریافت و بررسی نمایید، در صورت وجود مشکل با نمونه کد برام ارسال کنید

**Comment by RayabDeveloper** [comment]
منم مشکل Modal داشتم، 2 بار Modal باز میشد. وقتی هم رو روزی کلیک میکردم رویداد انجام میشد ( Lable تغییر میکرد به تاریخی که کلیک شده ) اما Modal بسته نمیشد.
ولی خطایی که میداد مربوط به popper بود که میگفت بیشتر از یک بار ازش instance گرفته شده.
اول تا آخر این مشکل از این کتابخونه نیست. اینو میدونم. هر چیه مربوط میشه به کد های Bootstrap که به خاطر استفاده از Template Theme آماده پیش میاد. اگه از خود ورژن خام Bootstrap استفاده کنی فکر نمیکنم مشکلی باشه. ولی متاسفانه مجبوریم :-D منم از Inline تو Modal خودم استفاده کردم موضوع حل شد.
