### ISSUE TITLE
مشکل عدم نمایش مودال و تاریخ انتخاب شده

### ISSUE THREAD

**Issue by AdelZaghi** [Mds92/MD.BootstrapPersianDateTimePicker#277]
سلام
از اینکه این انتخاب کننده تاریخ و زمان فارسی رو درست کردید بسیار ممنونم.
من با دوتا مشکل برخوردم:
- یکی اینکه وقتی selectedDate رو مقدار دهی میکردم، تاریخ اولیه نمایش داده نمی شد.  بعد به این راه حل رسیدم که بعد از تعریف لازمه که updateSelectedDateText رو اجرا کنم:
dtp1Instance.updateSelectedDateText()
- مشکل بعدی این بود که وقتی modalMode = true می شه، دیگه تقویم نمایش داده نمی شود. این مشکل با اضافه کردن this.element.addEventListener("click", this.showPopoverEvent, !0) به enableMainEvents حل شد.

enableMainEvents() {
                        if (!this.setting.inLine)
                            if (null != this.bsPopover)
                                this.element.addEventListener("shown.bs.popover", this.popoverOrModalShownEvent),
                                    this.element.addEventListener("hidden.bs.popover", this.popoverOrModalHiddenEvent),
                                    this.element.addEventListener("inserted.bs.popover", this.popoverInsertedEvent),
                                    this.element.addEventListener("click", this.showPopoverEvent, !0);
                            else if (null != this.bsModal) {
                            const e = this.getModal();
                            if (null == e) return void console.error("mds.bs.datetimepicker: \`modalElement\` not found!");
                                e.addEventListener("shown.bs.modal", this.popoverOrModalShownEvent),
                                    e.addEventListener("hidden.bs.modal", this.popoverOrModalHiddenEvent);
`                            this.element.addEventListener("click", this.showPopoverEvent, !0);`
                        }
                    }

**Comment by Mds92** [comment]
سلام 
تشکر بابت راهنمایی کاربران
فقط دقت کنید فایل دمویی هست در قسمت readme که کدش میتونه راه گشا باشه براتون
