### ISSUE TITLE
خطا در هنگام لود صفحه و کارنکردن تقویم

### ISSUE THREAD

**Issue by NZ62AN** [Mds92/MD.BootstrapPersianDateTimePicker#278]
سلام و درود
فایلهای css , js رو طبق تصاویر زیر اضافه کردم ولی خطای jQuery میده که اونهم اضافه کردم بدون استفاده از این پکیج کار میکنه نمیدونم مشکل از کجاست؟ 

![1](https://user-images.githubusercontent.com/42322285/200492293-0ddf55d1-8ba6-4cfc-9eda-f768d5dc8908.PNG)

![2](https://user-images.githubusercontent.com/42322285/200492315-38b229a2-5cd4-4db2-bb49-07eda08b9d8e.PNG)

![3](https://user-images.githubusercontent.com/42322285/200492334-5197f4b6-40d9-4ebb-a614-f43d0fa9ed16.PNG)

**Comment by Mds92** [comment]
سلام
این پکیج در آخرین ورژن از بوت استرپ 5 استفاده میکنه و از جی کوئری استفاده نمیکنه، در نتیجه این خطای جی کوئری برای این پکیج نیست.
در ورژن های قبلی که بوت استارپ 4 استفاده میشد از جی کوئری استفاده میشد

**Comment by NZ62AN** [comment]
بله برای بوت استرپ 4 میخوام استفاده کنم و از نسخه 4 پکیج هم استفاده کردم راه حلی داره؟

**Comment by Mds92** [comment]
خطایی که بیان کردید اینه که هنوز کتابخانه جی کوئری لود نشده کتابخانه دیت پیکر میخواد ران شه
باید ابتدا کتابخانه جی کوئری را لود کنید و سپس این کتابخانه

**Comment by NZ62AN** [comment]
من همین کار رو کردم
محتویات فایل js:


import 'bootstrap';
// window.$=window.jquery=require('jquery');
import jQuery from 'jquery';
window.$ = jQuery;

import 'bootstrap/dist/js/bootstrap.bundle';
import 'bootstrap-select';


import 'jquery.easing';
import 'chart.js';


import { includes } from 'lodash';

//import md.bootstrap.datetimepicker
import 'md.bootstrappersiandatetimepicker/dist/jquery.md.bootstrap.datetimepicker'
..
..


محتویات فایل scss:

@import "@fortawesome\fontawesome-free\css\all.min.css";


// Import Custom SB Admin 2 Variables (Overrides Default Bootstrap Variables)

@import "variables.scss";

// Import Bootstrap
@import "bootstrap/scss/bootstrap.scss";



// Import Custom SB Admin 2 Mixins and Components
@import "mixins.scss";
@import "global.scss";
@import "utilities.scss";

// Custom Components
@import "dropdowns.scss";
@import "navs.scss";
@import "buttons.scss";
@import "cards.scss";
@import "charts.scss";
// @import "login.scss";
@import "error.scss";
@import "footer.scss";

//Import md.bootstrappersiandatetimepicker
 @import "md.bootstrappersiandatetimepicker\dist\jquery.md.bootstrap.datetimepicker.style.css";


محتویات فایل vite.config.js

import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';


export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/scss/Admin/sb-admin-2.scss',
                'resources/js/admin.js',
                'resources/js/chart-area-demo.js',
                'resources/js/chart-pie-demo.js'
            ],
            refresh: true,
        }),
        
    ],
    resolve: {
        alias: {
            '$': 'jQuery',
        },
    }

});

**Comment by NZ62AN** [comment]
درسته 
کد رو اینطور تغییر دادم خطای jQuery و $ برطرف شد اما یک خطای دیگه مونده:

(function ($) {
    "use strict"; // Start of use strict

    // Toggle the side navigation
    $("#sidebarToggle, #sidebarToggleTop").on('click', function (e) {
        $("body").toggleClass("sidebar-toggled");
        $(".sidebar").toggleClass("toggled");
        if ($(".sidebar").hasClass("toggled")) {
            $('.sidebar .collapse').collapse('hide');
        };
    });

    // Close any open menu accordions when window is resized below 768px
    $(window).resize(function () {
        if ($(window).width() < 768) {
            $('.sidebar .collapse').collapse('hide');
        };

        // Toggle the side navigation when window is resized below 480px
        if ($(window).width() < 480 && !$(".sidebar").hasClass("toggled")) {
            $("body").addClass("sidebar-toggled");
            $(".sidebar").addClass("toggled");
            $('.sidebar .collapse').collapse('hide');
        };
    });

    // Prevent the content wrapper from scrolling when the fixed side navigation hovered over
    $('body.fixed-nav .sidebar').on('mousewheel DOMMouseScroll wheel', function (e) {
        if ($(window).width() > 768) {
            var e0 = e.originalEvent,
                delta = e0.wheelDelta || -e0.detail;
            this.scrollTop += (delta < 0 ? 1 : -1) * 30;
            e.preventDefault();
        }
    });

    // Scroll to top button appear
    $(document).on('scroll', function () {
        var scrollDistance = $(this).scrollTop();
        if (scrollDistance > 100) {
            $('.scroll-to-top').fadeIn();
        } else {
            $('.scroll-to-top').fadeOut();
        }
    });

    // Smooth scrolling using jQuery easing
    $(document).on('click', 'a.scroll-to-top', function (e) {
        var $anchor = $(this);
        $('html, body').stop().animate({
            scrollTop: ($($anchor.attr('href')).offset().top)
        }, 1000, 'easeInOutExpo');
        e.preventDefault();
    });

})(jQuery); // End of use strict

//import md.bootstrap.datetimepicker
import 'md.bootstrappersiandatetimepicker/dist/jquery.md.bootstrap.datetimepicker'


تصویر خطای باقیمانده:
![Capture](https://user-images.githubusercontent.com/42322285/201409883-9ade3123-6897-4d2b-acc6-d8bdaf184195.PNG)
