### ISSUE TITLE
خطا در انتخاب امروز

### ISSUE THREAD

**Issue by Mr-Malekan** [Mds92/MD.BootstrapPersianDateTimePicker#279]
سلام

وقتی مودال باز میشه و یک تاریخی بجز تاریخ امروز انتخاب میشه و مودال بسته میشه و تاریخ انتخاب شده در اینپوت باکس قرار میگیره، و مجددا مودال رو جهت اصلاح تاریخ باز میکنیم، اگر روی "امروز" بزنیم، آخرین تاریخی که انتخاب کردیم بعنوان تاریخ امروز انتخاب میشه و نه تاریخ واقعی امروز!!

ممنون اگه رفع بشه

**Comment by Mds92** [comment]
سلام، معذرت بابت جواب دیر هنگام
شما تقویم را داخل مدال قرار دادید یا از modalMode خود تقویم استفاده کرده اید؟
آیا در نسخه دمو هم چنین مشکلی هست؟
