### ISSUE TITLE
نحوه استفاده در کندو گراید 

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mds92/MD.BootstrapPersianDateTimePicker#28]
سلام
با تشکر از کنترل زیبا و خوب شما
شاید اینجا جای این سوال نباشه و باید توی فروم ها مطرح بشه
ولی چ جوری توی گراید استفاده میشه بخصوص کندو
ممنون از شما

**Comment by Mds92** [comment]
سلام
ببینید این یه پلاگین جی کوئری هست بر مبنای بوت استرپ، اینکه توی گرید ویو چجوری استفاده کنید کاملا باید اچ تی ام الی هندل بشه
حالا کندو هم همینطور هست
اما اگر منظورتون این هست که کندو یه کامپوننت هست حالا تو اون چجوری استفاده کنیم، باید جایی داشته باشه تا تمپلیت بگیره
تمپلیت هم اچ تی ام الی میگیره، شما باید تو اون تمپلیت این کنترل رو جا بدید
من کندو کار نکردم
