### ISSUE TITLE
جلوگیری از بسته شدن مودال بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by arbabi2010** [Mds92/MD.BootstrapPersianDateTimePicker#281]
سلام. 
من میخوام وقتی توی حالت مودال باز میشه . تا دکمه ای که تعیین کردم برای تایید و بستن مودال رو نزدم ، مودال بسته نشه و تاریخ توی اینپوت قرار نگیره . چطوری میتونم این رو هندل کنم ؟
ممنون از راهنماییتون

**Comment by Mds92** [comment]
سلام
برای جلوگیری از بسته شدن مدال بوت استرپ، باید از خود بوت استرپ استفاده کنید
https://getbootstrap.com/docs/5.2/components/modal/#options

**Comment by arbabi2010** [comment]
> سلام برای جلوگیری از بسته شدن مدال بوت استرپ، باید از خود بوت استرپ استفاده کنید https://getbootstrap.com/docs/5.2/components/modal/#options

خیلی ممنون. منظورتون این هست که از modalMode  استفاده نکنم و خودم داخل مودال قرار بدم و به صورت inline داخل مودالم ازش استفاده کنم ؟

**Comment by Mds92** [comment]
بله این روش هم میتونید استفاده کنید
