### ISSUE TITLE
فراخوانی تابع setDatePersian بصورت خودکار

### ISSUE THREAD

**Issue by alimo2** [Mds92/MD.BootstrapPersianDateTimePicker#283]
سلام
اگر targetTextSelector مقدار پیش فرض داشته باشه - مثلا فرم ادیت یک رکورد رو نمایش میدهیم - بصورت خودکار تاریخ رو روی تقویم تنظیم نمی‌کند؟ مثلا  setDatePersian را بر اساس مقدار targetTextSelector صدا کند.

**Comment by Mds92** [comment]
سلام، مقدار پیش فرض منظورتون چی هست؟
منظورتون این هست که اگر targetTextSelector را مقدار دهی نکنید تقویم صحیح نمایش داده نمی شود؟

**Comment by alimo2** [comment]
نه منظورم این هست تقویم تاریخی که targetTextSelector در خودش داره نشون بده. مثلا 1330/10/11 مقدار targetTextSelector است و تقویم هم همون سال و دی ماه رو نمایش بده. قبل از اینکه خودمون دستی سال رو از ۱۴۰۱ به اون سال و ماه بیاریم.
وقتی صفحه ما لود شد، تقویم رو که باز میکنیم بصورت خودکار تاریخی که اینپوت وابسته بهش مقدار داره نمایش بده
الان من مجبورم خودم تاریخ تقویم رو با 
setDatePersian 
دستی تنظیم کنم.

**Comment by Mds92** [comment]
تقویم به طور خودکار مقداری که در targetDateSelector هست را نشان میدهد
المان targetTextSelector فقط جنبه نمایشی دارد و در صورتی که targetDateSelector مقدار داشته باشد المان targetTextSelector مقدار دهی می شود
اینو تست کنید

**Comment by alimo2** [comment]
> تقویم به طور خودکار مقداری که در targetDateSelector هست را نشان میدهد المان targetTextSelector فقط جنبه نمایشی دارد و در صورتی که targetDateSelector مقدار داشته باشد المان targetTextSelector مقدار دهی می شود اینو تست کنید

تست کردم اما به این شکل هم کار نکرد. یعنی تقویم خودش رو بر اساس مقدار targetDateSelector تنظیم نمیکنه. چه میلادی چه شمسی

**Comment by alimo2** [comment]
![Screenshot from 2023-02-21 13-49-52](https://user-images.githubusercontent.com/8406916/220317694-1c2bf44c-e34f-4426-b249-64809df0bbb2.png)
![Screenshot from 2023-02-21 13-51-45](https://user-images.githubusercontent.com/8406916/220318032-f9ab0145-74f7-4f65-863b-04fb62dcb99e.png)

**Comment by alimo2** [comment]
در تصاویر فوق کادر مشکلی پایین اینپوت targetDateSelector هست. که یکباربا  تاریخ میلادی یکبار شمسی مقدار دهی شده و صفحه پس از لود روی دکمه تاریخ کلیک شده. اما هربار تقویم تاریخ امروز رو نشون میده

**Comment by Mds92** [comment]
لطفا از آپشن های selectedDate یا selectedDateToShow یا selectedRangeDate استفاده نمایید
```
const dtp1Instance = new mds.MdsPersianDateTimePicker(document.getElementById('dtp1'), {
  targetTextSelector: '[data-name="dtp1-text"]',
  targetDateSelector: '[data-name="dtp1-date"]',
  selectedDate: new Date('2021-02-03')
});
```
