### ISSUE TITLE
مشکل چشمک زدن کلی تقویم، پس از انتخاب تاریخ

### ISSUE THREAD

**Issue by AlirezaPhf** [Mds92/MD.BootstrapPersianDateTimePicker#284]
بسیار متشکرم بابت توسعه این تقویم و ریفکتور کردن کدها 🙏
همه چی اکی هست
تنها مشکلی که دارم اینه که وقتی روی المنت موردنظر کلیک میکنم، تقویم باز میشه و تاریخ رو انتخاب میکنم بعدش تقویم بسته میشه.
که تا اینجا همه چی اکیه
برای بار دوم که روی المنت کلیک میکنم، تقویم باز میشه و سریع بسته میشه (یه حالت چشمک زدن)
و از این به بعد این حالت وجود خواهد داشت
این حالت، زمانی هم که روی المنت کلیک میکنم و تقویم باز میشه و دوباره روی المنت کلیک میکنم پیش میاد.

از آخرین ورژن پکیج و بوتسترپ استفاده میکنم + vitejs

main.js

```
import '~bootstrap/scss/bootstrap.scss';
import '~datepicker/dist/mds.bs.datetimepicker.style.css';

import * as bootstrap from 'bootstrap';
import * as datepicker from 'md.bootstrappersiandatetimepicker/dist/mds.bs.datetimepicker';

const selectDate = new datepicker.MdsPersianDateTimePicker(document.getElementById('dtp1'), {
    targetTextSelector: '[data-name="dtp1-text"]',
    targetDateSelector: '[data-name="dtp1-date"]',
});
```

index.html

```
<!doctype html>
<html dir="rtl" lang="fa">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap w/ Vite</title>
</head>

<body>
    <div class="input-group-text cursor-pointer" id="dtp1">📅</div>
    <input type="text" data-name="dtp1-text">
    <input type="text" data-name="dtp1-date">
    <!-- --- -->
    <script type="module" src="./js/main.js"></script>
</body>

</html>
```

ممنون میشم راهنمایی بفرمایید.

**Comment by Mds92** [comment]
سلام، خوشحالم که مورد استفاده بوده
با تو فایل دمو هم چنین مشکلی هست؟

**Comment by AlirezaPhf** [comment]
توی فایل دمو نه، کاملا صحیح و درست کار میکنه
https://stackblitz.com/edit/vitejs-vite-z3hd6h?file=main.js

ممنون میشم این آدرس رو یه چک بکنید

**Comment by Mds92** [comment]
پروژه ای که درست کردید کامل نیست
لطفا تمامی کد ها را مشابه آنچه که تو دمو هست تغییر دهید، بعد تست کنید

**Comment by AlirezaPhf** [comment]
موردی که ارسال کردم بالاتر، دقیقا مواردی هست که طبق داکیومنت و دقیقا از روی دمو پیاده سازی شده.
ممنون میشم اگه جایی اشتباهی انجام دادم کمکم کنید

**Comment by Mds92** [comment]
مشکل در `popover.setContent` ورژن جدید بوت استرپ بود.
در ورژن های قبلی مشکلی نبود تو ورژن 5.2 فراخوانی این متد باعث چشمک زدن popover می شد
ممنون میشم آخرین ورژن را دریافت و بررسی کنید
