### ISSUE TITLE
مشکل در پکیج NPM

### ISSUE THREAD

**Issue by irandoct** [Mds92/MD.BootstrapPersianDateTimePicker#285]
با درود 
من امروز از طریق NPM اقدام به آپدیت به نسخه آخر نمودم . در NPM نسخه 4.2.2 در دسترس است . وقتی از طریق NPM آپدیت کردم تقویم کار نمی کرد . فایل های نسخه 4.2.1 را مستقیما دانلود و جایگزین کردم درست شد . ظاهرا پکیج NPM به درستی آپلود نشده و فایل ها ناقص است. 
با تشکر

**Comment by Mds92** [comment]
با سلام،  
برای اطمینان دوباره بررسی و پابلیش کردم

**Comment by irandoct** [comment]
با سپاس از پیگیری سریع شما ... بله ویرایش 4.2.3 در دسترس است و درست کار می کند

**Comment by Mds92** [comment]
تشکر از گزارش شما
