### ISSUE TITLE
بسته نشدن اتوماتیک تقویم بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by irandoct** [Mds92/MD.BootstrapPersianDateTimePicker#286]
درود بر شما... بعد از انتخاب تاریخ ، تقویم به صورت اتوماتیک بسته نمی شود ؟ من باید در زمینه صفحه کلیک کنم تا تقویم بسته شود !؟ راهکار چیست ؟
من از بوتسترپ 5 استفاده می کنم 
ممنون

**Comment by Mds92** [comment]
سلام، وقت بخیر
آیا تو فایل دمو هم چنین مشکلی مشاهده میکنید؟
اگر نه لطفا نمونه کد برای بررسی ارسال کنید

**Comment by irandoct** [comment]
درود ... شما در صفحه اول سایت من می توانید مشکل را ببینید:
https://physiotherapy.ir
با سپاس

**Comment by Mds92** [comment]
سلام مجدد
من خطا را بررسی کردم
تو انتخاب روز خطای زیر رخ میده
```js
Uncaught TypeError: Illegal invocation
    at Object.findOne (selector-engine.js:24:44)
    at Fe._sanitizeAndSetContent (tooltip.js:386:44)
    at Fe.setContent (popover.js:88:10)
    at r.updateCalendarBodyHtml (mds.bs.datetimepicker.ts:1758:15)
    at r.selectDay (mds.bs.datetimepicker.ts:1907:12)
    at HTMLDocument.selectCorrectClickEvent (mds.bs.datetimepicker.ts:2075:12)
```
روی انتخاب روزها شما listener یی قرار دادید؟
کمی هم باهاش کلنجار رفتم، روی متد popover.setContent مربوط به bootstrap داره خطا میده !
دقیق نمیتونم بگم مشکل چی هست
اما چیزی نیست که کاملا مربوط به این دیت پیکر باشه، کتابخانه های زیادی تو این سایت استفاده شده
ممکن هست کانفلیکت باشه

**Comment by irandoct** [comment]
با نسخه قبلی و با بوتسترپ نسخه قبلی مشکلی نبود .... به نظرم در نسخه جدید بوتسترپ popover یک تغییر نسبت به نسخه های قبلی داشته

**Comment by irandoct** [comment]
آیا می توان با متد onDayClick پاپ آور را بست ؟

**Comment by Mds92** [comment]
الان با توجه به خطایی که دارید عملکرد تقویم ناقص می ماند، حتی اگر popover دستی بسته شود، تقویم کارش را انجام نداده است

**Comment by irandoct** [comment]
درود بر شما ... آیا برای مشکل فیکسی پیدا شد؟

**Comment by Mds92** [comment]
سلام، نیازمند دیباگ روی کد شماست، فرصت این کار را ندارم، در صورتی که مشکل را متوجه شدید به منم بگید کد را تصحیح کنم

**Comment by irandoct** [comment]
درود بر شما ... ظاهرا مشکل مربوط به ناسازگاری با ویرایش بوتسترپ 5 است ... احتمالا پست زیر شما را برای اصلاح کد کمک می کند :
https://www.sitepoint.com/community/t/getting-the-error-illegal-invocation-at-object/368942/13
https://github.com/twbs/bootstrap/issues/29561
ممنون از وقتی که می گذارید

**Comment by irandoct** [comment]
با درود مجدد 
مشکل مشابهی گزارش شده بود ... ممکن است مطالعه این پست برای رفع مشکل کمک کننده باشد 
https://github.com/twbs/bootstrap/issues/33388

**Comment by irandoct** [comment]
درود.. ظاهرا مشکل حل شده

**Comment by Mds92** [comment]
خدا را شکر
دقیق تر کد را بررسی کردم، خطایی پیدا کردم، اما بنظرم ارتباطی با این مشکل شما نداشت
مرتفع کردم مشکل را، مثل اینکه این مشکل هم حل شده
