### ISSUE TITLE
not Found Bootstrap in js file because  your version bootstrap 5.0.2 and for me 5.2.3

### ISSUE THREAD

**Issue by lifebyweb** [Mds92/MD.BootstrapPersianDateTimePicker#287]
سلام. وقتی نسخه ۴.۲ رو اجرا میکنم، ارور نشناختن bootstrap در فایل js رو میده

البته بعد از کلی جستجو پیدا کردم که نسخه بوت استرپ شما 5.0.2 هست
برای ما 5.2.3 بود
لطفا اگر میشه برای این نسخه مشکلش رو حل کنید
با تشکر

راستی یک پکیج دیگر هم دیدم که گفتم شاید بتونه کمک کنه
[https://github.com/majidh1/JalaliDatePicker](url)

**Comment by Mds92** [comment]
سلام، 
فایل package.json را ببینید، ورژن بوت استرپ استفاده شده 5.2.3 است که خوب تا همین الان آخرین ورژن stable از bootstrap است
این پروژه سه تا برنچ داره، از برنچ پیش فرض استفاده کنید یعنی master-bs5
یا از پکیج های npm برای استفاده از این پروژه استفاده کنید
