### ISSUE TITLE
Set the current Time in Persian Calendar

### ISSUE THREAD

**Issue by jmosawy** [Mds92/MD.BootstrapPersianDateTimePicker#29]
In Georgian calendar, when the calendar is displayed, I can see the current time when I want to select a datetime, but in Persian, the default time is set to `00:00:00`, but I want to be the current time.
Can you help me regarding this issue?

**Comment by Mds92** [comment]
I'll fix it as soon as possible

**Comment by Mds92** [comment]
Please get the latest version
