### ISSUE TITLE
گرفتن مقدار تاریخ انتخاب شده

### ISSUE THREAD

**Issue by mina1917** [Mds92/MD.BootstrapPersianDateTimePicker#290]
چه طوری می تونم مقدار تاریخی که کاربر انتخاب کرده رو بگیرم و سمت سرور بفرستم؟ اینو امتحان کردم نشد. ممنون
$'#startDate').MdsPersianDateTimePicker('getDate');

**Comment by RayabDeveloper** [comment]
درود;

من تو رویداد onDayClick این کد رو نوشتم.
همیشه تو کار با تقویم و تاریخ یه عالمه مشکل هست، حتی برای تاریخ میلادی، چه برسه به تاریخ شمسی.
ولی این کد کار میکنه:

onDayClick(e) {
        if (e.disabled === undefined) {
            var year = e.selectedDate.getFullYear();
            var month = e.selectedDate.getMonth() + 1;
            var day = e.selectedDate.getDate();
        }
    }

مثلا اون + 1 رو نذاری، حساب کتاب خودت اشتباه از آب در میاد ( به هر حال آرایه هستن دیگه ).
