### ISSUE TITLE
تنظیم اشتباه تاریخ

### ISSUE THREAD

**Issue by DariushHk** [Mds92/MD.BootstrapPersianDateTimePicker#294]
ظاهرا در کد تنظیم تاریخ شمسی
dtp1Instance.setDatePersian(1400, 06, 31)
خطا وجود دارد و پس از تنظیم با یک ماه اختلاف نمایش داده میشود.

**Comment by Mds92** [comment]
لطفا برای دوباره تولید کردن خطا نمونه کد ارسال نمایید

**Comment by DariushHk** [comment]
در دموی کامپوننت اگر بخواهیم مقدار تاریخ را بصورت شمسی ست کنیم
const dtp1 = new mds.MdsPersianDateTimePicker(document.getElementById('dtp1'), {
  targetTextSelector: '[data-name="dtp1-text"]',
  targetDateSelector: '[data-name="dtp1-date"]',
});
dtp1 .setDatePersian(1400, 06, 31);

تاریخ با سی روز جابجایی نمایش داده میشود. و به شکل 1400/07/30 ست میشود.

**Comment by Mds92** [comment]
لطفا آخرین ورژن دریافت و بررسی شود

**Comment by alimo2** [comment]
> در دموی کامپوننت اگر بخواهیم مقدار تاریخ را بصورت شمسی ست کنیم const dtp1 = new mds.MdsPersianDateTimePicker(document.getElementById('dtp1'), { targetTextSelector: '[data-name="dtp1-text"]', targetDateSelector: '[data-name="dtp1-date"]', }); dtp1 .setDatePersian(1400, 06, 31);
> 
> تاریخ با سی روز جابجایی نمایش داده میشود. و به شکل 1400/07/30 ست میشود.


در نسخه 4.2.4 همین مشکل وجود داره

**Comment by alimo2** [comment]
من هم این مشکل رو دارم با اینکه آخرین نسخه رو گرفتم. البته آخرین نسخه ریلیز شده 4.2.6 هست اما در دریافت فایل زیپ فایل 4.2.4 قرار داده شده

![image](https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/assets/8406916/973e946c-d0bd-4fc7-a205-c61dc2c6c3ec)

https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/archive/refs/tags/v4.2.4.zip

**Comment by alimo2** [comment]
مشکل در نسخه 4.2.6 ای که از کد دریافت شد حل شده. لطفا لینک ریلیز به 4.2.6  اصلاح شود. ممنون
