### ISSUE TITLE
امکان مقدار دهی اولیه

### ISSUE THREAD

**Issue by DariushHk** [Mds92/MD.BootstrapPersianDateTimePicker#295]
در ویرایش های قدیمی امکان مقدار دهی اولیه با value  وجود داشت. 
اما ظاهرا در ویرایش جدید وجود ندارد و یا توسط جاوااسکریپ حذف میشود.
مثلا اگر مقدار دهی زیر را داشته باشیم
  <input type="text" class="form-control" id="date-text" placeholder="متن فارسی" name="date-text" value="1402/02/24" >

پس از لود شدن عملا خالی نمایش داده میشود. 
ممنون از کامپوننت عالی

**Comment by Mds92** [comment]
سلام، باید از آپشن selectedDate استفاده کنید
تو پوشه دمو فایلی هست به نام `how-to-start.html` 
بنظرم کارت را راه میندازه

**Comment by DariushHk** [comment]
ممنون از پاسخگویی. از همین طریق حل شد.
