### ISSUE TITLE
راهنمایی در مورد فانکشن updateSelectedDateText

### ISSUE THREAD

**Issue by dashti011** [Mds92/MD.BootstrapPersianDateTimePicker#296]
با سلام و احترام
1:ممنون میشم راهنماییم کنید چطور میتونم از فانکشن updateSelectedDateText توی کدم استفاده کنم.

نمونه کد استفاده شده من به صورت زیر هست.
```html
<div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon-start"><i class="bi bi-calendar3"></i></span>
            <input type="text" class="form-control" placeholder="تاریخ شروع" aria-label="تاریخ شروع" data-name="dtp-start-text">
            <input type="hidden"   data-name="dtp-start-date">
       </div>
```
و بخش جاوا اسکریپت :

```js
var dtpStart = new mds.MdsPersianDateTimePicker(document.getElementById('basic-addon-start'), {
            targetTextSelector: '[data-name="dtp-start-text"]',
            targetDateSelector: '[data-name="dtp-start-date"]',
           
           
        });
```

2: هدفم برای استفاده از فانکشن بالا اینه که هر زمان تغییری در تاریخ انتخابی صورت گرفت یا حتی فیلد تاریخ پاک شد من متوجه بشم و فانکشن خاصی را صدا بزنم یا حتی یه Alert  ساده نشون بدم ، این فانکشن updateSelectedDateText همون کارو برام انجام میده ؟
چون اشنایی کاملی به نحوه استفاده از فانکشن ها و.. ندارم و کاملا مبتدی هستم . نمونه کد زیر هم تست کردم اما جواب نداد.
```js
var dtpEnd = new mds.MdsPersianDateTimePicker(document.getElementById('basic-addon-end'), {
                    targetTextSelector: '[data-name="dtp-end-text"]',
                    targetDateSelector: '[data-name="dtp-end-date"]',
                  
                });
        dtpEnd.updateSelectedDateText(alert('date end'));
```

**Comment by Mds92** [comment]
سلام
برای این که متوجه تغییر در تاریخ بشید، میتونید یه change listener روی المان `targetDateSelector` یا `targetTextSelector` بگذارید و نیازی به استفاده از متدهای این کتابخانه نیست.
متد `updateSelectedDateText` میاد متنی که در المان `targetTextSelector` قرار دارد را بروز میکند و کاری که شما میخواهید انجام بدهید چیز دیگری هست
