### ISSUE TITLE
پاک شدن value قبلی

### ISSUE THREAD

**Issue by fardezh** [Mds92/MD.BootstrapPersianDateTimePicker#297]
با سلام.
وقتی که روی یک input با type: text که از قبل یک value به طور string روش هست، تقویم رو initialize میکنیم، value قبلی پاک میشه. من نتونستم متدی پیدا کنم که بتونه value دیفالت برای اینپوت ها ست کنه یا حداقل جلوی پاک شدن value قبلی رو بگیره. اگر همچین متد یا setting ای وجود داره ممنون میشم بهم بگید. فکر میکردم با `()instance.updateSelectedDateText` میشد این کارو انجام داد و البته خیلی کار این متد رو هم متوجه نشدم چون که ورودی خاصی دریافت نمیکنه.

نمونه کد: 
```HTML
 <input type="text" class="persian-date" value="1402/01/01" />
```

```JS
const dateInput = $(".persian-date");
const instance = new mds.MdsPersianDateTimePicker(dateInput , {
      targetTextSelector: ".persian-date",
      textFormat: "yyyy/MM/dd",
      disableAfterToday: true,
    });
```

واضحه که input ای که روش تقویم init شده همون input تارگت برای خروجی هست.

**Comment by Mds92** [comment]
سلام، لطفا فایل مسیر زیر را بررسی کنید، تو این فایل نحوه استفاده از این تقویم با مقدار دهی اولیه نوشته شده
`demo/how-to-start.html`
