### ISSUE TITLE
persian date time picker bootstrap4

### ISSUE THREAD

**Issue by Mohammad-Abbasi2559** [Mds92/MD.BootstrapPersianDateTimePicker#298]
سلام من می خوام عرض تقویم رو تغییر بدم چون برای من تمام عرض صفحه رو می پوشونه ولی وقتی width رو تغییر می دم دیگه تقویم برام کار نمی کنه و وقتی inspect را می زنم به گوشه سمت راست تقویم رفته جایی که اصلا معلوم نیست
نمی دونم باید چی کارش کنم!
می شه راهنمایی کنید لطفا
خیلی ممنون

**Comment by Mds92** [comment]
سلام، این مورد کاملا مربوط به css های صفحه شما هست
برای آشنایی با این تقویم صفحات دمو و how to start را که در همین برنچ و پوشه دمو هست مشاهده کنید
