### ISSUE TITLE
مشکل جانمایی در زمان استفاده از Bootstrap-rtl

### ISSUE THREAD

**Issue by hp1361** [Mds92/MD.BootstrapPersianDateTimePicker#3]
با عرض سلام و خسته نباشید بابت ارائه این ابزار مفید

زمانیکه از Bootstrap-rtl جهت راست چین کردن صفحه استفاده میکنم، DatePicker در جای مناسب (با توجه به المان مربوطه) قرار نمیگیره.
از این نسخه استفاده میکنم:
https://www.nuget.org/packages/bootstrap-rtl/3.3.6

اگر راهنمایی بفرمایید ممنون میشم

**Comment by Mds92** [comment]
سلام، ممنون از شما
ببینید این تقویم بر اساس popover بوت استرپ هست، بنابراین اگر درست استفاده نمایید نباید مشکلی باشه
من خودم برای راست به چپ کردن از کتابخانه زیر استفاده میکنم، و مشکلی ندارم، به شما هم توصیه میکنم از همین کتابخانه استفاده کنید
https://github.com/morteza/bootstrap-rtl

**Comment by hp1361** [comment]
سلام

از نسخه ای که شما گفتید استفاده کردم و به خوبی کار کرد.

ممنون از بابت پیشنهاد این نسخه از Bootstrap-rtl

موفق باشید

2016-01-30 15:08 GMT+03:30 Mohammmad Dayyan <notifications@github.com>:

**Comment by Mds92** [comment]
سلام
خدا رو شکر که مشکلتون حل شد
