### ISSUE TITLE
[Feature request] Add date range select support instead of from to

### ISSUE THREAD

**Issue by sijav** [Mds92/MD.BootstrapPersianDateTimePicker#31]
Hi again,
And again thanks for this awesome plugin, I have one feature request which could be amassing to have.
I'm asking for date range select support like bootstrap [daterangepicker](http://www.daterangepicker.com/), it allows you to select between date range which is somehow like your plugin instead of two textbox, it uses only one with buttons to select the range (eg. last 30 days).
Implementing this would really great and support many things we need!

Thanks again for this great work. 👍

**Comment by Mds92** [comment]
Great, but it needs more work on this plugin,
Probably I work on it

**Comment by Mds92** [comment]
Please link  a demo

**Comment by sijav** [comment]
I did link a demo as [http://www.daterangepicker.com/](daterangepicker)

**Comment by Mds92** [comment]
Please get and test the latest version
