### ISSUE TITLE
Use With on the fly created textbox

### ISSUE THREAD

**Issue by behiunforgiven** [Mds92/MD.BootstrapPersianDateTimePicker#34]
When I Create a text box on the fly (With jQuery) Date picker shows , but can not set date value in textbox.
Is it a way to solve this?

**Comment by Mds92** [comment]
Can you get me a sample to test and debug?

**Comment by behiunforgiven** [comment]
This is my html for example
 `<div id="test"></div>`

and this is javascript part
`
var $textbox = $("<input class='datepicker' type='text' name='test' />");
        $textbox.MdPersianDateTimePicker();
        $("#test").html($textbox);
`

It shows the datepicker but can not set the date value in textbox.

It also changes these html properties:
`data-mdpersiandatetimepickerselecteddatetime = {"Year":1395,"Month":9,"Day":17,"Hour":10,"Minute":4,"Second":31}`

and 
`data-mdpersiandatetimepickershowing = false`

**Comment by behiunforgiven** [comment]
This is complete html page example that does not work
jquery version is : 3.1.0
bootstrap version is : 3.3.7

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>title</title>
    <link href="/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="/Content/bootstrap-rtl.css" rel="stylesheet" />
    <link href="/Content/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.css" rel="stylesheet" />
    <script src="/Scripts/jquery-3.1.0.min.js"></script>
    <script src="/Scripts/bootstrap.min.js"></script>
</head>
<body>
    <div class="container" style="max-width: 400px;">
        <div class="form-group">
            <div class="input-group">
                <input type="text" class="form-control" data-mddatetimepicker="true"  />
            </div>
        </div>
    </div>
    <script src="/Scripts/MdBootstrapPersianDateTimePicker/jalaali.js"></script>
    <script src="/Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js"></script>
</body>
</html>
```

**Comment by behiunforgiven** [comment]
Finally I found the bug !
it's about : "TargetSelector"
if I change the above code to this:
```html
<input type="text" class="form-control" id="fromDate" data-mddatetimepicker="true" data-targetselector="#fromDate" />
```
it works fine !
