### ISSUE TITLE
خروجی شمسی برای هر دو تقویم نمایش داده شده شمسی و میلادی

### ISSUE THREAD

**Issue by hp1361** [Mds92/MD.BootstrapPersianDateTimePicker#35]
با سلام به شما و تشکر بابت کار خوبتون
من از کامپوننت شما در برنامه ام جهت دریافت تاریخ بصورت رشته شمسی و تغییر اون در سمت سرور به کمک کامپوننت دیگر شما و ذخیره در بانک بصورت نوع تاریخ استفاده  میکنم.

مشکلی که وجود داره اینه که کاربر گاهی اوقات نیاز دار تاریخ را در انتخابگر تاریخ بصورت میلادی انتخاب نماید اما رشته نمایش داده شده در ادیتور بصورت شمسی باشد.

در صورت true کردن IsGregorian خروجی تقویم در ادیتور بصورت میلادی خواهد بود نه شمسی و علاوه بر اینکه نیاز کاربر برآورده نمیشود، در سمت سرور هم برای تبدیل با مشکل روبرو خواهم شد.

آیا امکانش هست تقویم هم بصورت میلادی و هم شمسی صرفاً خروجی رشته شمسی داشته باشه؟

ممنون

**Comment by Mds92** [comment]
سلام، خواهش میکنم، انشالا که فرهنگ اپن سورس هر روز بیشتر بین ما ایرانی ها جا بیوفته
اما در مورد مشکل شما
شما خودتون باید این رو هندل کنید، به این صورت که یه فیلد هیدن بگیرید و تاریخ رو به صورت یو تی سی تو اون ذخیره کنید
حالا کاربر هر چی میزنه شما تو فیلد هیدن خودتون تاریخ یو تی سی دارید
و طرف سرور هم مشکلی ندارید و به راحتی هندل میشه
