### ISSUE TITLE
بعد از نمایش باکس انتخاب تاریخ هیچ چیز عمل نمی کنه

### ISSUE THREAD

**Issue by MSAyrese** [Mds92/MD.BootstrapPersianDateTimePicker#37]
بعد از نمایش باکس انتخاب تاریخ هیچ چیز عمل نمی کنه و این خطا هارو تو کنسول دارم.
هر قدر که روی دکمه ای کلیک میکنم خطاها زیاد تر میشن.

لطفا راه حل ارائه کنید.
@Mds92 

`Uncaught TypeError: Cannot set property 'Day' of undefined
    at updateDateTimePickerHtml (PersianDateTimePicker.js:1331)
    at HTMLTableCellElement.<anonymous> (PersianDateTimePicker.js:1362)

//----------------------------------------------------------------------------

Uncaught TypeError: Cannot read property 'Month' of undefined
    at increaseOneMonth (PersianDateTimePicker.js:268)
    at updateDateTimePickerHtml (PersianDateTimePicker.js:1289)
    at HTMLButtonElement.<anonymous> (PersianDateTimePicker.js:1374)

//----------------------------------------------------------------------------

Uncaught TypeError: Cannot set property 'Year' of undefined
    at updateDateTimePickerHtml (PersianDateTimePicker.js:1350)
    at HTMLAnchorElement.<anonymous> (PersianDateTimePicker.js:1386)

//----------------------------------------------------------------------------`

**Comment by Mds92** [comment]
یکی از دموها رو با دقت نگاه کنید و مثل همون پیاده سازی نمایید
نباید مشکلی باشه

**Comment by MSAyrese** [comment]
راهنما رو قبلا دیدم. هیچ مشکلی از بابت پیاده سازی ندارم.
اگر مشکلی بود پس چرا باکس تقویم ضاهر شد؟

این راه حل هم (که خودتون تو فایلا اعمال کردین) هم مشکلو حل نکرد:
https://www.codeproject.com/Messages/5233105/Re-Problem-with-jquery-Validation.aspx

**Comment by MSAyrese** [comment]
خودم مشکلو حل کردم.
واقعا که چه پشتیبانی خوبی از پلاگینت داری...

**Comment by MSAyrese** [comment]
خودم مشکلو حل کردم.
واقعا که چه پشتیبانی خوبی از پلاگینت داری...
@Mds92

**Comment by Mds92** [comment]
میخوای پاشم بیام برات حل کنم
چقدر پرو هستن بعضیا
