### ISSUE TITLE
using both Jalali and Gregorian

### ISSUE THREAD

**Issue by NilooofarAfshar** [Mds92/MD.BootstrapPersianDateTimePicker#4]
I want to use this calendar with both Jalali and Gregorian configurations. Is it possible? (preferably with a button to switch between them)

**Comment by Mds92** [comment]
You can't use Md.PersianDateTime in this situation now.
But maybe in future I add an option to this library to switch between these calendar types.

**Comment by Mds92** [comment]
Please see the new Version
