### ISSUE TITLE
نبود روز سی ام

### ISSUE THREAD

**Issue by omidd1315** [Mds92/MD.BootstrapPersianDateTimePicker#41]
![capture](https://cloud.githubusercontent.com/assets/6449139/23101696/e6ed9b98-f6ae-11e6-81a3-c39e152fcc23.PNG)

ماه بهمن سال جاری روز سی ام ندارد

**Comment by Mds92** [comment]
آخرین ورژن رو دانلود کنید، من چنین مشکلی رو ندیدم

**Comment by Marjani** [comment]
من هم بررسی کردم، این مشکل وجود ندارد، پیشنهاد می کنم این موضوع را ببندید
