### ISSUE TITLE
نحوه استفاده در صورت استفاده از کلاس

### ISSUE THREAD

**Issue by h4m3d66** [Mds92/MD.BootstrapPersianDateTimePicker#47]
با سلام
در صورتی که بخوایم به المنت هایی که میخوایم دیت پیکر داشته باشن یک کلاس بدیم و همه اون المنت هایی که اون کلاس رو دارن دیت پیکرو نمایش بدن به صورتی که بعد از انتخاب تاریخ، تاریخ انتخاب شده داخل المنت خودش نمایش داده بشه به چه صورتی باید عمل کرد؟

 $('.datePicker').each(function() {
        $(this).MdPersianDateTimePicker({
        Placement: 'popover',
        Trigger: 'click',
        EnableTimePicker: false,
        TargetSelector: ???????????,
        GroupId: '',
        ToDate: false,
        FromDate: false,
        DisableBeforeToday: false,
        Disabled: false,
        Format: 'yyyy/MM/dd',
        IsGregorian: false,
        EnglishNumber: true,
    });
    });

**Comment by Ham3D** [comment]
If we choose to let TargetSelector empty it should pick its parent input right ?
but it wont.
how can we populate Target selector on the fly , for example when we use a plugin like jquery Repeater.

**Comment by Mds92** [comment]
سلام
راستش خوب متوجه نشدم چی میخواین دقیقا
اما به عنوان مثال میخواین تمامی المان هایی که کلاس cssClassName دارن DatePicker رو نشون بدن به روش زیر عمل کنید:
```
$('#ElementId').MdPersianDateTimePicker({
    Placement: 'left',
    Trigger: 'click',
    EnableTimePicker: false,
    TargetSelector: '#TargetId',
    GroupId: '',
    ToDate: false,
    FromDate: false,
    DisableBeforeToday: false,
    Disabled: false,
    Format: 'yyyy/MM/dd',
    IsGregorian: false
});
```

**Comment by Ham3D** [comment]
Perfect!

-- 
Wish you all the bests
Hamed Hojjati
