### ISSUE TITLE
Bootstrap v4

### ISSUE THREAD

**Issue by Amir-Afrootan** [Mds92/MD.BootstrapPersianDateTimePicker#48]
نسخه سازگار با Bootstrap v4 کی میاد؟

**Comment by Mds92** [comment]
خود بوت استرپ 4 هنوز بتا هست و نهایی نشده
انشالا بعد از نهایی شدن خود بوت استرپ 4

**Comment by Amir-Afrootan** [comment]
سلام مجدد محمد جان.
من تسلط کامل به html و css و js دارم همچنین ساختار بوت استرپ رو هم کامل میشناسم. خوشحال میشم کمکی از دستم بربیاد

**Comment by Mds92** [comment]
سلام امیر جان
ممنون از لطف شما
چشم کاری بود میگم خدمتتون

**Comment by Mds92** [comment]
بوت استرپ 4 دارای تغییرات اساسی روی نام کلاس هاست و همچنین گریدش خیلی فرق کرده
فکر نمیکنم این دیت پیکر رو برای بوت استرپ 4 ورژن بدم
برای اون میتونید از ورژن های زیر استفاده کنید
https://github.com/Mds92/mds-angular-datetime-picker-package

**Comment by Amir-Afrootan** [comment]
ولی من فکر میکنم بشه😏
________________________________
