### ISSUE TITLE
default dynamic date

### ISSUE THREAD

**Issue by sir-amins** [Mds92/MD.BootstrapPersianDateTimePicker#49]
hi

is there any option to set default date to dynamic date? for example TODAY?

<input id="textbox1"  data-targetselector="#textbox1" type="text" class="form-control" data-mddatetimepicker="true" value="۱۳۹۲/۰۱/۰۱" data-placement="right" />

i saw the demo but it is static ۱۳۹۲/۰۱/۰۱.
i want today to be selected on a INPUT when page loads.

like this :

 http://www.jqueryscript.net/demo/jQuery-Datepicker-Plugin-For-Persian-Date-persianDatepicker/

http://www.jqueryscript.net/time-clock/jQuery-Datepicker-Plugin-For-Persian-Date-persianDatepicker.html

with prior thanks

**Comment by Mds92** [comment]
Hello,
In current version you can set default datetime by yourself and with jQuery<br>
e.g:
```javascript
$('#Id').val('1396-06-16');
```
You have to calculate today by yourself.

**Comment by sir-amins** [comment]
could you please explain how to get current date by jalaali.js in jquery code before 

$('#Id').val('1396-06-16');

to set the current date in .val?

thanks
