### ISSUE TITLE
مشکل با کنترل سمت سرور

### ISSUE THREAD

**Issue by hamoonsh** [Mds92/MD.BootstrapPersianDateTimePicker#51]
سلام
وقتی تگ input  رو runat server قرار میدم باعث میشه که دیگه مقدار بهش نسبت داده نشه
میتونین راهنمایی کنین؟

**Comment by Mds92** [comment]
سلام
این به پلاگین جاوااسکریپتی برای جی کوئری هست 
به ASP.NET مرتبط نیست
مشکل شما احتمالا برای این هست که وقتی تگ 
runat server
روی input
قرار میدید آی دی کنترل عوض میشه
در نتیجه دیگه پلاگین نمیتونه تگس باکس رو پیدا کنه
