### ISSUE TITLE
مشکل نمایش در مودال

### ISSUE THREAD

**Issue by Hamidreza10** [Mds92/MD.BootstrapPersianDateTimePicker#52]
من این تقویمو رو یه مودال اجزا میکنم که وقتی بیرون مودال زده شد، مودال بسته میشه
الان وقتی تقویم روی مودال اجرا میشه وقتی یه تاریخ انتخاب میشه مودال بسته میشه.
میشه یه کاری کرد که تقویم رو یه div بخصوص بیاد که من ایدی divرو داشته باشم که مودال بسته نشه

**Comment by Mds92** [comment]
سلام
من مشکل رو بررسی کردم
اگر کاربر برای بستن تقویم بیرون از مدال کلیک کنه، مدال هم بسته میشه
اما اگر کاربر تاریخ انتخاب کنه مدال بسته نمیشه
خوب فعلا راه حلی ندارم به غیر از اینکه ترفند بزنید و انتخاب تاریخ رو جایی تو صفحه قرار بدید که خیلی کاربر نتونه برای بستن تقویم خارج از مدال کلیک کنه
