### ISSUE TITLE
ارسال تاریخ از سمت سرور

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mds92/MD.BootstrapPersianDateTimePicker#53]
فرض کنیم نیاز است تاریخهای یک هفته آینده به بعد نمایش داده شود و روزهای قبل نیز غیر فعال شود
وقتی تاریخ یک هفته آینده از سمت سرور یا کنترولر ارسال میشود و
کنترل نمایش داده میشود باز تاریخ روز جاری نمایش میدهد
`<button class="btn btn-default" data-disablebeforetoday="true" data-MdDateTimePicker="true" data-TargetSelector="#input1" data-EnableTimePicker="true" data-Placement="left" data-Trigger="click">انتخاب تاریخ</button> `
سوالم اینه چجوری تاریخ سرور در تگ های اچ تی ام ال 5 ست شود
متشکرم

**Comment by Mds92** [comment]
خوب این سوال مربوط به این پروژه نمیشه !!!
اما اگر منظورتون اینه که چجوری تاریخ این تقویم رو ست کنید، کافی هست که مقدار تگ مربوط به این تقویم رو مقدار دهی کنید
