### ISSUE TITLE
error onclick day

### ISSUE THREAD

**Issue by kafinetetaha** [Mds92/MD.BootstrapPersianDateTimePicker#54]
when on click day or today in calender show this error ( newDateTimeInJsonFormat is undefined)

**Comment by Mds92** [comment]
Please see DEMO files source

**Comment by kafinetetaha** [comment]
when use in mvc project, show this error !!!!

**Comment by Mds92** [comment]
What do you mean by MVC, it is a client project not server side

**Comment by mehrdadsamadie** [comment]
I have same error
when on click day or today in calender show this error ( newDateTimeInJsonFormat is undefined)

**Comment by Mds92** [comment]
Please describe more, it's not clear
