### ISSUE TITLE
add writeDateString option

### ISSUE THREAD

**Issue by HASSANDL** [Mds92/MD.BootstrapPersianDateTimePicker#55]
Hello, very thanks for this plugin.
I want until user click on day, date of input not update.
now user click next month input update but I want only user click on day this work.

```
// ماه بعدی
case changeDateTimeEnum.IncreaseMonth:
increaseOneMonth(newDateTimeInJsonFormat, isGregorianState);
writeDateString = false;
break;
```

**Comment by Mds92** [comment]
Hello,
You have to customize source code for it,
Right now, you have to customize code from line 1339
