### ISSUE TITLE
year range

### ISSUE THREAD

**Issue by nassajis** [Mds92/MD.BootstrapPersianDateTimePicker#58]
سلام برای اینکه بخوایم رنج نمایش و انتخاب سال که پیشفرض 10 سال هستش رو تغییر بدیم پارامتری مشخص شده؟

**Comment by Mds92** [comment]
سلام
فعلا پارامتری نداره و باید تو کد دست بزنید تا تغییر کنه

**Comment by nassajis** [comment]
اون خط کد کجاست که من تغییرش بدم>

**Comment by Mds92** [comment]
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/issues/69#issuecomment-363058608
