### ISSUE TITLE
نمایش تاریخ فارسی بدون کلیک

### ISSUE THREAD

**Issue by pta-soft** [Mds92/MD.BootstrapPersianDateTimePicker#59]
سلام و خسته نباشید و با تشکر از این دیتا پیکر خوبی که تهیه کردید.
 چطور میشه تاریخ رو وقتی لود میشه صفحه بدون کلیک نشون داد و به یه لیبل اختصاص داد 
چون تا کلیک نشه نمیشه نشون داد 
**مثلا این تاریخ وقتی صفحه لود میشه:
یک شنبه ۰۵ آذر ۱۳۹۶**

**Comment by Mds92** [comment]
سلام و ممنون از شما
وقتی داره صفحه لود میشه شما مقدار اولیه این تاریخ رو دارید دیگه
اونو داخل لیبل بزارید و داخل تکس باکس دیت پیکر هم بزارید
