### ISSUE TITLE
Incompatibility with Bootstrap 4

### ISSUE THREAD

**Issue by mortezafs** [Mds92/MD.BootstrapPersianDateTimePicker#60]
First of all, thanks for your efforts to design and develop this plugin.
Unfortunately, given the fact that the latest version of Bootstrap had a lot changes and now is incompatible with this plugin, this plugin is highly need to be compatible with the new version of Bootstrap.
This plugin with Bootstrap version 4 is unusable

Thank you.

**Comment by Mds92** [comment]
Your welcome and glad to use it.
Unfortunately, in Bootstrap 4 we have some fundamental changes, that you can see here
https://getbootstrap.com/docs/4.0/migration/
It couldn't(or is very hard) be compatible with Boostrap 4 and 3 at the same time
So I have to create another version, Maybe sometime

**Comment by Mds92** [comment]
Please see new version with supporting Bootstrap 4
