### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Andre-de-Vos** [Mds92/MD.BootstrapPersianDateTimePicker#64]
Dear Sina, 

Thanks for your plugin. Though I discovered what possibly is a bug. Using Gregorian calendar and setting EnglishNumber to false (or ommitting it) will result in farsi numbers in the imputfield. Next time you open the datapicker it tries to convert the number in the inputfield which results in NaN in the titlebar and no selectable days. When you replace the farsi numbers in the inputfield with latin numbers all works fine. I suggest setting EnglishNumbers to true when IsGregorian is true, or a check on numberformat when the number in the inputfield is used to set the selected date.
![datetimepicker](https://user-images.githubusercontent.com/26482010/35472996-339ec42e-0371-11e8-9624-c020ef895543.png)

Mersi baraye hameye zahmat keh keshidid,
Andre.

**Comment by Mds92** [comment]
Thanks for your report,
I just fix it, please get new version

**Comment by Andre-de-Vos** [comment]
Dastet dard nakone
