### ISSUE TITLE
Suggestion for adding functionality

### ISSUE THREAD

**Issue by Andre-de-Vos** [Mds92/MD.BootstrapPersianDateTimePicker#65]
Dear Sina,

What would be nice is when used language is independent of used calendar (gregorian/miladi/other). Then you could use the miladi calendar with month/daynames in any language you like and the same goes for the Gregorian calendar (e.g. daynames in Farsi, English, French, Arab etc..).
Another one is the switch to Miladi from Gregorian. It would be nice if you could also switch back to Gregorian again. 

Merci az hameh zahmet keh mikeshid!
Andre.

**Comment by Mds92** [comment]
Please see new version with supporting Bootstrap 4
