### ISSUE TITLE
month picker

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mds92/MD.BootstrapPersianDateTimePicker#67]
با تشکر از شما تقویم خیلی خوبی است
آیا امکان دارد 
month picker
به پروژه اضافه کنید ؟

**Comment by Mds92** [comment]
با سلام
منظورتون چیه دقیقا؟

**Comment by aliebrahimi2015** [comment]
بعضی وقتها نیاز هست تا  ماهی از ماههای شمسی یا میلادی انتخاب شود
منظورم اینه بجای روزهای تقویم , 12 ماه شمسی یا میلادی قرار بگیره و انتخاب هر ماه بیانگر روز اول یا اخر ان ماه باشد

**Comment by Mds92** [comment]
چنین چیزی رو میتونید با یه کمبو باکس پیاده کنید
مگر اینکه شکل خاصی مد نظر شما باشه
