### ISSUE TITLE
تغییر سال از 1356 تا 1401 به سال های دیگر

### ISSUE THREAD

**Issue by asfshop** [Mds92/MD.BootstrapPersianDateTimePicker#69]
با سلام 
چطوری میشه این رنج رو تغییر داد ، از سوالات قبلی متوجه شدم توی کد باید تغییر بدیم ، لطفا بگین از کجای کد میشه رنج سال رو تغییر داد .

با تشکر

**Comment by Mds92** [comment]
سلام
الان شما تو فایل زیر تو خط 727 میتونید این رنج رو تغییر بدید
`jquery.Bootstrap-PersianDateTimePicker.js`
