### ISSUE TITLE
Make it available in bower repositores

### ISSUE THREAD

**Issue by elhampour** [Mds92/MD.BootstrapPersianDateTimePicker#7]
It would be nice if you make this library available for bower installation. if you want i can help you do that.

**Comment by Mds92** [comment]
It would be OK if you do it.

**Comment by elhampour** [comment]
i did that. i made a fork of your project. and then create another project just for bower. because for bower we need bower.json file. if you want to change your files in order to be a bower project. you have to add the bower.json file, you can get that from my github repository.
secondly, you create a option for date to be rendered in both english and persian numbers. but for the actual calender you did not have any option, so add an option for the person/english calender numbers. see that in my fork version. then if you please with that , add it to the real project.

**Comment by Mds92** [comment]
Thanks, does it have any links to write it in read me file

**Comment by elhampour** [comment]
I did not understand what you meant. you want a read me file about the package ?and how did i create that ?

**Comment by Mds92** [comment]
In nuget we have a page belong to package.
e.g:
https://www.nuget.org/packages/MD.BootstrapPersianDateTimePicker/ for current project.
What about bower? Is it have a page to link it?

**Comment by elhampour** [comment]
[Bower Link](http://bower.io/search/?q=MD.BootstrapPersianDateTimePickerBower)

this is the link to bower repository, as you see if you click on the link , it is redirected to my git hub project. order the files like my git hub project (if you want), and let met know , that i delete my own repository and add your repository to github.

all im saying is that your project is good , and it would be nice to have it under the best client side framework (BOIWER).

**Comment by Younesi** [comment]
Thanks to mr @elhampour  for adding this package as a  Bower library 
@Mds92  Thank you for  package, It would be nice to backup and update on Bower too.
