### ISSUE TITLE
Date limit function has to be added.

### ISSUE THREAD

**Issue by cellbeansagar** [Mds92/MD.BootstrapPersianDateTimePicker#70]
Hello im not able to set the date limit in calender. 
Restrict the range of selectable dates with the minDate and maxDate options. 
Suppose i have to restrict the user to select the date from today till next 10 days. It cannot be done in existing build.
Also unable to add the validation on birthdate.

Please add features related to it.

**Comment by Mds92** [comment]
Please see new version
