### ISSUE TITLE
Uncaught ReferenceError: toJalaali is not defined

### ISSUE THREAD

**Issue by farshidrezaei** [Mds92/MD.BootstrapPersianDateTimePicker#71]
hi.
i use **npm** and **laravel webpack mix**. 
after execute `npm run dev` , when i load page i get this error:

```
Uncaught ReferenceError: toJalaali is not defined
    at getTodayCalendarInPersian (md-bootstrap-datepicker.js:453)
    at parsePersianDateTime (md-bootstrap-datepicker.js:855)
    at HTMLInputElement.<anonymous> (md-bootstrap-datepicker.js:1863)
    at Function.each (jquery.js:424)
    at jQuery.fn.init.each (jquery.js:259)
    at jQuery.fn.init.init (md-bootstrap-datepicker.js:1834)
    at jQuery.fn.init.$.fn.MdPersianDateTimePicker (md-bootstrap-datepicker.js:1952)
   ....
```

how can i fix it?

**Comment by Mds92** [comment]
Hello, How did you install `MD.BootstrapPersianDateTimePicker`?
Are you using Angular 5.*?

**Comment by farshidrezaei** [comment]
execute
 `npm install md.bootstrappersiandatetimepicker`
then
```
require('../../../../node_modules/md.bootstrappersiandatetimepicker/MD.BootstrapPersianDateTimePicker/Scripts/MdBootstrapPersianDateTimePicker/jalaali.js');
require('../../../../node_modules/md.bootstrappersiandatetimepicker/MD.BootstrapPersianDateTimePicker/Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js');
```
in datepicker.js file.

then 

mix.js('md-bootstrap-datepicker/md-bootstrap-datepicker.js', 'md-bootstrap-datepicker');

no. i use jquery.

**Comment by Mds92** [comment]
First: Don't use `npm install md.bootstrappersiandatetimepicker`, npm library is not up to date. Download latest release instead.
Second: You have to add both `*.js` files in `MdBootstrapPersianDateTimePicke` folder into your project. I mean:
```
jalaali.js
jquery.Bootstrap-PersianDateTimePicker.js
```
The order is important

**Comment by farshidrezaei** [comment]
thank you. 
so edit or update your readme.
