### ISSUE TITLE
Prevent change date in input when change month or year

### ISSUE THREAD

**Issue by mbasirati** [Mds92/MD.BootstrapPersianDateTimePicker#72]
I want when I change month or year, the date in my input doesn't change.
How can I do this?

**Comment by Mds92** [comment]
I couldn't understand you?
If you can please write in Persian

**Comment by mbasirati** [comment]
سلام
من میخوام وقتی روی دکمه های تغییر ماه یا سال کلیک میشه تاریخ داخل اینپوتم تغییر نکنه.
الان وقتی من ماه یا سال رو تغییر میدم مقدار تاریخ ست شده درون اینپوت هم تغییر میکنه
امیدوارم متوجه شده باشید

**Comment by Mds92** [comment]
سلام
یعنی میخواهید وقتی روی روز کلیک کرد مقدار داخل تکس باکس تغییر کنه و با تغییر ماه یا سال تغییری اتفاق نیوفته؟
درسته؟

**Comment by mbasirati** [comment]
بله دقیقا

**Comment by Mds92** [comment]
الان چنین چیزی نداریم و شما خودتون باید کد رو ویرایش کنید
اما با توجه به درخواست ها قصد دارم این گزینه رو بزارم به عنوان کانفیگ
