### ISSUE TITLE
افزودن فانکشن ایونت onselect

### ISSUE THREAD

**Issue by monavarian** [Mds92/MD.BootstrapPersianDateTimePicker#73]
اول که خیلی ممنون . واقعا پلاگین خوبی هست و خیلی کاربردیه . 
اما بدلیل نداشتن فانکشن مجبورم از یه پلاگین دیگه استفاده کنم 
ممنون میشم که این قضیه رو اضافه کنید 
مثل فانکشن های : 
onSelect 
همچنین اینکه بتونیم تاریخ هایی رو غیر فعال کنیم که کاربر اونها رو نتونه انتخاب کنه . مثلا یه ماه خاص یا یه روزهای خاص رو 
خیلی ممنون

**Comment by Mds92** [comment]
سلام
1. در مورد فانکشنی که گفتید، شما میتونید از اونت
onchange
استفاده کنید، به طور مثال مقدار انتخاب شده توسط تقویم باید داخل یه 
input
ریخته شه، روی اونت 
onchange
اون 
input
یه فانکشن بنویسید تا کار مورد نظر شما انجام بشه

2. در مورد غیر فعال شدن برخی تاریخ ها، هنوز چنین قابلیتی اضافه نکردم اما اگر تعداد درخواست ها زیرا باشه انشالا اونم اضافه میکنم
