### ISSUE TITLE
newDateTimeInJsonFormat is undefined

### ISSUE THREAD

**Issue by marooj** [Mds92/MD.BootstrapPersianDateTimePicker#74]
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]  profile.php
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.js:5:17117
Empty string passed to getElementById().  jquery.js:4:1404
TypeError: newDateTimeInJsonFormat is undefined[Learn More]  jquery.Bootstrap-PersianDateTimePicker.js:1412:39
	updateDateTimePickerHtml http://ideabaz.ir/admin/js/jquery.Bootstrap-PersianDateTimePicker.js:1412:39
	bindEvents/< http://ideabaz.ir/admin/js/jquery.Bootstrap-PersianDateTimePicker.js:1458:7
	dispatch http://ideabaz.ir/admin/js/jquery.js:5:14077
	add/v.handle http://ideabaz.ir/admin/js/jquery.js:5:10849

**Comment by Mds92** [comment]
سلام
من الان دوباره بررسی کرد خطایی ندیدم
لطفا نمونه کد بفرستید

**Comment by AzadySoft** [comment]
با سلام.
من هم امروز به این مشکل برخوردم و راهکارش هم پیدا کردم بعد از مدتها سر و کله زدن !
مشکل برمیگرده به ورژن بوت استرپ استفاده شده
اون اسکریپتی که همراه مثالهای پروژه داده شده، ورژن 
Bootstrap 3.3.7 
هست
در حالیکه من در پروژه ی خودم از ورژن
Bootstrap 3.0.0
استفاده میکردم.
بوت استرپ رو آپدیت کنید مشکل حل میشه.
در واقع 
Bootstrap.js
 رو باید آپدیت کنید.
موفق باشید.

**Comment by Mds92** [comment]
تشکر از پست شما
ورژن فعلی بوت استرپ استفاده شده 4.3.1 هست
