### ISSUE TITLE
نیاز به تغییر نوع تقویم جهت ذخیره سازی در بانک اطلاعات

### ISSUE THREAD

**Issue by seilsepor** [Mds92/MD.BootstrapPersianDateTimePicker#75]
با سلام. دوست عزیز
من تاریخ را با فرمت میلادی در بانک ذخیره میکنم. میخواستم بدونم شما همچین امکانی را در تقویم لحاظ نکردید که امکان نمایش تقویم به شمسی باشد ولی در زمینه و در هنگام تبادل اطلاعات با سرور ، تقویم میلادی ارسال و دریافت کند؟

**Comment by Mds92** [comment]
سلام
این موضوع باید توسط خود شما هندل شود، اما این تقویم تاریخ میلادی معادل را به شما میدهد
مثال:
شما باید روی onchange تکس باکس خود کدی معادل زیر قرار بدید
```javascript

$('#TextBoxId').on('change', function () {
    var dateTime = $('#TextBoxId').MdPersianDateTimePicker('getDate');
    console.log(dateTime);
    $('#HiddenDateField').val(dateTime);
});

```

**Comment by darvishiyan-mahdi** [comment]
با عرض سلام و خسته  نباشید من این کد شما رو میزارم اما مشکل داره راه دیگه ای ندارین؟
