### ISSUE TITLE
سازگاری با بوت‌استرپ ۴

### ISSUE THREAD

**Issue by esajjad** [Mds92/MD.BootstrapPersianDateTimePicker#78]
###### <h3>برای پشتیبانی این کامپوننت در بوت‌استرپ۴، اقدامات زیر باید انجام بشه:<h3>

> مقدار تمپلیت را با مقدار جدید تعویض کنید
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/blob/b5b959da149d8815627374ed3f926afd0be04089/MD.BootstrapPersianDateTimePicker/Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js#L1582

```js
template: '<div class="popover zIndexCorrected" role="tooltip"><div class="arrow"></div><h3 class="popover-header" data-name="md-datetimepicker-title" data-isgregorian="' + settings.IsGregorian + '"></h3><div class="popover-body" data-name="md-datetimepicker-popovercontent"></div></div>',
```

> نام کلاس باید اصلاح بشه
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker/blob/b5b959da149d8815627374ed3f926afd0be04089/MD.BootstrapPersianDateTimePicker/Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js#L1702

```js
$target.parents('.popover.show').length == 0)
```

**Comment by Mds92** [comment]
سلام
ممنون از توجه شما
انشالا برای بوت استرپ 4 قصد دارم تغییراتی اساسی بدم

**Comment by mohsen4887** [comment]
منتظر تغییرات برای سازگاری با بوت استرپ 4 هستم.
ممنون از شما دوستان عزیز

**Comment by amir3164** [comment]
سلام  من تغییرات انجام دادم ولی کارنمیکند

**Comment by Mds92** [comment]
انشالا به زودی برای نسخه 4 ورژن جدیدی میزارم

**Comment by eifo30** [comment]
با سلام...
میخواستم بپرسم تقریبا کی با ورژن چهار هماهنگ میشه؟
چون خودم بسیار عجله دارم میپرسم.

تشکر

**Comment by Mds92** [comment]
ورژن جدید با قابلیت بوت استرپ 4 را دانلود کنید
