### ISSUE TITLE
تعیین مقدار اولیه تاریخ

### ISSUE THREAD

**Issue by smrfakhri** [Mds92/MD.BootstrapPersianDateTimePicker#79]
با سلام و تشکر
آیا راهی هست که قبل از بارگذاری پلاگین، مقدار اولیه تاریخ را (مثلا با متغیری که از سرور ارسال میشود) ست کنیم
به گونه ای که اولین نمایش با آن تاریخ باشد
مثلا با اتریبیوتی بنام
data-initdate='1/4/1397'
چک کردم در موضوعات قبلی شما اشاره کرده بودید که کافیست مقدار value را ست کنیم
ولی این مقدار نه در خود تگ و نه در ست کردن با جکوئری کار نکرد یعنی باعث نشد
کل نمایش تقویم به آن تاریخ برود و همواره ماه و تاریخ جاری نمایش می یابد

**Comment by Mds92** [comment]
سلام
> چک کردم در موضوعات قبلی شما اشاره کرده بودید که کافیست مقدار value را ست کنیم
> ولی این مقدار نه در خود تگ و نه در ست کردن با جکوئری کار نکرد یعنی باعث نشد
> کل نمایش تقویم به آن تاریخ برود و همواره ماه و تاریخ جاری نمایش می یابد
ممنون میشم یه نمونه کد بدید
اگر تقویم به تاریخ ست شده در 
value
نرود، باگ هست و باید درست شود

**Comment by Mds92** [comment]
اول نمونه این کاری که می خواهید بکنید در فایل زیر هست
Demo2.html

من دقیقا کد شما رو تو فایل بالا و در انتهای اسکریپت های دیگر گذاشتم و مشکلی نبود !!!

**Comment by smrfakhri** [comment]
در حالتی که پلاگین بر روی تگ input قرار دارد مقدار value از تگ input بعنوان مقدار اولیه ست میشود ولی اگر در تگ div قرار گیرد و از همان ابتدا نمایش یابد چه باید کرد؟ در مثال زیر همیشه تاریخ جاری امروز ست میشود.

        <div class="form-group">
            <div value="۱۳۹۲/۰۱/۰۱" data-targetselector="#textbox1" data-mddatetimepicker="true" data-name="datepicker1" data-inline="true" data-isgregorian="false"></div>
            <input id="textbox1" type="text" value="۱۳۹۲/۰۱/۰۱" />
        </div>

**Comment by Mds92** [comment]
بله متوجه منظورتون شدم
این باگ هست
وقتی تقویم 
 data-inline="true" 
هست این مشکل هست
بررسی و درستش میکنم

**Comment by Mds92** [comment]
لطفا ورژن جدید رو از نوگت یا ان پی ام بگیرید
تست بفرمایید
باید درست شده باشه

**Comment by smrfakhri** [comment]
سلام
نسخه جدید گرفتم و در فایل demo1 شما تغییر زیر را انجام دادم کار نکرد

        <div class="form-group">
            <div data-value="1395/3/9" value="1395/3/9"
data-mddatetimepicker="true" data-inline="true" data-isgregorian="false"
data-targetselector="#fromDate0" data-enabletimepicker="false"
                 style="border: solid 1px #ccc;">
            </div>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" id="fromDate0"
value="1395/3/9" placeholder="تاریخ" readonly />
        </div>


2018-06-19 17:03 GMT+04:30 Mohammmad Dayyan <notifications@github.com>:

**Comment by smrfakhri** [comment]
بله درست شد
خیلی ممنون، لطف کردید
جزاکم الله خیرا

‫در ۲۹ خرداد ۱۳۹۷، ساعت ۱۸:۵۶‏، Mohammmad Dayyan‏ <notifications@github.com>
نوشت:‏

**Comment by Mds92** [comment]
یا علی

**Comment by smrfakhri** [comment]
علی یارت
جسارتا بنظرم اگه تگ data-value هم تعریف کنید برای مقدار دهی اولیه و خصوصا
اینکه بتونه آبجکت های نوع تاریخ که از سمت سرور میاد و میلادی هم هست رو قبول
کنه، بجا و مناسب باشه
یا خودش هوشمند تشخیص بده شمسیه یا میلادی، یا اینکه دو تا تگ باشه
data-gregorialvalue    و  data-persianvalue
ممنون


2018-06-19 20:38 GMT+04:30 Mohammmad Dayyan <notifications@github.com>:

**Comment by vahidalvandi** [comment]
```
$('[data-name="datepicker1"]').MdPersianDateTimePicker('setValue', '1395/7/2');
```

این فرمان خطا میدهد
setValue
یافت نمیشود

**Comment by Mds92** [comment]
من چنین متدی تو لیست متدهای پلاگین قرار ندادم
احتمالا از ورژن قبلی دارید استفاده میکنید
فایل readme
را مطالعه کنید

**Comment by vahidalvandi** [comment]
من میخوام در صفحه ویرایش با وارد کردن تاریخ شمسی در ورودی به صورت خودکار تاریخ میلادی هم دیده شود . اما این اتفاق نمی افتد اما اگر دیتاپیکر انتخاب شود معادل میلادی آن دیده میشود.
باید چکار کنم

ممنون

**Comment by Mds92** [comment]
یعنی دو تا پیکر دارید؟
یکی شمسی یکی میلادی؟
در این صورت باید از متد 
setDate
استفاده کنید
و پیکری را که باید آپدیت شود بروز کنید

**Comment by vahidalvandi** [comment]
به چه صورت میتوانم اعداد فارسی را به انگلیسی تبدیل کنم که در سرور تغییر تاریخ را انجام دهم؟

**Comment by Mds92** [comment]
ممنون میشم readme
را مطالعه کنید
شما باید آبجکت 
Date
به سرور ارسال کنید

`targetDateSelector` برای ذخیره آبجکت دیت
`englishNumber` برای انگلیسی کردن اعداد
