### ISSUE TITLE
نحوه بکارگیری در mvc form

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mds92/MD.BootstrapPersianDateTimePicker#8]
سلام
کنترل خوبی طراحی کردید ضمن تشکر از شما
زمانیکه درون فرم بکار برده شود چنانچه تکست باکس تاریخ فوکوس بگیرد 
تقویم نشون داده میشه وقتی یکی از روزهای تاریخ انتخاب میشه تکست باکس تاریخ به روز نمیشه
اگر راهنمایی کنید ممنون میشم
```
@using (Html.BeginForm())
{
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(m => m.StartDate, new { @class = "control-label", @for = "fromdate" })
                    <div class="input-group">
                        <span class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromdate" data-fromdate="true" data-enabletimepicker="false" data-placement="bottom">
                            <span class="fa fa-calendar"></span>
                        </span>
                        @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", id = "fromdate", placeholder = "از تاریخ", data_groupId = "group1", data_mddatetimepicker = "true", data_trigger = "focus", data_targetselector = "#fromdate", data_fromdate = "true", data_enabletimepicker = "false", data_placement = "bottom" })
                    </div>
                    @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
                </div>
}
```

**Comment by Mds92** [comment]
سلام
خوب شما تارگت رو دادید
#fromdate
تکس باکسی یا المانی با این شناسه وجود ندارد، به نظرم بهتر هست اول ام وی سی رو خوب یاد بگیرید. تو کد شما شناسه تکس باکس
StartDate
همون 
StartDate
است

**Comment by aliebrahimi2015** [comment]
ممنون از پاسخ شما
مشکل هنوز پابرجاست
شناسه  تکست باکس یا المان من با صفت 
id="fromdate"
 مشخص شده در سوال قبلیم مشخص هست برادر من
مشکل اینه با همین کد ناقص و سواد ناقص من اکر اون تگ 
@using (Html.BeginForm())
رو کامل برداریم به خوبی کار میکنه ولی درون فرم همون مشکل پابرجا هست

**Comment by Mds92** [comment]
لطفا خروجی Html
حاصل از کد بالاتون رو بزارید تا بشه فهمید مشکل چی هست

**Comment by aliebrahimi2015** [comment]
کدهای مثال خودتون رو توی یک فرم قرار دادم
  ها رو با کنتزل inputو یکی از 
 جایگذین میکنم TextBoxFor 
===================================================================
`  @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                  @*  <input type="text" class="form-control" id="fromDate1" placeholder="از تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="right"/>*@
                       @Html.TextBoxFor(m => m.StartDate, new { @class = "form-control", id = "fromDate1", placeholder = "از تاریخ", data_mddatetimepicker = "true", data_trigger = "focus", data_groupId = "group1", data_targetselector = "#fromdate1", data_fromdate = "true", data_enabletimepicker = "false", data_placement = "bottom" })

                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                    <input type="text" class="form-control" id="toDate1" placeholder="تا تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="true" data-placement="right" />
                </div>
            </div>
          
            <button type="button" onclick="save()" class="btn btn-primary">save</button>
        }`
todate وقتی برنامه اجرا میکنم و تاریخ دوم یعنی 
 فوکوس میگرد اگر تارخی  به دلخواه انتخاب کنم 
به درستی تکست ورودی تغییر میکنه ولی برای 
تاریخ قابل تغییر نیست TextBoxFor 

خروجی اچ تی امل به صورت زیر هست
`
<form action="/Reservation/Index" method="post"><input name="__RequestVerificationToken" type="hidden" value="ILuAQvpnKYrmqa02E3I9plZt2EvU5tHZOIzpd9w9vstZVO45q7xZb452kGeOspifo1Nh8GuCidnw-Kz8Uf-Qo5FpDqWeH5LXzL87ssD7v3eEuvFOW8JbBy2Qt43hMLM2LgfE6CLjdQLKMyQJcAG4Xw2" />            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                  
                       <input class="form-control" data-enabletimepicker="false" data-fromdate="true" data-groupId="group1" data-mddatetimepicker="true" data-placement="bottom" data-targetselector="#fromdate1" data-trigger="focus" data-val="true" data-val-required="اولین تاریخ رزرو را انتخاب کنید" id="fromDate1" name="StartDate" placeholder="از تاریخ" type="text" value="1395/02/01" />

                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                    <input type="text" class="form-control" id="toDate1" placeholder="تا تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="true" data-placement="right" />
                </div>
            </div>
            <button type="button" onclick="save()" class="btn btn-primary">save</button>
</form> 
`

**Comment by aliebrahimi2015** [comment]
<form action="/Reservation/Index" method="post"><input name="__RequestVerificationToken" type="hidden" value="ILuAQvpnKYrmqa02E3I9plZt2EvU5tHZOIzpd9w9vstZVO45q7xZb452kGeOspifo1Nh8GuCidnw-Kz8Uf-Qo5FpDqWeH5LXzL87ssD7v3eEuvFOW8JbBy2Qt43hMLM2LgfE6CLjdQLKMyQJcAG4Xw2" />            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                  
                       <input class="form-control" data-enabletimepicker="false" data-fromdate="true" data-groupId="group1" data-mddatetimepicker="true" data-placement="bottom" data-targetselector="#fromdate1" data-trigger="focus" data-val="true" data-val-required="اولین تاریخ رزرو را انتخاب کنید" id="fromDate1" name="StartDate" placeholder="از تاریخ" type="text" value="1395/02/01" />

                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="false" data-placement="left">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </div>
                    <input type="text" class="form-control" id="toDate1" placeholder="تا تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="true" data-placement="right" />
                </div>
            </div>
            <button type="button" onclick="save()" class="btn btn-primary">save</button>
</form>

**Comment by Mds92** [comment]
لطفا  اچ تا ام ال نهایی رو بزارید

**Comment by aliebrahimi2015** [comment]
درست میفرمایید مثال ام وی سی ندارید منظور من این بود که تگهاتون رو عینا از روی مثالدتون کپی کردم
توی فرم

`<form action="/reservation/getprereserve?class=form-inline&amp;role=form" method="post">            <div class="form-group">
               <div class="input-group">
                    <span class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromdate" data-fromdate="true" data-enabletimepicker="false" data-placement="bottom">
                        <span class="fa fa-calendar"></span>
                    </span>
                    <input class="form-control" data-enabletimepicker="false" data-fromdate="true" data-groupId="group1" data-mddatetimepicker="true" data-placement="bottom" data-targetselector="#fromdate" data-trigger="focus" data-val="true" data-val-required="اولین تاریخ رزرو را انتخاب کنید" id="fromdate" name="StartDate" placeholder="از تاریخ" type="text" value="1395/02/01" />
                </div>
            </div>
            <button type="submit" class="btn btn-primary">آماد سازی </button>
</form>`

**Comment by Mds92** [comment]
من کد تولید شده شما رو در فایل زیر که در سورس قرار دارد گذاشتم
`Views/test.html`
بدون مشکل اجرا شد و وقتی روی انتخاب تاریخ میزدم تاریخ انتخاب شده و در تکس باکس شما قرار میگرفت
خوبه که خودتون هم تست کنید

میشه بگیر مشکل دقیقا کجاست؟
شاید یه رفرنسی رو اضافه نکردید؟

**Comment by aliebrahimi2015** [comment]
`
   <form>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromdate" data-fromdate="true" data-enabletimepicker="false" data-placement="bottom"><span class="fa fa-calendar"></span></span>
                            <input class="form-control" data-enabletimepicker="false" data-fromdate="true" data-groupid="group1" data-mddatetimepicker="true" data-placement="bottom" data-targetselector="#fromdate" data-trigger="focus" data-val="true" data-val-required="اولین تاریخ رزرو را انتخاب کنید" id="fromdate" name="StartDate" placeholder="از تاریخ" type="text" value="1395/02/01" />
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">آماد سازی </button>
                </form>
`
من این کدها رو که گذاشتمش  بین تگ فرم 
Form  کار نمیکنه ولی اگر
رو بردارمش درست کار میکنه رفرنس خاصی هم نداره یک پروژه ساده اولیه ام وی سی میسازم و توی 
Razor 
کدهای شما رو کپی میکنم
از توجه شما ممنونم

**Comment by Mds92** [comment]
من یه بار دیگه دقیقا همین کدهای شما رو گذاشتم تو فایل 
`test.html`
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Persian DateTime</title>

    <link href="../Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="../Content/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="../Content/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.css" />

    <script src="../Scripts/jquery-2.1.4.js" type="text/javascript"></script>
    <script src="../Scripts/bootstrap.min.js" type="text/javascript"></script>

    <style type="text/css">
        body, table {
            font-family: 'Segoe UI', Tahoma;
            font-size: 14px;
        }
    </style>

</head>
<body>
    <div style="margin-top: 50px; clear: both;"></div>

    <div class="container" style="max-width: 400px;">

        <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                    <span class="glyphicon glyphicon-calendar"></span>
                </div>
                <input type="text" class="form-control" id="fromDate1" placeholder="از تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="right" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="false" data-placement="left">
                    <span class="glyphicon glyphicon-calendar"></span>
                </div>
                <input type="text" class="form-control" id="toDate1" placeholder="تا تاریخ" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#toDate1" data-groupid="group1" data-todate="true" data-enabletimepicker="true" data-placement="right" />
            </div>
        </div>
		
		<form>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon" data-mddatetimepicker="true" data-trigger="click" data-targetselector="#fromdate" data-fromdate="true" data-enabletimepicker="false" data-placement="bottom"><span class="fa fa-calendar"></span></span>
					<input class="form-control" data-enabletimepicker="false" data-fromdate="true" data-groupid="group1" data-mddatetimepicker="true" data-placement="bottom" data-targetselector="#fromdate" data-trigger="focus" data-val="true" data-val-required="اولین تاریخ رزرو را انتخاب کنید" id="fromdate" name="StartDate" placeholder="از تاریخ" type="text" value="1395/02/01" />
				</div>
			</div>
			<button type="submit" class="btn btn-primary">آماد سازی </button>
		</form>

    </div>

    <script src="../Scripts/MdBootstrapPersianDateTimePicker/jalaali.js" type="text/javascript"></script>
    <script src="../Scripts/MdBootstrapPersianDateTimePicker/jquery.Bootstrap-PersianDateTimePicker.js" type="text/javascript"></script>
</body>
</html>
```
برای من بدون مشکل اجرا میشه
مشکل شما جای دیگریست
