### ISSUE TITLE
مشکل در محدوده از تاریخ 

### ISSUE THREAD

**Issue by ashkan1234** [Mds92/MD.BootstrapPersianDateTimePicker#80]
سلام.
مشکلی در زمان استفاده از یک Datetime دارم.
وقتی میخوام  data-fromdate="true" باشه و  data-todate="false" ، تاریخ های قبل و بعد enable=false میشود.
در صورتی که میخوام فقط تاریخ های از آن روز به بعد فالس شود و تاریخ روزهای قبل فعال باشد!
این خروجی html : 

`<input name="ctl00$ContentPlaceHolder1$txtLostDate" type="text" id="txtLostDate" data-mddatetimepicker="true" data-fromdate="true" autocomplete="off" data-todate="false" data-targetselector="#txtLostDate" value="1397/04/13" maxlength="10" class="form-control emp-box-border" data-placement="right" data-enabletimepicker="false" data-trigger="focus" dir="ltr" placeholder="تاریخ مفقودی" data-groupid="group1" data-mdpersiandatetimepicker="" data-mdformat="yyyy/MM/dd" data-isline="false" data-mdpersiandatetimepickerselecteddatetime="{&quot;Year&quot;:1397,&quot;Month&quot;:4,&quot;Day&quot;:13,&quot;Hour&quot;:0,&quot;Minute&quot;:0,&quot;Second&quot;:0}" data-original-title="" title="" data-mdpersiandatetimepickershowing="false">`

**Comment by Mds92** [comment]
ورژن جدید با قابلیت بوت استرپ 4 را دانلود کنید
