### ISSUE TITLE
استفاده بصورت inline

### ISSUE THREAD

**Issue by mhmsignin** [Mds92/MD.BootstrapPersianDateTimePicker#83]
اگه قابلیت استفاده بصورت اینلاین هم به اضافه مورد قبلی به این پلاگین اضافه بشه، خدا پدر و مادر گرامیتون رو حفظ و رحمت کنه خدایی

**Comment by Mds92** [comment]
سلام
ممنون از شما
این قابلیت وجود داره
لطفا فایل های دمو مشاهده شود

**Comment by arbabi2010** [comment]
> سلام ممنون از شما این قابلیت وجود داره لطفا فایل های دمو مشاهده شود

سلام. من مجبورم توی پروژه ای که بوت استرپ سه هست استفاده کنم. توی ورژن 3 این پکیج وقتی inline  رو true  میکنی تقویم رو هم دیگه نشون نمیده
