### ISSUE TITLE
تداخل با fancybox v3.3.5

### ISSUE THREAD

**Issue by asfshop** [Mds92/MD.BootstrapPersianDateTimePicker#84]
سلام هنگام استفاده از پلاگین فنسی باکس در کنار پلاگین شما یک پنجره مدال باز میشود که کلمه آبجکت در آن نوشته شده است ، لطفا راهنمایی بفرمایید.

البته در فنسی باکس های نسخه های پایین تر این مشکل وجود ندارد .

![capture](https://user-images.githubusercontent.com/11470938/43507515-a0e58a1a-9582-11e8-8b3c-6f4cbeca35ce.JPG)

**Comment by Mds92** [comment]
با سلام
باید ببینید آیا خطایی در کنسول مرورگر وجود دارد یا نه؟

**Comment by asfshop** [comment]
خطایی وجود نداشت ، ولی بررسی کردم روی تریگر کلیک حساس هست و با تریگر کلیک مدال فنسی باکس هم لود میشه ، به صورت پیش فرض گذاشتم روی موس آور درست شد ولی وقتی روی اینپوت کلیک کنیم باز هم اون مدال فنسی باکس لود میشه ، اگر بررسی کنید ویه راه حل بهم بدین که با کلیک تداخلی با فنسی باکس نداشته باشه ممنون میشم

**Comment by Mds92** [comment]
ببینید من با فنسی باکس کار خیلی نکردم
نمیتونم بررسی کنم
چون شناخت فنسی باکس به طور کامل زمان نیاز داره
چرا از مدال خود بوت استرگ استفاده نمیکنید؟
