### ISSUE TITLE
سازگاری با بوت استرپ 4

### ISSUE THREAD

**Issue by amir3164** [Mds92/MD.BootstrapPersianDateTimePicker#85]
سلام اگه امکانش هست بابوت استرپ چهار نشخه اپدیت کنیدممنون

**Comment by mrbelial** [comment]
سلام
ممنون از کار خوبتون
منم همین مشکل رو دارم
اگه میشه با بوت استرپ 4 هم کار کنه خیلی خوبه

**Comment by Mds92** [comment]
سلام
به زودی ورژن جدید با بوت استرپ 4 و ویژگی های بهتر ریلیز خواهد شد، انشالا

**Comment by Mds92** [comment]
بروز رسانی شد
آخرین ورژن را دانلود کنید
