### ISSUE TITLE
not properly working in bootstrap 4.1

### ISSUE THREAD

**Issue by subaira2004** [Mds92/MD.BootstrapPersianDateTimePicker#86]
hi,
the popover shows only today date and its not showing the full calendar in bootstrap4.1
i am trying apply on text input (id = purchaseDate)
please find below config 
   $('#purchaseDate').MdPersianDateTimePicker({
            Placement: 'bottom',
            Trigger: 'focus',
            EnableTimePicker: false,
            TargetSelector: '#purchaseDate',
            GroupId: '',
            ToDate: false,
            FromDate: false,
            DisableBeforeToday: false,
            Disabled: false,
            Format: 'yyyy/MM/dd',
            IsGregorian: false,
            EnglishNumber: false,
            InLine: false
        });

**Comment by Mds92** [comment]
Hello, This plugin is no compatible with Bootstrap 4+ right now.

**Comment by subaira2004** [comment]
Hi mohammed

Thank you for your kind response
I understand.

Could you suggest any other calendar in this case which supports bootstrap 4
Or
Could you suggest any jquery  Persian calendar

Ps : i dont know Persian but my project is dual language(english/Persian)

Regards
Zubair
Dubai, UAE
0588991898

On Aug 18, 2018, at 2:03 PM, Mohammmad Dayyan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello, This plugin is no compatible with Bootstrap 4+ right now.

**Comment by Mds92** [comment]
Please check the following:
https://github.com/behzadi/persianDatepicker

**Comment by subaira2004** [comment]
Thank you for your kind suggestion


Regards
Zubair
Dubair, UAE


On Aug 18, 2018, at 2:12 PM, Mohammmad Dayyan <notifications@github.com<mailto:notifications@github.com>> wrote:


Please check the following:
https://github.com/behzadi/persianDatepicker
