### ISSUE TITLE
بالا نیامدن Popover

### ISSUE THREAD

**Issue by mojtabanpe** [Mds92/MD.BootstrapPersianDateTimePicker#87]
سلام
بوت استرپ و جی کوئری من اخرین اپدیت موجود هستند ولی هر کار میکنم سمپل پیشنهادی شما جوابگو 
نیست.پیشنهادی دارید که مشکا من رو حل کنه؟
خیلی ممنون

**Comment by Mds92** [comment]
سلام
چه خطایی داره میده؟
من تو آخرین ورژن اومدم از cdn
 به جای پوشه node_module
استفاده کردم
آخری رو تست کردی؟

**Comment by mojtabanpe** [comment]
اره مرسی درست شد.
ولی الان یه مشکل دیگه دارم که وقتی تاریخ رو به سمت سرور میفرستم و سال و ماه و روز رو میکشم بیرون نمیتونه هیچ کدوم رو به عدد تبدیل کنه 
راه حلی دارید؟امکانش هست قبل از فرستادن به سمت سرور به تاریخ میلادی تبدیل شه و اعداد هم فارسی فرستاده نشن؟

**Comment by Mds92** [comment]
این مشکل شما باعث شد ویژگی جدیدی به پلاگین اضافه کنم
`targetDateSelector`
این پراپرتی را ست نمائید تا به طور خودکار تاریخ میلادی انتخاب شده در آن قرار داده شود
مثلا سلکتور یه فیلد مخفی در آن قرار دهید
دقت نمائید 
`targetSelector`
به 
`targetTextSelector`
تغییر نام پیدا کرد
فایل readme را مطالعه کنید
