### ISSUE TITLE
انتخاب ساعت و روز

### ISSUE THREAD

**Issue by zhnm** [Mds92/MD.BootstrapPersianDateTimePicker#88]
سلام
مرسی از شما برای پلاگین خوبتون
در دمویی که قرار دادین یه باگ وجود داره
demo->Samples1.html
اگر اول تایم رو انتخاب کنیم بعد روز رو تایم آپدیت نشده و میپره
البته یه لحظه تایم درست نشون داده میشه ولی مجدد تایم دیفالت رو نشون میده
ممنون میشم بفرمایین باید چطور حلش کنم؟

**Comment by Mds92** [comment]
سلام، خواهش میکنم
بررسی و اطلاع رسانی میکنم

**Comment by Mds92** [comment]
لطفا ورژن جدید را دریافت و بررسی نمائید
