### ISSUE TITLE
Conflict with other js files

### ISSUE THREAD

**Issue by vahidst110** [Mds92/MD.BootstrapPersianDateTimePicker#89]
Hi 
First of all , i thanks a lot to design this plugin for iranian people.
I have amazing problem with this plugin.
When i add jquery.md.bootstrap.datetimepicker.js to project , my other javascript files stops. 
Means javascript intellisence not working at all . When i delete jquery.md.bootstrap.datetimepicker.js , anything is ok and no problem . I dont know what is  the problem.
Please help me .

**Comment by Mds92** [comment]
Hello,
You're welcome. Glad to help.

> When i add jquery.md.bootstrap.datetimepicker.js to project , my other javascript files stops.

You have to see your browser console window, probably you have an error, see that and post the error.

**Comment by vahidst110** [comment]
> Hello,
> You're welcome. Glad to help.
> 
> > When i add jquery.md.bootstrap.datetimepicker.js to project , my other javascript files stops.
> 
> You have to see your browser console window, probably you have an error, see that and post the error.

not exist any error in console window .
I find out that when i add javascript to project , all of code convert to comment . 
this issue cause intellisence stoping.
but i don't know why js codes convert to comment ?
look at the following link .
http://uupload.ir/files/h3c6_js.png

**Comment by Mds92** [comment]
I saw your picture, Line 10 is not comment, Visual Studio shows it as green by mistake.

**Comment by vahidst110** [comment]
Yes . I omite comments of line 10 ,
But visual studio again mistake . 
Do you test this javascript file on visual studio 2017 ver 15.8.0 or higher ?

**Comment by vahidst110** [comment]
Yes . I omite comments of line 10 ,
But visual studio again mistake . 
Do you test this javascript file on visual studio 2017 ver 15.8.0 or higher ?

**Comment by Mds92** [comment]
As I said It's not problem of `JS` file, `JS` file created by `webpack` and it's OK.
For testing open it with `notepad++`
You have to check your another javascript files.
