### ISSUE TITLE
disable بودن کنترلر

### ISSUE THREAD

**Issue by saria64** [Mds92/MD.BootstrapPersianDateTimePicker#9]
سلام دوست عزیز
میشه لطفا مورد من رو بررسی کنین که مشکل از کجاست
اسکریپت های مورد نیاز و همچنین سی اس اس هارو ادد کردم
 وقتی پیجم بالا میاد ، کنترلر تاریخ دیزیبلد هست. روش کلیک میکنم چیزی باز نمیشه
اتچ کردم عکس رو.

. موقع نمایش کنترلر بجای اینکه اون انتخاب کننده سمت چپ نشون داده بشه ، سمت راست نشون داده میشه.
من از مترونیک استفاده کردم .

امیدوارم بتونین کمکم کنید.

![untitled11](https://cloud.githubusercontent.com/assets/19488051/15423799/7206d6d4-1e94-11e6-93da-5ad152d35539.png)

**Comment by Mds92** [comment]
سلام
باید کد اچ تی ام ال صفحه تون رو بدید تا بتونم بگم علت چیه
با عکس نمیتونم چیزی بگم
