### ISSUE TITLE
عمل نکردن disablebeforetoday!

### ISSUE THREAD

**Issue by miladhashemi** [Mds92/MD.BootstrapPersianDateTimePicker#90]
سلام.
اگر این ویژگی true باشه کل تقویم غیرفعال میشه.

**Comment by Mds92** [comment]
سلام
من همین الان تست کردم
مشکلی نیست
فایل sample1
رو بروز کردم، مشاهده نمائید
دقت کنید
disableBeforeToday
دارای B بزرگ
و T بزرگ
 می باشد

**Comment by miladhashemi** [comment]
ممنونم از پاسخگوییتون
من از پلاگینی که با بوت استرپ 3 زحمت کشیدین نوشتید استفاده کردم. و از تگ های HTML استفاده کردم این مشکل هنوز دارم.

**Comment by Mds92** [comment]
بزارید بررسی کنم اعلام میکنم بهتون
