### ISSUE TITLE
موقعیت مکانی هنگام ظاهر شدن 

### ISSUE THREAD

**Issue by Ali-Azmoud** [Mds92/MD.BootstrapPersianDateTimePicker#91]
سلام. وقت بخیر
راستش یک مشکلی هست توی نمایش دیت پیکر، اینکه وقتی تریگر نمایش دیت پیکر جایی نزدیک به انتهای محدوده نمایشگر باشه، مثلا گوشه ها باشه، دیت پیکر ابتدا خارج از محدوده نمایش ظاهر میشه. و با یک اسکرول هوشمند عمل میکنه و یه جایی داخل محدوده نمایش تغییر مکان میده

مشکل در نمایش ابتدایی دیت پیکره
اگر این رو در لیست رفع باگ ها قرار بدید ممنون میشم.

**Comment by Mds92** [comment]
با سلام
این دیت پیکر از 
popover
بوت استرپ 4 استفاده میکنه واگر مشکلی هست مربوط میشه به بوت استرپ 4
ببینید شاید خود بوت استرپ برای این راه حلی گفته باشه
https://getbootstrap.com/docs/4.1/components/popovers/

اما یه راه دیگه اش  هم برای درست کردن این موضوع اینه که از آپشن
placement
استفاده کنید و جهتی رو بهش بدید که مشکل کمتری ایجاد میکنه

**Comment by irandoct** [comment]
من هم همین مشکل را دارم ....

**Comment by irandoct** [comment]
من خیلی بررسی کردم. ظاهرا مشکل از فایل استایل هستش ... مقدار پارامتر mds-bootstrap-persian-datetime-picker-popover باعث مشکل می شود . با تغییر مقدار عرض پاپ آور ناپدید می شود ...

**Comment by Mds92** [comment]
لطفا در صورتی که با استایلی این موضوع حل می شود اینجا قرار دهید تا در ریلیز بعدی در سورس قرار داده شود
با تشکر

**Comment by irandoct** [comment]
برای اصلاح مشکل کافی است مقدار right: auto; استایل مربوط به پاپ آور اضافه کنید . این مشکل به دلیل تنظیمات RTL بوت استرپ ایجاد شده است

**Comment by irandoct** [comment]
.mds-bootstrap-persian-datetime-picker-popover {
    max-width: 100%;
    -webkit-box-shadow: 0 5px 15px 1px rgba(0, 0, 0, 0.1);
    box-shadow: 0 5px 15px 1px rgba(0, 0, 0, 0.1);
    z-index: 999999999;
	right: auto;
}

**Comment by Mds92** [comment]
می تونم بپرسم چطور بوت استرپ 4 را راست به چپ می کنید؟
آیا وقتی راست به چپ  میکنید Popover های خود بوت استرپ هم مشکل دار می شوند؟

**Comment by irandoct** [comment]
هنگام راست به چپ کردن باید مقدار فاصله از راست را 0 بگذاریم. در خود بوت استرپ فاصله ها از چپ تنظیم می شوند ... همین تغییر فاصله از سمت راست باعث بروز مشکل برای popover می شد . وقتی شما بهش مقدار بدهید دیگر این مشکل بروز نمی کند ... بهتر است !important هم بهش اضافه کنید.

**Comment by irandoct** [comment]
http://bootstrap.rtlcss.com/docs/4.0/components/popovers/

**Comment by Mds92** [comment]
ببینید اگر این مشکل با این راست به چپ شدن ایجاد می شود، مشکل از این کتابخانه  هست نه خود بوت استرپ
اگر من مقدار زیر 
right: auto;
را به css های پلاگین اضافه کنم ممکن هست با کتابخانه های rtl
دیگر به مشکل بخوره یا در عملکرد خود پاپ اور بوت استرپ مشکل ایجاد شود
این پلاگین با بوت استرپ استاندارد ورژن 4 گسترش داده شده و در فایل دمو هم بدون مشکل قابل مشاهده می باشد
کسانی که این کتابخانه شما را استفاده میکنند باید خودشان فایل استایل را برای خودشان تنظیم کنند تا درست نمایش داده شود

با تشکر از شما
