### ISSUE TITLE
عمل نکردن disabledDates

### ISSUE THREAD

**Issue by ghost** [Mds92/MD.BootstrapPersianDateTimePicker#93]
سلام ، من بار ها و بار ها تست کردم ، همه ی موارد کار میکنه ولی این یه دونه هیچ جوره کار نمیکنه ، ممنون میشم پاسخ بدید ، اینم کد مربوطه >
     $('#datePicker').MdPersianDateTimePicker({
            targetTextSelector: '#datePicker',
            disableBeforeToday:true,
            disabledDates:[new Date(2018,10, 17),new Date(2018,10, 17)],

        });

**Comment by Mds92** [comment]
سلام
کدوم یکی کار نمیکنه
disableBeforeToday
یا 
disabledDates
فایل sample
موجود در پروژه رو دیدید؟

**Comment by ghost** [comment]
کار نمیکنه ، تو فایل سمپل هم نیست ، ممنون میشم ، زود تر راهنماییم کنید .disabledDates

**Comment by Mds92** [comment]
در ورژن بعدی درست می شود
