### ISSUE TITLE
عمل نکردن disabledDates

### ISSUE THREAD

**Issue by ghost** [Mds92/MD.BootstrapPersianDateTimePicker#94]
سلام قسمت
disabledDates
کار نمیکنه
اینم نمونه کد ، ممنون میشم راهنماییم کنید 
 $('#datePicker').MdPersianDateTimePicker({
            targetTextSelector: '#datePicker',
            disabledDates:[new Date(2018,10,18),new Date(2018,10,19)],

        });

**Comment by Mds92** [comment]
سلام
ورژن جدید را بگیرید
