### ISSUE TITLE
بخدا کار نمیکنه

### ISSUE THREAD

**Issue by ghost** [Mds92/MD.BootstrapPersianDateTimePicker#97]
disabledDates
کار نمیکنه بخدا ، شما تاریخ ماه پیش رو دادی ، بعدش از قبل از امروز رو هم دیسابل کردی ، مثلا شما 
2018/10/18 
رو غیر فعال کنید ، خداییش کار نمیکنه

**Comment by Mds92** [comment]
برو جاوا اسکریپت بیشتر بخون 
ببین عددهای ماه به چه معنا هستند
https://www.w3schools.com/js/js_date_methods.asp

`disabledDates: [new Date(Date.parse('2018/10/18'))]`
